-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity top_module_dataflow_in_loop_VITIS_LOOP_190_1_edg_img_0_RAM_AUTO_3R2W_memcore is 
    generic(
        MEM_TYPE        : string    := "auto"; 
        DataWidth       : integer   := 1; 
        AddressWidth    : integer   := 6;
        AddressRange    : integer   := 42
    ); 
    port (
        address0    : in std_logic_vector(AddressWidth-1 downto 0); 
        ce0         : in std_logic; 
        d0          : in std_logic_vector(DataWidth-1 downto 0); 
        we0         : in std_logic; 
        q0          : out std_logic_vector(DataWidth-1 downto 0);
        address1    : in std_logic_vector(AddressWidth-1 downto 0); 
        ce1         : in std_logic; 
        d1          : in std_logic_vector(DataWidth-1 downto 0); 
        we1         : in std_logic; 
        q1          : out std_logic_vector(DataWidth-1 downto 0);
        reset           : in std_logic; 
        clk             : in std_logic 
    ); 
end entity; 

architecture rtl of top_module_dataflow_in_loop_VITIS_LOOP_190_1_edg_img_0_RAM_AUTO_3R2W_memcore is 

signal address0_t1_tmp : std_logic_vector(AddressWidth-1 downto 0);
signal address1_t1_tmp : std_logic_vector(AddressWidth-1 downto 0);


type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 
-- Init 
shared variable ram : mem_array := (
    others=>(others=>'0')); -- 
attribute syn_ramstyle : string;
attribute syn_ramstyle of ram : variable is "auto";
attribute ram_style : string;
attribute ram_style of ram : variable is MEM_TYPE;


signal address0_t0 : std_logic_vector(AddressWidth-1 downto 0); 
signal address0_t1 : std_logic_vector(AddressWidth-1 downto 0); 
signal d0_t0 : std_logic_vector(DataWidth-1 downto 0);
signal we0_t0 : std_logic;
signal d0_t1 : std_logic_vector(DataWidth-1 downto 0);
signal we0_t1 : std_logic;
signal q0_t0 : std_logic_vector(DataWidth-1 downto 0);
signal q0_t1 : std_logic_vector(DataWidth-1 downto 0);
 
signal address1_t0 : std_logic_vector(AddressWidth-1 downto 0); 
signal address1_t1 : std_logic_vector(AddressWidth-1 downto 0); 
signal d1_t0 : std_logic_vector(DataWidth-1 downto 0);
signal we1_t0 : std_logic;
signal d1_t1 : std_logic_vector(DataWidth-1 downto 0);
signal we1_t1 : std_logic;
signal q1_t0 : std_logic_vector(DataWidth-1 downto 0);
signal q1_t1 : std_logic_vector(DataWidth-1 downto 0);
 

begin 


address0_t0 <= address0;
d0_t0 <= d0;
we0_t0 <= we0; -- 

q0 <= q0_t1;
 
address1_t0 <= address1;
d1_t0 <= d1;
we1_t0 <= we1; -- 

q1 <= q1_t1;
 


p_IO_pipeline_reg : process (clk)  
begin
    if (clk'event and clk = '1') then

        if (ce0 = '1') then
            address0_t1 <= address0_t0; 
            d0_t1 <= d0_t0;
            we0_t1 <= we0_t0;

            q0_t1 <= q0_t0;
        end if;
 
        if (ce1 = '1') then
            address1_t1 <= address1_t0; 
            d1_t1 <= d1_t0;
            we1_t1 <= we1_t0;

            q1_t1 <= q1_t0;
        end if;
 
    end if;
end process;


memory_access_guard_0: process (address0_t1) 
begin
    address0_t1_tmp <= address0_t1;
--synthesis translate_off
    if (CONV_INTEGER(address0_t1) > AddressRange-1) then
        address0_t1_tmp <= (others => '0');
    else 
       address0_t1_tmp <= address0_t1;
    end if;
--synthesis translate_on
end process;   -- 




--  read first
p_memory_access_0: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0_t0 <= ram(CONV_INTEGER(address0_t1_tmp));
            if (we0_t1 = '1') then 
                ram(CONV_INTEGER(address0_t1_tmp)) := d0_t1; 
            end if; 
        end if;
    end if;
end process;


 
memory_access_guard_1: process (address1_t1) 
begin
    address1_t1_tmp <= address1_t1;
--synthesis translate_off
    if (CONV_INTEGER(address1_t1) > AddressRange-1) then
        address1_t1_tmp <= (others => '0');
    else 
       address1_t1_tmp <= address1_t1;
    end if;
--synthesis translate_on
end process;   -- 




--  read first
p_memory_access_1: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce1 = '1') then 
            q1_t0 <= ram(CONV_INTEGER(address1_t1_tmp));
            if (we1_t1 = '1') then 
                ram(CONV_INTEGER(address1_t1_tmp)) := d1_t1; 
            end if; 
        end if;
    end if;
end process;


 

end rtl;
