-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_module_gaussian is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    y : IN STD_LOGIC_VECTOR (7 downto 0);
    img_ga_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_ga_0_ce0 : OUT STD_LOGIC;
    img_ga_0_we0 : OUT STD_LOGIC;
    img_ga_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_ga_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_ga_1_ce0 : OUT STD_LOGIC;
    img_ga_1_we0 : OUT STD_LOGIC;
    img_ga_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_ga_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_ga_2_ce0 : OUT STD_LOGIC;
    img_ga_2_we0 : OUT STD_LOGIC;
    img_ga_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_ga_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_ga_3_ce0 : OUT STD_LOGIC;
    img_ga_3_we0 : OUT STD_LOGIC;
    img_ga_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_in0_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in0_0_ce0 : OUT STD_LOGIC;
    img_in0_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in0_0_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in0_0_ce1 : OUT STD_LOGIC;
    img_in0_0_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in0_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in0_1_ce0 : OUT STD_LOGIC;
    img_in0_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in0_1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in0_1_ce1 : OUT STD_LOGIC;
    img_in0_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in0_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in0_2_ce0 : OUT STD_LOGIC;
    img_in0_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in0_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in0_3_ce0 : OUT STD_LOGIC;
    img_in0_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in1_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in1_0_ce0 : OUT STD_LOGIC;
    img_in1_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in1_0_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in1_0_ce1 : OUT STD_LOGIC;
    img_in1_0_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in1_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in1_1_ce0 : OUT STD_LOGIC;
    img_in1_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in1_1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in1_1_ce1 : OUT STD_LOGIC;
    img_in1_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in1_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in1_2_ce0 : OUT STD_LOGIC;
    img_in1_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in1_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in1_3_ce0 : OUT STD_LOGIC;
    img_in1_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in2_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in2_0_ce0 : OUT STD_LOGIC;
    img_in2_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in2_0_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in2_0_ce1 : OUT STD_LOGIC;
    img_in2_0_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in2_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in2_1_ce0 : OUT STD_LOGIC;
    img_in2_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in2_1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in2_1_ce1 : OUT STD_LOGIC;
    img_in2_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in2_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in2_2_ce0 : OUT STD_LOGIC;
    img_in2_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    img_in2_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    img_in2_3_ce0 : OUT STD_LOGIC;
    img_in2_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of top_module_gaussian is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv7_56 : STD_LOGIC_VECTOR (6 downto 0) := "1010110";
    constant ap_const_lv7_2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_const_lv7_5 : STD_LOGIC_VECTOR (6 downto 0) := "0000101";
    constant ap_const_lv7_4 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal x_reg_376 : STD_LOGIC_VECTOR (6 downto 0);
    signal y_read_reg_1131 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal tmp_reg_1135 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln6_fu_397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln8_fu_412_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln8_reg_1144 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln8_reg_1144_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln8_reg_1144_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln8_reg_1144_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln8_reg_1144_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln8_reg_1144_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln8_reg_1144_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln8_reg_1144_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln8_reg_1144_pp0_iter8_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln8_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_1188 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_1188_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_1188_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_1188_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_1188_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_1188_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_1188_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_1188_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_1188_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln25_7_reg_1192 : STD_LOGIC_VECTOR (4 downto 0);
    signal lshr_ln25_7_reg_1192_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal lshr_ln25_s_reg_1197 : STD_LOGIC_VECTOR (4 downto 0);
    signal lshr_ln25_s_reg_1197_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln8_fu_468_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal zext_ln25_1_fu_480_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln25_1_reg_1252 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln_reg_1267 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln25_1_reg_1272 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln25_1_reg_1272_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln25_2_reg_1277 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln27_2_reg_1282 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln25_3_reg_1287 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln25_4_reg_1292 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln25_5_reg_1297 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln27_4_reg_1302 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln27_4_reg_1302_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln27_5_reg_1307 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln25_6_reg_1312 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln25_6_reg_1312_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln25_6_reg_1312_pp0_iter5_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln27_6_reg_1317 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln27_6_reg_1317_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln26_1_reg_1327 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln26_2_reg_1332 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln27_1_reg_1338 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln27_1_reg_1338_pp0_iter5_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln27_1_reg_1338_pp0_iter6_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln27_fu_631_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln27_reg_1343 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln25_1_fu_637_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln25_1_reg_1348 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln25_1_reg_1348_pp0_iter5_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln26_3_reg_1353 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln26_4_reg_1358 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln26_5_reg_1363 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln27_3_reg_1368 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln27_5_fu_689_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln27_5_reg_1373 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln25_14_fu_698_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln25_14_reg_1378 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln25_14_reg_1378_pp0_iter5_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln26_6_reg_1384 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln27_7_fu_714_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln27_7_reg_1389 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln14_reg_1394 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln15_reg_1399 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln27_3_fu_746_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln27_3_reg_1404 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln25_fu_758_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln25_reg_1409 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln25_reg_1409_pp0_iter6_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln27_6_fu_773_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln27_6_reg_1414 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln25_11_fu_788_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln25_11_reg_1419 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln25_13_fu_794_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln25_13_reg_1424 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln25_7_reg_1429 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln26_7_reg_1434 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln26_7_reg_1434_pp0_iter6_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln27_8_fu_826_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln27_8_reg_1439 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln27_7_reg_1444 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln25_16_fu_848_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln25_16_reg_1449 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln25_16_reg_1449_pp0_iter6_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln25_8_reg_1454 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln25_9_reg_1459 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln26_8_reg_1464 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln27_8_reg_1469 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln27_10_fu_897_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln27_10_reg_1474 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln27_9_reg_1479 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln27_4_fu_919_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln27_4_reg_1484 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln25_6_fu_928_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln25_6_reg_1489 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln25_12_fu_939_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln25_12_reg_1494 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln25_15_fu_951_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln25_15_reg_1499 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln27_9_fu_966_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln27_9_reg_1504 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln25_18_fu_975_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln25_18_reg_1509 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln26_9_reg_1514 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln27_11_fu_1003_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln27_11_reg_1519 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln25_20_fu_1015_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln25_20_reg_1524 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln25_22_fu_1021_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln25_22_reg_1529 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln25_3_fu_1036_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln25_3_reg_1534 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln25_9_fu_1045_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln25_9_reg_1539 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln25_4_fu_1054_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln25_4_reg_1544 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln25_17_fu_1068_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln25_17_reg_1549 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln25_19_fu_1077_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln25_19_reg_1554 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln25_21_fu_1092_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln25_21_reg_1559 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln25_23_fu_1101_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln25_23_reg_1564 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln25_2_fu_1110_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln25_2_reg_1569 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln25_7_fu_1118_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln25_7_reg_1579 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln25_10_fu_1126_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln25_10_reg_1584 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_flush_enable : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln25_fu_474_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal img_in0_0_ce1_local : STD_LOGIC;
    signal img_in0_0_ce0_local : STD_LOGIC;
    signal img_in0_1_ce1_local : STD_LOGIC;
    signal img_in0_1_ce0_local : STD_LOGIC;
    signal img_in0_2_ce0_local : STD_LOGIC;
    signal img_in2_2_ce0_local : STD_LOGIC;
    signal img_in0_3_ce0_local : STD_LOGIC;
    signal img_in2_3_ce0_local : STD_LOGIC;
    signal img_in1_1_ce1_local : STD_LOGIC;
    signal img_in1_1_ce0_local : STD_LOGIC;
    signal img_in1_2_ce0_local : STD_LOGIC;
    signal img_in2_1_ce1_local : STD_LOGIC;
    signal img_in2_1_ce0_local : STD_LOGIC;
    signal img_in1_3_ce0_local : STD_LOGIC;
    signal img_in1_0_ce1_local : STD_LOGIC;
    signal img_in1_0_ce0_local : STD_LOGIC;
    signal img_in2_0_ce1_local : STD_LOGIC;
    signal img_in2_0_ce0_local : STD_LOGIC;
    signal img_ga_1_we0_local : STD_LOGIC;
    signal img_ga_1_ce0_local : STD_LOGIC;
    signal img_ga_0_we0_local : STD_LOGIC;
    signal img_ga_0_ce0_local : STD_LOGIC;
    signal img_ga_2_we0_local : STD_LOGIC;
    signal img_ga_2_ce0_local : STD_LOGIC;
    signal img_ga_3_we0_local : STD_LOGIC;
    signal img_ga_3_ce0_local : STD_LOGIC;
    signal lshr_ln8_fu_402_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln8_fu_422_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln25_5_fu_436_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln25_8_fu_452_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln25_fu_595_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln26_fu_598_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln27_10_fu_686_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln25_2_fu_640_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln26_1_fu_643_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln25_6_fu_695_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln27_3_fu_743_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln27_fu_740_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln27_5_fu_752_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln27_7_fu_755_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln27_12_fu_767_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln27_11_fu_764_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln27_13_fu_770_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln27_16_fu_782_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln27_17_fu_785_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln27_15_fu_779_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln27_19_fu_823_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln27_6_fu_800_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln27_21_fu_832_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln27_23_fu_835_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln27_26_fu_894_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln27_2_fu_916_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln27_1_fu_913_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln27_8_fu_925_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln25_7_fu_936_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln27_14_fu_933_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln25_9_fu_948_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln25_8_fu_945_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln27_20_fu_963_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln27_18_fu_960_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln26_2_fu_957_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln25_11_fu_972_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln27_27_fu_997_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln27_25_fu_994_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln27_28_fu_1000_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln27_30_fu_1009_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln26_3_fu_981_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln25_15_fu_1012_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln25_3_fu_1033_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln27_4_fu_1027_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln25_4_fu_1042_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln27_9_fu_1030_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln25_10_fu_1051_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln25_12_fu_1065_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln27_22_fu_1059_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln25_13_fu_1074_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln27_24_fu_1062_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln25_16_fu_1089_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln27_29_fu_1083_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln25_17_fu_1098_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln27_31_fu_1086_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln25_5_fu_1107_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln25_14_fu_1115_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln25_18_fu_1123_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    x_reg_376_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                x_reg_376 <= ap_const_lv7_0;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln8_fu_430_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                x_reg_376 <= add_ln8_fu_468_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln25_10_reg_1584 <= add_ln25_10_fu_1126_p2;
                add_ln25_11_reg_1419 <= add_ln25_11_fu_788_p2;
                add_ln25_12_reg_1494 <= add_ln25_12_fu_939_p2;
                add_ln25_13_reg_1424 <= add_ln25_13_fu_794_p2;
                add_ln25_14_reg_1378 <= add_ln25_14_fu_698_p2;
                add_ln25_14_reg_1378_pp0_iter5_reg <= add_ln25_14_reg_1378;
                add_ln25_15_reg_1499 <= add_ln25_15_fu_951_p2;
                add_ln25_16_reg_1449 <= add_ln25_16_fu_848_p2;
                add_ln25_16_reg_1449_pp0_iter6_reg <= add_ln25_16_reg_1449;
                add_ln25_17_reg_1549 <= add_ln25_17_fu_1068_p2;
                add_ln25_18_reg_1509 <= add_ln25_18_fu_975_p2;
                add_ln25_19_reg_1554 <= add_ln25_19_fu_1077_p2;
                add_ln25_20_reg_1524 <= add_ln25_20_fu_1015_p2;
                add_ln25_21_reg_1559 <= add_ln25_21_fu_1092_p2;
                add_ln25_22_reg_1529 <= add_ln25_22_fu_1021_p2;
                add_ln25_23_reg_1564 <= add_ln25_23_fu_1101_p2;
                add_ln25_2_reg_1569 <= add_ln25_2_fu_1110_p2;
                add_ln25_3_reg_1534 <= add_ln25_3_fu_1036_p2;
                add_ln25_4_reg_1544 <= add_ln25_4_fu_1054_p2;
                add_ln25_6_reg_1489 <= add_ln25_6_fu_928_p2;
                add_ln25_7_reg_1579 <= add_ln25_7_fu_1118_p2;
                add_ln25_9_reg_1539 <= add_ln25_9_fu_1045_p2;
                add_ln25_reg_1409 <= add_ln25_fu_758_p2;
                add_ln25_reg_1409_pp0_iter6_reg <= add_ln25_reg_1409;
                add_ln27_10_reg_1474 <= add_ln27_10_fu_897_p2;
                add_ln27_11_reg_1519 <= add_ln27_11_fu_1003_p2;
                add_ln27_3_reg_1404 <= add_ln27_3_fu_746_p2;
                add_ln27_4_reg_1484 <= add_ln27_4_fu_919_p2;
                add_ln27_5_reg_1373 <= add_ln27_5_fu_689_p2;
                add_ln27_6_reg_1414 <= add_ln27_6_fu_773_p2;
                add_ln27_7_reg_1389 <= add_ln27_7_fu_714_p2;
                add_ln27_8_reg_1439 <= add_ln27_8_fu_826_p2;
                add_ln27_9_reg_1504 <= add_ln27_9_fu_966_p2;
                add_ln27_reg_1343 <= add_ln27_fu_631_p2;
                icmp_ln8_reg_1188_pp0_iter2_reg <= icmp_ln8_reg_1188_pp0_iter1_reg;
                icmp_ln8_reg_1188_pp0_iter3_reg <= icmp_ln8_reg_1188_pp0_iter2_reg;
                icmp_ln8_reg_1188_pp0_iter4_reg <= icmp_ln8_reg_1188_pp0_iter3_reg;
                icmp_ln8_reg_1188_pp0_iter5_reg <= icmp_ln8_reg_1188_pp0_iter4_reg;
                icmp_ln8_reg_1188_pp0_iter6_reg <= icmp_ln8_reg_1188_pp0_iter5_reg;
                icmp_ln8_reg_1188_pp0_iter7_reg <= icmp_ln8_reg_1188_pp0_iter6_reg;
                icmp_ln8_reg_1188_pp0_iter8_reg <= icmp_ln8_reg_1188_pp0_iter7_reg;
                sext_ln25_1_reg_1348 <= sext_ln25_1_fu_637_p1;
                sext_ln25_1_reg_1348_pp0_iter5_reg <= sext_ln25_1_reg_1348;
                trunc_ln14_reg_1394 <= img_in1_0_q1(7 downto 3);
                trunc_ln15_reg_1399 <= img_in2_0_q1(7 downto 4);
                trunc_ln25_1_reg_1272 <= img_in0_1_q1(7 downto 3);
                trunc_ln25_1_reg_1272_pp0_iter4_reg <= trunc_ln25_1_reg_1272;
                trunc_ln25_2_reg_1277 <= img_in0_2_q0(7 downto 4);
                trunc_ln25_3_reg_1287 <= img_in0_1_q1(7 downto 4);
                trunc_ln25_4_reg_1292 <= img_in0_2_q0(7 downto 3);
                trunc_ln25_5_reg_1297 <= img_in0_3_q0(7 downto 4);
                trunc_ln25_6_reg_1312 <= img_in0_3_q0(7 downto 3);
                trunc_ln25_6_reg_1312_pp0_iter4_reg <= trunc_ln25_6_reg_1312;
                trunc_ln25_6_reg_1312_pp0_iter5_reg <= trunc_ln25_6_reg_1312_pp0_iter4_reg;
                trunc_ln25_7_reg_1429 <= img_in0_0_q0(7 downto 4);
                trunc_ln25_8_reg_1454 <= img_in0_0_q0(7 downto 3);
                trunc_ln25_9_reg_1459 <= img_in0_1_q0(7 downto 4);
                trunc_ln26_1_reg_1327 <= img_in1_1_q1(7 downto 2);
                trunc_ln26_2_reg_1332 <= img_in1_2_q0(7 downto 3);
                trunc_ln26_3_reg_1353 <= img_in1_1_q1(7 downto 3);
                trunc_ln26_4_reg_1358 <= img_in1_2_q0(7 downto 2);
                trunc_ln26_5_reg_1363 <= img_in1_3_q0(7 downto 3);
                trunc_ln26_6_reg_1384 <= img_in1_3_q0(7 downto 2);
                trunc_ln26_7_reg_1434 <= img_in1_0_q0(7 downto 3);
                trunc_ln26_7_reg_1434_pp0_iter6_reg <= trunc_ln26_7_reg_1434;
                trunc_ln26_8_reg_1464 <= img_in1_0_q0(7 downto 2);
                trunc_ln26_9_reg_1514 <= img_in1_1_q0(7 downto 3);
                trunc_ln27_1_reg_1338 <= img_in2_1_q1(7 downto 3);
                trunc_ln27_1_reg_1338_pp0_iter5_reg <= trunc_ln27_1_reg_1338;
                trunc_ln27_1_reg_1338_pp0_iter6_reg <= trunc_ln27_1_reg_1338_pp0_iter5_reg;
                trunc_ln27_2_reg_1282 <= img_in2_2_q0(7 downto 4);
                trunc_ln27_3_reg_1368 <= img_in2_1_q1(7 downto 4);
                trunc_ln27_4_reg_1302 <= img_in2_2_q0(7 downto 3);
                trunc_ln27_4_reg_1302_pp0_iter4_reg <= trunc_ln27_4_reg_1302;
                trunc_ln27_5_reg_1307 <= img_in2_3_q0(7 downto 4);
                trunc_ln27_6_reg_1317 <= img_in2_3_q0(7 downto 3);
                trunc_ln27_6_reg_1317_pp0_iter4_reg <= trunc_ln27_6_reg_1317;
                trunc_ln27_7_reg_1444 <= img_in2_0_q0(7 downto 4);
                trunc_ln27_8_reg_1469 <= img_in2_0_q0(7 downto 3);
                trunc_ln27_9_reg_1479 <= img_in2_1_q0(7 downto 4);
                trunc_ln_reg_1267 <= img_in0_0_q1(7 downto 4);
                    zext_ln25_1_reg_1252(4 downto 0) <= zext_ln25_1_fu_480_p1(4 downto 0);
                    zext_ln8_reg_1144_pp0_iter2_reg(4 downto 0) <= zext_ln8_reg_1144_pp0_iter1_reg(4 downto 0);
                    zext_ln8_reg_1144_pp0_iter3_reg(4 downto 0) <= zext_ln8_reg_1144_pp0_iter2_reg(4 downto 0);
                    zext_ln8_reg_1144_pp0_iter4_reg(4 downto 0) <= zext_ln8_reg_1144_pp0_iter3_reg(4 downto 0);
                    zext_ln8_reg_1144_pp0_iter5_reg(4 downto 0) <= zext_ln8_reg_1144_pp0_iter4_reg(4 downto 0);
                    zext_ln8_reg_1144_pp0_iter6_reg(4 downto 0) <= zext_ln8_reg_1144_pp0_iter5_reg(4 downto 0);
                    zext_ln8_reg_1144_pp0_iter7_reg(4 downto 0) <= zext_ln8_reg_1144_pp0_iter6_reg(4 downto 0);
                    zext_ln8_reg_1144_pp0_iter8_reg(4 downto 0) <= zext_ln8_reg_1144_pp0_iter7_reg(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln8_reg_1188 <= icmp_ln8_fu_430_p2;
                icmp_ln8_reg_1188_pp0_iter1_reg <= icmp_ln8_reg_1188;
                lshr_ln25_7_reg_1192 <= add_ln25_5_fu_436_p2(6 downto 2);
                lshr_ln25_7_reg_1192_pp0_iter1_reg <= lshr_ln25_7_reg_1192;
                lshr_ln25_s_reg_1197 <= add_ln25_8_fu_452_p2(6 downto 2);
                lshr_ln25_s_reg_1197_pp0_iter1_reg <= lshr_ln25_s_reg_1197;
                    zext_ln8_reg_1144(4 downto 0) <= zext_ln8_fu_412_p1(4 downto 0);
                    zext_ln8_reg_1144_pp0_iter1_reg(4 downto 0) <= zext_ln8_reg_1144(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                tmp_reg_1135 <= y(7 downto 1);
                y_read_reg_1131 <= y;
            end if;
        end if;
    end process;
    zext_ln8_reg_1144(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    zext_ln8_reg_1144_pp0_iter1_reg(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    zext_ln8_reg_1144_pp0_iter2_reg(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    zext_ln8_reg_1144_pp0_iter3_reg(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    zext_ln8_reg_1144_pp0_iter4_reg(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    zext_ln8_reg_1144_pp0_iter5_reg(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    zext_ln8_reg_1144_pp0_iter6_reg(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    zext_ln8_reg_1144_pp0_iter7_reg(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    zext_ln8_reg_1144_pp0_iter8_reg(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    zext_ln25_1_reg_1252(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, icmp_ln6_fu_397_p2, ap_CS_fsm_state2, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln6_fu_397_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln25_10_fu_1126_p2 <= std_logic_vector(signed(sext_ln25_18_fu_1123_p1) + signed(add_ln25_21_reg_1559));
    add_ln25_11_fu_788_p2 <= std_logic_vector(signed(sext_ln27_13_fu_770_p1) + signed(sext_ln27_16_fu_782_p1));
    add_ln25_12_fu_939_p2 <= std_logic_vector(signed(sext_ln25_7_fu_936_p1) + signed(sext_ln27_14_fu_933_p1));
    add_ln25_13_fu_794_p2 <= std_logic_vector(signed(sext_ln27_17_fu_785_p1) + signed(sext_ln27_15_fu_779_p1));
    add_ln25_14_fu_698_p2 <= std_logic_vector(signed(sext_ln26_1_fu_643_p1) + signed(sext_ln25_6_fu_695_p1));
    add_ln25_15_fu_951_p2 <= std_logic_vector(signed(sext_ln25_9_fu_948_p1) + signed(sext_ln25_8_fu_945_p1));
    add_ln25_16_fu_848_p2 <= std_logic_vector(signed(sext_ln27_21_fu_832_p1) + signed(sext_ln27_23_fu_835_p1));
    add_ln25_17_fu_1068_p2 <= std_logic_vector(signed(sext_ln25_12_fu_1065_p1) + signed(sext_ln27_22_fu_1059_p1));
    add_ln25_18_fu_975_p2 <= std_logic_vector(signed(sext_ln26_2_fu_957_p1) + signed(sext_ln25_11_fu_972_p1));
    add_ln25_19_fu_1077_p2 <= std_logic_vector(signed(sext_ln25_13_fu_1074_p1) + signed(sext_ln27_24_fu_1062_p1));
    add_ln25_20_fu_1015_p2 <= std_logic_vector(signed(sext_ln27_28_fu_1000_p1) + signed(sext_ln27_30_fu_1009_p1));
    add_ln25_21_fu_1092_p2 <= std_logic_vector(signed(sext_ln25_16_fu_1089_p1) + signed(sext_ln27_29_fu_1083_p1));
    add_ln25_22_fu_1021_p2 <= std_logic_vector(signed(sext_ln26_3_fu_981_p1) + signed(sext_ln25_15_fu_1012_p1));
    add_ln25_23_fu_1101_p2 <= std_logic_vector(signed(sext_ln25_17_fu_1098_p1) + signed(sext_ln27_31_fu_1086_p1));
    add_ln25_2_fu_1110_p2 <= std_logic_vector(signed(sext_ln25_5_fu_1107_p1) + signed(add_ln25_3_reg_1534));
    add_ln25_3_fu_1036_p2 <= std_logic_vector(signed(sext_ln25_3_fu_1033_p1) + signed(sext_ln27_4_fu_1027_p1));
    add_ln25_4_fu_1054_p2 <= std_logic_vector(signed(sext_ln25_10_fu_1051_p1) + signed(add_ln25_12_reg_1494));
    add_ln25_5_fu_436_p2 <= std_logic_vector(unsigned(or_ln8_fu_422_p3) + unsigned(ap_const_lv7_2));
    add_ln25_6_fu_928_p2 <= std_logic_vector(signed(sext_ln27_8_fu_925_p1) + signed(sext_ln25_1_reg_1348_pp0_iter5_reg));
    add_ln25_7_fu_1118_p2 <= std_logic_vector(signed(sext_ln25_14_fu_1115_p1) + signed(add_ln25_17_reg_1549));
    add_ln25_8_fu_452_p2 <= std_logic_vector(unsigned(x_reg_376) + unsigned(ap_const_lv7_5));
    add_ln25_9_fu_1045_p2 <= std_logic_vector(signed(sext_ln25_4_fu_1042_p1) + signed(sext_ln27_9_fu_1030_p1));
    add_ln25_fu_758_p2 <= std_logic_vector(signed(sext_ln27_5_fu_752_p1) + signed(sext_ln27_7_fu_755_p1));
    add_ln27_10_fu_897_p2 <= std_logic_vector(signed(sext_ln27_26_fu_894_p1) + signed(sext_ln27_17_fu_785_p1));
    add_ln27_11_fu_1003_p2 <= std_logic_vector(signed(sext_ln27_27_fu_997_p1) + signed(sext_ln27_25_fu_994_p1));
    add_ln27_3_fu_746_p2 <= std_logic_vector(signed(sext_ln27_3_fu_743_p1) + signed(sext_ln27_fu_740_p1));
    add_ln27_4_fu_919_p2 <= std_logic_vector(signed(sext_ln27_2_fu_916_p1) + signed(sext_ln27_1_fu_913_p1));
    add_ln27_5_fu_689_p2 <= std_logic_vector(signed(sext_ln27_10_fu_686_p1) + signed(sext_ln25_2_fu_640_p1));
    add_ln27_6_fu_773_p2 <= std_logic_vector(signed(sext_ln27_12_fu_767_p1) + signed(sext_ln27_11_fu_764_p1));
    add_ln27_7_fu_714_p2 <= std_logic_vector(signed(sext_ln26_fu_598_p1) + signed(sext_ln25_1_fu_637_p1));
    add_ln27_8_fu_826_p2 <= std_logic_vector(signed(sext_ln27_19_fu_823_p1) + signed(sext_ln27_6_fu_800_p1));
    add_ln27_9_fu_966_p2 <= std_logic_vector(signed(sext_ln27_20_fu_963_p1) + signed(sext_ln27_18_fu_960_p1));
    add_ln27_fu_631_p2 <= std_logic_vector(signed(sext_ln25_fu_595_p1) + signed(sext_ln26_fu_598_p1));
    add_ln8_fu_468_p2 <= std_logic_vector(unsigned(x_reg_376) + unsigned(ap_const_lv7_4));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state15 <= ap_CS_fsm(4);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_ST_fsm_state15_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_condition_pp0_flush_enable_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln8_fu_430_p2, ap_block_pp0_stage0_subdone)
    begin
        if (((icmp_ln8_fu_430_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_pp0_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp0_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= y_read_reg_1131;
    icmp_ln6_fu_397_p2 <= "1" when (tmp_reg_1135 = ap_const_lv7_0) else "0";
    icmp_ln8_fu_430_p2 <= "1" when (unsigned(or_ln8_fu_422_p3) < unsigned(ap_const_lv7_56)) else "0";
    img_ga_0_address0 <= zext_ln8_reg_1144_pp0_iter8_reg(5 - 1 downto 0);
    img_ga_0_ce0 <= img_ga_0_ce0_local;

    img_ga_0_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if ((((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_ga_0_ce0_local <= ap_const_logic_1;
        else 
            img_ga_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_ga_0_d0 <= add_ln25_2_reg_1569;
    img_ga_0_we0 <= img_ga_0_we0_local;

    img_ga_0_we0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            img_ga_0_we0_local <= ap_const_logic_1;
        else 
            img_ga_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_ga_1_address0 <= zext_ln8_reg_1144_pp0_iter7_reg(5 - 1 downto 0);
    img_ga_1_ce0 <= img_ga_1_ce0_local;

    img_ga_1_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if ((((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_ga_1_ce0_local <= ap_const_logic_1;
        else 
            img_ga_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_ga_1_d0 <= add_ln25_4_reg_1544;
    img_ga_1_we0 <= img_ga_1_we0_local;

    img_ga_1_we0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            img_ga_1_we0_local <= ap_const_logic_1;
        else 
            img_ga_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_ga_2_address0 <= zext_ln8_reg_1144_pp0_iter8_reg(5 - 1 downto 0);
    img_ga_2_ce0 <= img_ga_2_ce0_local;

    img_ga_2_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if ((((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_ga_2_ce0_local <= ap_const_logic_1;
        else 
            img_ga_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_ga_2_d0 <= add_ln25_7_reg_1579;
    img_ga_2_we0 <= img_ga_2_we0_local;

    img_ga_2_we0_local_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln8_reg_1188_pp0_iter8_reg, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (icmp_ln8_reg_1188_pp0_iter8_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            img_ga_2_we0_local <= ap_const_logic_1;
        else 
            img_ga_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_ga_3_address0 <= zext_ln8_reg_1144_pp0_iter8_reg(5 - 1 downto 0);
    img_ga_3_ce0 <= img_ga_3_ce0_local;

    img_ga_3_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if ((((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_ga_3_ce0_local <= ap_const_logic_1;
        else 
            img_ga_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_ga_3_d0 <= add_ln25_10_reg_1584;
    img_ga_3_we0 <= img_ga_3_we0_local;

    img_ga_3_we0_local_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln8_reg_1188_pp0_iter8_reg, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (icmp_ln8_reg_1188_pp0_iter8_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            img_ga_3_we0_local <= ap_const_logic_1;
        else 
            img_ga_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in0_0_address0 <= zext_ln25_fu_474_p1(5 - 1 downto 0);
    img_in0_0_address1 <= zext_ln8_fu_412_p1(5 - 1 downto 0);
    img_in0_0_ce0 <= img_in0_0_ce0_local;

    img_in0_0_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in0_0_ce0_local <= ap_const_logic_1;
        else 
            img_in0_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in0_0_ce1 <= img_in0_0_ce1_local;

    img_in0_0_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in0_0_ce1_local <= ap_const_logic_1;
        else 
            img_in0_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in0_1_address0 <= zext_ln25_1_fu_480_p1(5 - 1 downto 0);
    img_in0_1_address1 <= zext_ln8_fu_412_p1(5 - 1 downto 0);
    img_in0_1_ce0 <= img_in0_1_ce0_local;

    img_in0_1_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in0_1_ce0_local <= ap_const_logic_1;
        else 
            img_in0_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in0_1_ce1 <= img_in0_1_ce1_local;

    img_in0_1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in0_1_ce1_local <= ap_const_logic_1;
        else 
            img_in0_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in0_2_address0 <= zext_ln8_fu_412_p1(5 - 1 downto 0);
    img_in0_2_ce0 <= img_in0_2_ce0_local;

    img_in0_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in0_2_ce0_local <= ap_const_logic_1;
        else 
            img_in0_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in0_3_address0 <= zext_ln8_fu_412_p1(5 - 1 downto 0);
    img_in0_3_ce0 <= img_in0_3_ce0_local;

    img_in0_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in0_3_ce0_local <= ap_const_logic_1;
        else 
            img_in0_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in1_0_address0 <= zext_ln25_fu_474_p1(5 - 1 downto 0);
    img_in1_0_address1 <= zext_ln8_reg_1144_pp0_iter1_reg(5 - 1 downto 0);
    img_in1_0_ce0 <= img_in1_0_ce0_local;

    img_in1_0_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in1_0_ce0_local <= ap_const_logic_1;
        else 
            img_in1_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in1_0_ce1 <= img_in1_0_ce1_local;

    img_in1_0_ce1_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in1_0_ce1_local <= ap_const_logic_1;
        else 
            img_in1_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in1_1_address0 <= zext_ln25_1_reg_1252(5 - 1 downto 0);
    img_in1_1_address1 <= zext_ln8_reg_1144(5 - 1 downto 0);
    img_in1_1_ce0 <= img_in1_1_ce0_local;

    img_in1_1_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if ((((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in1_1_ce0_local <= ap_const_logic_1;
        else 
            img_in1_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in1_1_ce1 <= img_in1_1_ce1_local;

    img_in1_1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in1_1_ce1_local <= ap_const_logic_1;
        else 
            img_in1_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in1_2_address0 <= zext_ln8_reg_1144(5 - 1 downto 0);
    img_in1_2_ce0 <= img_in1_2_ce0_local;

    img_in1_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in1_2_ce0_local <= ap_const_logic_1;
        else 
            img_in1_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in1_3_address0 <= zext_ln8_reg_1144(5 - 1 downto 0);
    img_in1_3_ce0 <= img_in1_3_ce0_local;

    img_in1_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in1_3_ce0_local <= ap_const_logic_1;
        else 
            img_in1_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in2_0_address0 <= zext_ln25_fu_474_p1(5 - 1 downto 0);
    img_in2_0_address1 <= zext_ln8_reg_1144_pp0_iter1_reg(5 - 1 downto 0);
    img_in2_0_ce0 <= img_in2_0_ce0_local;

    img_in2_0_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in2_0_ce0_local <= ap_const_logic_1;
        else 
            img_in2_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in2_0_ce1 <= img_in2_0_ce1_local;

    img_in2_0_ce1_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in2_0_ce1_local <= ap_const_logic_1;
        else 
            img_in2_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in2_1_address0 <= zext_ln25_1_fu_480_p1(5 - 1 downto 0);
    img_in2_1_address1 <= zext_ln8_reg_1144(5 - 1 downto 0);
    img_in2_1_ce0 <= img_in2_1_ce0_local;

    img_in2_1_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in2_1_ce0_local <= ap_const_logic_1;
        else 
            img_in2_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in2_1_ce1 <= img_in2_1_ce1_local;

    img_in2_1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in2_1_ce1_local <= ap_const_logic_1;
        else 
            img_in2_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in2_2_address0 <= zext_ln8_fu_412_p1(5 - 1 downto 0);
    img_in2_2_ce0 <= img_in2_2_ce0_local;

    img_in2_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in2_2_ce0_local <= ap_const_logic_1;
        else 
            img_in2_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    img_in2_3_address0 <= zext_ln8_fu_412_p1(5 - 1 downto 0);
    img_in2_3_ce0 <= img_in2_3_ce0_local;

    img_in2_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            img_in2_3_ce0_local <= ap_const_logic_1;
        else 
            img_in2_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln8_fu_402_p4 <= x_reg_376(6 downto 2);
    or_ln8_fu_422_p3 <= (lshr_ln8_fu_402_p4 & ap_const_lv2_2);
        sext_ln25_10_fu_1051_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_15_reg_1499),8));

        sext_ln25_11_fu_972_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln27_7_reg_1444),5));

        sext_ln25_12_fu_1065_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_16_reg_1449_pp0_iter6_reg),8));

        sext_ln25_13_fu_1074_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_18_reg_1509),6));

        sext_ln25_14_fu_1115_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_19_reg_1554),8));

        sext_ln25_15_fu_1012_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln27_9_reg_1479),5));

        sext_ln25_16_fu_1089_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_20_reg_1524),8));

        sext_ln25_17_fu_1098_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_22_reg_1529),6));

        sext_ln25_18_fu_1123_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_23_reg_1564),8));

        sext_ln25_1_fu_637_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln27_2_reg_1282),5));

        sext_ln25_2_fu_640_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln25_3_reg_1287),6));

        sext_ln25_3_fu_1033_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_reg_1409_pp0_iter6_reg),8));

        sext_ln25_4_fu_1042_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_6_reg_1489),6));

        sext_ln25_5_fu_1107_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_9_reg_1539),8));

        sext_ln25_6_fu_695_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln27_5_reg_1307),5));

        sext_ln25_7_fu_936_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_11_reg_1419),8));

        sext_ln25_8_fu_945_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_13_reg_1424),7));

        sext_ln25_9_fu_948_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_14_reg_1378_pp0_iter5_reg),7));

        sext_ln25_fu_595_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_1267),5));

        sext_ln26_1_fu_643_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln25_5_reg_1297),5));

        sext_ln26_2_fu_957_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln25_7_reg_1429),5));

        sext_ln26_3_fu_981_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln25_9_reg_1459),5));

        sext_ln26_fu_598_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln25_2_reg_1277),5));

        sext_ln27_10_fu_686_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln25_4_reg_1292),6));

        sext_ln27_11_fu_764_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln26_3_reg_1353),7));

        sext_ln27_12_fu_767_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln27_5_reg_1373),7));

        sext_ln27_13_fu_770_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln26_4_reg_1358),7));

        sext_ln27_14_fu_933_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln27_6_reg_1414),8));

        sext_ln27_15_fu_779_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln27_3_reg_1368),6));

        sext_ln27_16_fu_782_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln27_4_reg_1302_pp0_iter4_reg),7));

        sext_ln27_17_fu_785_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln26_5_reg_1363),6));

        sext_ln27_18_fu_960_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln25_6_reg_1312_pp0_iter5_reg),7));

        sext_ln27_19_fu_823_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln27_7_reg_1389),6));

        sext_ln27_1_fu_913_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln14_reg_1394),7));

        sext_ln27_20_fu_963_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln27_8_reg_1439),7));

        sext_ln27_21_fu_832_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln26_6_reg_1384),7));

        sext_ln27_22_fu_1059_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln27_9_reg_1504),8));

        sext_ln27_23_fu_835_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln27_6_reg_1317_pp0_iter4_reg),7));

        sext_ln27_24_fu_1062_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln26_7_reg_1434_pp0_iter6_reg),6));

        sext_ln27_25_fu_994_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln25_8_reg_1454),7));

        sext_ln27_26_fu_894_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_14_reg_1378),6));

        sext_ln27_27_fu_997_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln27_10_reg_1474),7));

        sext_ln27_28_fu_1000_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln26_8_reg_1464),7));

        sext_ln27_29_fu_1083_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln27_11_reg_1519),8));

        sext_ln27_2_fu_916_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln27_3_reg_1404),7));

        sext_ln27_30_fu_1009_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln27_8_reg_1469),7));

        sext_ln27_31_fu_1086_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln26_9_reg_1514),6));

        sext_ln27_3_fu_743_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln27_reg_1343),6));

        sext_ln27_4_fu_1027_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln27_4_reg_1484),8));

        sext_ln27_5_fu_752_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln26_1_reg_1327),7));

        sext_ln27_6_fu_800_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln26_2_reg_1332),6));

        sext_ln27_7_fu_755_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln26_2_reg_1332),7));

        sext_ln27_8_fu_925_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln15_reg_1399),5));

        sext_ln27_9_fu_1030_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln27_1_reg_1338_pp0_iter6_reg),6));

        sext_ln27_fu_740_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln25_1_reg_1272_pp0_iter4_reg),6));

    zext_ln25_1_fu_480_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln25_s_reg_1197_pp0_iter1_reg),64));
    zext_ln25_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln25_7_reg_1192_pp0_iter1_reg),64));
    zext_ln8_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln8_fu_402_p4),64));
end behav;
