// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_module_line_buff2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        y,
        img_ga_0_address0,
        img_ga_0_ce0,
        img_ga_0_q0,
        img_ga_1_address0,
        img_ga_1_ce0,
        img_ga_1_q0,
        img_ga0_0_address0,
        img_ga0_0_ce0,
        img_ga0_0_we0,
        img_ga0_0_d0,
        img_ga0_1_address0,
        img_ga0_1_ce0,
        img_ga0_1_we0,
        img_ga0_1_d0,
        img_ga1_0_address0,
        img_ga1_0_ce0,
        img_ga1_0_we0,
        img_ga1_0_d0,
        img_ga1_1_address0,
        img_ga1_1_ce0,
        img_ga1_1_we0,
        img_ga1_1_d0,
        img_ga2_0_address0,
        img_ga2_0_ce0,
        img_ga2_0_we0,
        img_ga2_0_d0,
        img_ga2_1_address0,
        img_ga2_1_ce0,
        img_ga2_1_we0,
        img_ga2_1_d0,
        img_ga_2_address0,
        img_ga_2_ce0,
        img_ga_2_q0,
        img_ga_3_address0,
        img_ga_3_ce0,
        img_ga_3_q0,
        img_ga0_2_address0,
        img_ga0_2_ce0,
        img_ga0_2_we0,
        img_ga0_2_d0,
        img_ga0_3_address0,
        img_ga0_3_ce0,
        img_ga0_3_we0,
        img_ga0_3_d0,
        img_ga1_2_address0,
        img_ga1_2_ce0,
        img_ga1_2_we0,
        img_ga1_2_d0,
        img_ga1_3_address0,
        img_ga1_3_ce0,
        img_ga1_3_we0,
        img_ga1_3_d0,
        img_ga2_2_address0,
        img_ga2_2_ce0,
        img_ga2_2_we0,
        img_ga2_2_d0,
        img_ga2_3_address0,
        img_ga2_3_ce0,
        img_ga2_3_we0,
        img_ga2_3_d0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_pp0_stage0 = 9'd8;
parameter    ap_ST_fsm_state10 = 9'd16;
parameter    ap_ST_fsm_pp1_stage0 = 9'd32;
parameter    ap_ST_fsm_pp2_stage0 = 9'd64;
parameter    ap_ST_fsm_state23 = 9'd128;
parameter    ap_ST_fsm_pp3_stage0 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] y;
output  [4:0] img_ga_0_address0;
output   img_ga_0_ce0;
input  [7:0] img_ga_0_q0;
output  [4:0] img_ga_1_address0;
output   img_ga_1_ce0;
input  [7:0] img_ga_1_q0;
output  [4:0] img_ga0_0_address0;
output   img_ga0_0_ce0;
output   img_ga0_0_we0;
output  [7:0] img_ga0_0_d0;
output  [4:0] img_ga0_1_address0;
output   img_ga0_1_ce0;
output   img_ga0_1_we0;
output  [7:0] img_ga0_1_d0;
output  [4:0] img_ga1_0_address0;
output   img_ga1_0_ce0;
output   img_ga1_0_we0;
output  [7:0] img_ga1_0_d0;
output  [4:0] img_ga1_1_address0;
output   img_ga1_1_ce0;
output   img_ga1_1_we0;
output  [7:0] img_ga1_1_d0;
output  [4:0] img_ga2_0_address0;
output   img_ga2_0_ce0;
output   img_ga2_0_we0;
output  [7:0] img_ga2_0_d0;
output  [4:0] img_ga2_1_address0;
output   img_ga2_1_ce0;
output   img_ga2_1_we0;
output  [7:0] img_ga2_1_d0;
output  [4:0] img_ga_2_address0;
output   img_ga_2_ce0;
input  [7:0] img_ga_2_q0;
output  [4:0] img_ga_3_address0;
output   img_ga_3_ce0;
input  [7:0] img_ga_3_q0;
output  [4:0] img_ga0_2_address0;
output   img_ga0_2_ce0;
output   img_ga0_2_we0;
output  [7:0] img_ga0_2_d0;
output  [4:0] img_ga0_3_address0;
output   img_ga0_3_ce0;
output   img_ga0_3_we0;
output  [7:0] img_ga0_3_d0;
output  [4:0] img_ga1_2_address0;
output   img_ga1_2_ce0;
output   img_ga1_2_we0;
output  [7:0] img_ga1_2_d0;
output  [4:0] img_ga1_3_address0;
output   img_ga1_3_ce0;
output   img_ga1_3_we0;
output  [7:0] img_ga1_3_d0;
output  [4:0] img_ga2_2_address0;
output   img_ga2_2_ce0;
output   img_ga2_2_we0;
output  [7:0] img_ga2_2_d0;
output  [4:0] img_ga2_3_address0;
output   img_ga2_3_ce0;
output   img_ga2_3_we0;
output  [7:0] img_ga2_3_d0;
output  [7:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] img_ga1bf_0_address1;
wire   [7:0] img_ga1bf_0_q1;
wire   [4:0] img_ga1bf_1_address1;
wire   [7:0] img_ga1bf_1_q1;
wire   [4:0] img_ga2bf_0_address1;
wire   [7:0] img_ga2bf_0_q1;
wire   [4:0] img_ga2bf_1_address1;
wire   [7:0] img_ga2bf_1_q1;
wire   [4:0] img_ga1bf_2_address1;
wire   [7:0] img_ga1bf_2_q1;
wire   [4:0] img_ga1bf_3_address1;
wire   [7:0] img_ga1bf_3_q1;
wire   [4:0] img_ga2bf_2_address1;
wire   [7:0] img_ga2bf_2_q1;
wire   [4:0] img_ga2bf_3_address1;
wire   [7:0] img_ga2bf_3_q1;
reg   [6:0] x_6_reg_706;
reg   [6:0] x_5_reg_717;
reg   [6:0] x_reg_728;
reg   [6:0] x_7_reg_739;
reg   [7:0] reg_750;
reg    ap_enable_reg_pp0_iter3;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp1_stage0_11001;
wire    ap_block_pp2_stage0_11001;
wire    ap_block_pp3_stage0_11001;
reg    ap_enable_reg_pp1_iter3;
reg    ap_enable_reg_pp2_iter3;
reg    ap_enable_reg_pp3_iter3;
reg   [7:0] reg_759;
reg   [7:0] reg_768;
reg   [7:0] reg_777;
reg   [7:0] y_read_reg_951;
reg    ap_block_state1;
wire   [0:0] icmp_ln31_fu_786_p2;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln23_fu_801_p1;
reg   [63:0] zext_ln23_reg_960;
wire    ap_CS_fsm_pp0_stage0;
reg   [63:0] zext_ln23_reg_960_pp0_iter1_reg;
reg   [63:0] zext_ln23_reg_960_pp0_iter2_reg;
reg   [63:0] zext_ln23_reg_960_pp0_iter3_reg;
wire   [0:0] icmp_ln23_fu_817_p2;
reg   [0:0] icmp_ln23_reg_982;
reg   [0:0] icmp_ln23_reg_982_pp0_iter1_reg;
reg   [0:0] icmp_ln23_reg_982_pp0_iter2_reg;
reg   [0:0] icmp_ln23_reg_982_pp0_iter3_reg;
wire   [6:0] add_ln23_fu_823_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [63:0] zext_ln14_fu_839_p1;
reg   [63:0] zext_ln14_reg_1041;
wire    ap_CS_fsm_pp1_stage0;
reg   [63:0] zext_ln14_reg_1041_pp1_iter1_reg;
reg   [63:0] zext_ln14_reg_1041_pp1_iter2_reg;
reg   [63:0] zext_ln14_reg_1041_pp1_iter3_reg;
wire   [0:0] icmp_ln14_fu_855_p2;
reg   [0:0] icmp_ln14_reg_1063;
reg   [0:0] icmp_ln14_reg_1063_pp1_iter1_reg;
reg   [0:0] icmp_ln14_reg_1063_pp1_iter2_reg;
reg   [0:0] icmp_ln14_reg_1063_pp1_iter3_reg;
wire   [6:0] add_ln14_fu_861_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [63:0] zext_ln7_fu_877_p1;
reg   [63:0] zext_ln7_reg_1122;
wire    ap_CS_fsm_pp2_stage0;
reg   [63:0] zext_ln7_reg_1122_pp2_iter1_reg;
reg   [63:0] zext_ln7_reg_1122_pp2_iter2_reg;
reg   [63:0] zext_ln7_reg_1122_pp2_iter3_reg;
wire   [0:0] icmp_ln7_fu_893_p2;
reg   [0:0] icmp_ln7_reg_1140;
reg   [0:0] icmp_ln7_reg_1140_pp2_iter1_reg;
reg   [0:0] icmp_ln7_reg_1140_pp2_iter2_reg;
reg   [0:0] icmp_ln7_reg_1140_pp2_iter3_reg;
wire   [6:0] add_ln7_fu_899_p2;
reg    ap_enable_reg_pp2_iter0;
wire   [63:0] zext_ln32_fu_915_p1;
reg   [63:0] zext_ln32_reg_1179;
wire    ap_CS_fsm_pp3_stage0;
reg   [63:0] zext_ln32_reg_1179_pp3_iter1_reg;
reg   [63:0] zext_ln32_reg_1179_pp3_iter2_reg;
reg   [63:0] zext_ln32_reg_1179_pp3_iter3_reg;
reg   [4:0] img_ga1bf_0_addr_1_reg_1195;
reg   [4:0] img_ga1bf_0_addr_1_reg_1195_pp3_iter1_reg;
reg   [4:0] img_ga1bf_0_addr_1_reg_1195_pp3_iter2_reg;
reg   [4:0] img_ga1bf_0_addr_1_reg_1195_pp3_iter3_reg;
reg   [4:0] img_ga2bf_0_addr_1_reg_1201;
reg   [4:0] img_ga2bf_0_addr_1_reg_1201_pp3_iter1_reg;
reg   [4:0] img_ga2bf_0_addr_1_reg_1201_pp3_iter2_reg;
reg   [4:0] img_ga2bf_0_addr_1_reg_1201_pp3_iter3_reg;
reg   [4:0] img_ga1bf_1_addr_1_reg_1212;
reg   [4:0] img_ga1bf_1_addr_1_reg_1212_pp3_iter1_reg;
reg   [4:0] img_ga1bf_1_addr_1_reg_1212_pp3_iter2_reg;
reg   [4:0] img_ga1bf_1_addr_1_reg_1212_pp3_iter3_reg;
reg   [4:0] img_ga2bf_1_addr_1_reg_1218;
reg   [4:0] img_ga2bf_1_addr_1_reg_1218_pp3_iter1_reg;
reg   [4:0] img_ga2bf_1_addr_1_reg_1218_pp3_iter2_reg;
reg   [4:0] img_ga2bf_1_addr_1_reg_1218_pp3_iter3_reg;
wire   [0:0] icmp_ln32_fu_939_p2;
reg   [0:0] icmp_ln32_reg_1229;
reg   [0:0] icmp_ln32_reg_1229_pp3_iter1_reg;
reg   [0:0] icmp_ln32_reg_1229_pp3_iter2_reg;
reg   [0:0] icmp_ln32_reg_1229_pp3_iter3_reg;
reg   [4:0] img_ga1bf_2_addr_1_reg_1233;
reg   [4:0] img_ga1bf_2_addr_1_reg_1233_pp3_iter1_reg;
reg   [4:0] img_ga1bf_2_addr_1_reg_1233_pp3_iter2_reg;
reg   [4:0] img_ga1bf_2_addr_1_reg_1233_pp3_iter3_reg;
reg   [4:0] img_ga2bf_2_addr_1_reg_1239;
reg   [4:0] img_ga2bf_2_addr_1_reg_1239_pp3_iter1_reg;
reg   [4:0] img_ga2bf_2_addr_1_reg_1239_pp3_iter2_reg;
reg   [4:0] img_ga2bf_2_addr_1_reg_1239_pp3_iter3_reg;
reg   [4:0] img_ga1bf_3_addr_1_reg_1250;
reg   [4:0] img_ga1bf_3_addr_1_reg_1250_pp3_iter1_reg;
reg   [4:0] img_ga1bf_3_addr_1_reg_1250_pp3_iter2_reg;
reg   [4:0] img_ga1bf_3_addr_1_reg_1250_pp3_iter3_reg;
reg   [4:0] img_ga2bf_3_addr_1_reg_1256;
reg   [4:0] img_ga2bf_3_addr_1_reg_1256_pp3_iter1_reg;
reg   [4:0] img_ga2bf_3_addr_1_reg_1256_pp3_iter2_reg;
reg   [4:0] img_ga2bf_3_addr_1_reg_1256_pp3_iter3_reg;
wire   [6:0] add_ln32_fu_945_p2;
reg    ap_enable_reg_pp3_iter0;
reg   [7:0] val_1_8_reg_1272;
reg   [7:0] val_2_reg_1277;
reg   [7:0] img_ga1bf_1_load_reg_1283;
reg   [7:0] img_ga2bf_1_load_reg_1288;
reg   [7:0] val_1_9_reg_1294;
reg   [7:0] val_2_1_reg_1299;
reg   [7:0] img_ga1bf_3_load_reg_1305;
reg   [7:0] img_ga2bf_3_load_reg_1310;
wire    ap_CS_fsm_state3;
reg    ap_predicate_pred647_state3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_predicate_pred675_state3;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_flush_enable;
reg    ap_enable_reg_pp1_iter1;
reg    ap_enable_reg_pp1_iter2;
reg    ap_enable_reg_pp1_iter4;
reg    ap_enable_reg_pp1_iter5;
reg    ap_predicate_pred702_state3;
wire    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_flush_enable;
reg    ap_enable_reg_pp2_iter1;
reg    ap_enable_reg_pp2_iter2;
reg    ap_enable_reg_pp2_iter4;
reg    ap_enable_reg_pp2_iter5;
wire    ap_CS_fsm_state23;
wire    ap_block_pp3_stage0_subdone;
reg    ap_condition_pp3_flush_enable;
reg    ap_enable_reg_pp3_iter1;
reg    ap_enable_reg_pp3_iter2;
reg    ap_enable_reg_pp3_iter4;
reg    ap_enable_reg_pp3_iter5;
wire    ap_block_pp0_stage0;
wire    ap_block_pp1_stage0;
wire    ap_block_pp2_stage0;
wire    ap_block_pp3_stage0;
reg    img_ga_0_ce0_local;
reg   [4:0] img_ga_0_address0_local;
reg    img_ga_1_ce0_local;
reg   [4:0] img_ga_1_address0_local;
reg    img_ga_2_ce0_local;
reg   [4:0] img_ga_2_address0_local;
reg    img_ga_3_ce0_local;
reg   [4:0] img_ga_3_address0_local;
reg    img_ga2_0_we0_local;
reg    img_ga2_0_ce0_local;
reg   [4:0] img_ga2_0_address0_local;
reg    img_ga2_1_we0_local;
reg    img_ga2_1_ce0_local;
reg   [4:0] img_ga2_1_address0_local;
reg    img_ga2bf_0_we0_local;
reg    img_ga2bf_0_ce0_local;
reg   [4:0] img_ga2bf_0_address0_local;
reg    img_ga2bf_0_ce1_local;
reg    img_ga2bf_1_we0_local;
reg    img_ga2bf_1_ce0_local;
reg   [4:0] img_ga2bf_1_address0_local;
reg    img_ga2bf_1_ce1_local;
reg    img_ga2_2_we0_local;
reg    img_ga2_2_ce0_local;
reg   [4:0] img_ga2_2_address0_local;
reg    img_ga2_3_we0_local;
reg    img_ga2_3_ce0_local;
reg   [4:0] img_ga2_3_address0_local;
reg    img_ga2bf_2_we0_local;
reg    img_ga2bf_2_ce0_local;
reg   [4:0] img_ga2bf_2_address0_local;
reg    img_ga2bf_2_ce1_local;
reg    img_ga2bf_3_we0_local;
reg    img_ga2bf_3_ce0_local;
reg   [4:0] img_ga2bf_3_address0_local;
reg    img_ga2bf_3_ce1_local;
reg    img_ga1_0_we0_local;
reg   [7:0] img_ga1_0_d0_local;
reg    img_ga1_0_ce0_local;
reg   [4:0] img_ga1_0_address0_local;
reg    img_ga1_1_we0_local;
reg   [7:0] img_ga1_1_d0_local;
reg    img_ga1_1_ce0_local;
reg   [4:0] img_ga1_1_address0_local;
reg    img_ga1bf_0_we0_local;
reg   [7:0] img_ga1bf_0_d0_local;
reg    img_ga1bf_0_ce0_local;
reg   [4:0] img_ga1bf_0_address0_local;
reg    img_ga1bf_0_ce1_local;
reg    img_ga1bf_1_we0_local;
reg   [7:0] img_ga1bf_1_d0_local;
reg    img_ga1bf_1_ce0_local;
reg   [4:0] img_ga1bf_1_address0_local;
reg    img_ga1bf_1_ce1_local;
reg    img_ga1_2_we0_local;
reg   [7:0] img_ga1_2_d0_local;
reg    img_ga1_2_ce0_local;
reg   [4:0] img_ga1_2_address0_local;
reg    img_ga1_3_we0_local;
reg   [7:0] img_ga1_3_d0_local;
reg    img_ga1_3_ce0_local;
reg   [4:0] img_ga1_3_address0_local;
reg    img_ga1bf_2_we0_local;
reg   [7:0] img_ga1bf_2_d0_local;
reg    img_ga1bf_2_ce0_local;
reg   [4:0] img_ga1bf_2_address0_local;
reg    img_ga1bf_2_ce1_local;
reg    img_ga1bf_3_we0_local;
reg   [7:0] img_ga1bf_3_d0_local;
reg    img_ga1bf_3_ce0_local;
reg   [4:0] img_ga1bf_3_address0_local;
reg    img_ga1bf_3_ce1_local;
reg    img_ga0_0_we0_local;
reg   [7:0] img_ga0_0_d0_local;
reg    img_ga0_0_ce0_local;
reg   [4:0] img_ga0_0_address0_local;
reg    img_ga0_1_we0_local;
reg   [7:0] img_ga0_1_d0_local;
reg    img_ga0_1_ce0_local;
reg   [4:0] img_ga0_1_address0_local;
reg    img_ga0_2_we0_local;
reg   [7:0] img_ga0_2_d0_local;
reg    img_ga0_2_ce0_local;
reg   [4:0] img_ga0_2_address0_local;
reg    img_ga0_3_we0_local;
reg   [7:0] img_ga0_3_d0_local;
reg    img_ga0_3_ce0_local;
reg   [4:0] img_ga0_3_address0_local;
wire   [4:0] lshr_ln_fu_791_p4;
wire   [6:0] or_ln1_fu_809_p3;
wire   [4:0] lshr_ln14_fu_829_p4;
wire   [6:0] or_ln_fu_847_p3;
wire   [4:0] lshr_ln7_fu_867_p4;
wire   [6:0] or_ln7_fu_885_p3;
wire   [4:0] lshr_ln15_fu_905_p4;
wire   [6:0] or_ln2_fu_931_p3;
wire    ap_CS_fsm_state10;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state23_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_idle_pp3;
wire    ap_enable_pp3;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp2_iter3 = 1'b0;
#0 ap_enable_reg_pp3_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter4 = 1'b0;
#0 ap_enable_reg_pp2_iter5 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter2 = 1'b0;
#0 ap_enable_reg_pp3_iter4 = 1'b0;
#0 ap_enable_reg_pp3_iter5 = 1'b0;
end

top_module_line_buff2_img_ga1bf_0_RAM_AUTO_3R2W #(
    .DataWidth( 8 ),
    .AddressRange( 22 ),
    .AddressWidth( 5 ))
img_ga1bf_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(img_ga1bf_0_address0_local),
    .ce0(img_ga1bf_0_ce0_local),
    .we0(img_ga1bf_0_we0_local),
    .d0(img_ga1bf_0_d0_local),
    .address1(img_ga1bf_0_address1),
    .ce1(img_ga1bf_0_ce1_local),
    .q1(img_ga1bf_0_q1)
);

top_module_line_buff2_img_ga1bf_0_RAM_AUTO_3R2W #(
    .DataWidth( 8 ),
    .AddressRange( 22 ),
    .AddressWidth( 5 ))
img_ga1bf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(img_ga1bf_1_address0_local),
    .ce0(img_ga1bf_1_ce0_local),
    .we0(img_ga1bf_1_we0_local),
    .d0(img_ga1bf_1_d0_local),
    .address1(img_ga1bf_1_address1),
    .ce1(img_ga1bf_1_ce1_local),
    .q1(img_ga1bf_1_q1)
);

top_module_line_buff2_img_ga1bf_0_RAM_AUTO_3R2W #(
    .DataWidth( 8 ),
    .AddressRange( 22 ),
    .AddressWidth( 5 ))
img_ga2bf_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(img_ga2bf_0_address0_local),
    .ce0(img_ga2bf_0_ce0_local),
    .we0(img_ga2bf_0_we0_local),
    .d0(reg_750),
    .address1(img_ga2bf_0_address1),
    .ce1(img_ga2bf_0_ce1_local),
    .q1(img_ga2bf_0_q1)
);

top_module_line_buff2_img_ga1bf_0_RAM_AUTO_3R2W #(
    .DataWidth( 8 ),
    .AddressRange( 22 ),
    .AddressWidth( 5 ))
img_ga2bf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(img_ga2bf_1_address0_local),
    .ce0(img_ga2bf_1_ce0_local),
    .we0(img_ga2bf_1_we0_local),
    .d0(reg_759),
    .address1(img_ga2bf_1_address1),
    .ce1(img_ga2bf_1_ce1_local),
    .q1(img_ga2bf_1_q1)
);

top_module_line_buff2_img_ga1bf_0_RAM_AUTO_3R2W #(
    .DataWidth( 8 ),
    .AddressRange( 22 ),
    .AddressWidth( 5 ))
img_ga1bf_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(img_ga1bf_2_address0_local),
    .ce0(img_ga1bf_2_ce0_local),
    .we0(img_ga1bf_2_we0_local),
    .d0(img_ga1bf_2_d0_local),
    .address1(img_ga1bf_2_address1),
    .ce1(img_ga1bf_2_ce1_local),
    .q1(img_ga1bf_2_q1)
);

top_module_line_buff2_img_ga1bf_0_RAM_AUTO_3R2W #(
    .DataWidth( 8 ),
    .AddressRange( 22 ),
    .AddressWidth( 5 ))
img_ga1bf_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(img_ga1bf_3_address0_local),
    .ce0(img_ga1bf_3_ce0_local),
    .we0(img_ga1bf_3_we0_local),
    .d0(img_ga1bf_3_d0_local),
    .address1(img_ga1bf_3_address1),
    .ce1(img_ga1bf_3_ce1_local),
    .q1(img_ga1bf_3_q1)
);

top_module_line_buff2_img_ga1bf_0_RAM_AUTO_3R2W #(
    .DataWidth( 8 ),
    .AddressRange( 22 ),
    .AddressWidth( 5 ))
img_ga2bf_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(img_ga2bf_2_address0_local),
    .ce0(img_ga2bf_2_ce0_local),
    .we0(img_ga2bf_2_we0_local),
    .d0(reg_768),
    .address1(img_ga2bf_2_address1),
    .ce1(img_ga2bf_2_ce1_local),
    .q1(img_ga2bf_2_q1)
);

top_module_line_buff2_img_ga1bf_0_RAM_AUTO_3R2W #(
    .DataWidth( 8 ),
    .AddressRange( 22 ),
    .AddressWidth( 5 ))
img_ga2bf_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(img_ga2bf_3_address0_local),
    .ce0(img_ga2bf_3_ce0_local),
    .we0(img_ga2bf_3_we0_local),
    .d0(reg_777),
    .address1(img_ga2bf_3_address1),
    .ce1(img_ga2bf_3_ce1_local),
    .q1(img_ga2bf_3_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_predicate_pred647_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if (((ap_predicate_pred647_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp1_flush_enable)) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((ap_predicate_pred675_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end else if (((ap_predicate_pred675_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp1_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp2_flush_enable)) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if (((ap_predicate_pred702_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter3 <= ap_enable_reg_pp2_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter4 <= ap_enable_reg_pp2_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter5 <= ap_enable_reg_pp2_iter4;
        end else if (((ap_predicate_pred702_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp2_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp3_flush_enable)) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state23)) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter2 <= ap_enable_reg_pp3_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter3 <= ap_enable_reg_pp3_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter4 <= ap_enable_reg_pp3_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter5 <= ap_enable_reg_pp3_iter4;
        end else if ((1'b1 == ap_CS_fsm_state23)) begin
            ap_enable_reg_pp3_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred675_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        x_5_reg_717 <= 7'd0;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (icmp_ln14_fu_855_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        x_5_reg_717 <= add_ln14_fu_861_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred647_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        x_6_reg_706 <= 7'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln23_fu_817_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_6_reg_706 <= add_ln23_fu_823_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        x_7_reg_739 <= 7'd0;
    end else if (((ap_enable_reg_pp3_iter0 == 1'b1) & (icmp_ln32_fu_939_p2 == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        x_7_reg_739 <= add_ln32_fu_945_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred702_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        x_reg_728 <= 7'd0;
    end else if (((ap_enable_reg_pp2_iter0 == 1'b1) & (icmp_ln7_fu_893_p2 == 1'd1) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        x_reg_728 <= add_ln7_fu_899_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_predicate_pred647_state3 <= (y_read_reg_951 == 8'd4);
        ap_predicate_pred675_state3 <= (y_read_reg_951 == 8'd3);
        ap_predicate_pred702_state3 <= (y_read_reg_951 == 8'd2);
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln14_reg_1063 <= icmp_ln14_fu_855_p2;
        icmp_ln14_reg_1063_pp1_iter1_reg <= icmp_ln14_reg_1063;
        zext_ln14_reg_1041[4 : 0] <= zext_ln14_fu_839_p1[4 : 0];
        zext_ln14_reg_1041_pp1_iter1_reg[4 : 0] <= zext_ln14_reg_1041[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        icmp_ln14_reg_1063_pp1_iter2_reg <= icmp_ln14_reg_1063_pp1_iter1_reg;
        icmp_ln14_reg_1063_pp1_iter3_reg <= icmp_ln14_reg_1063_pp1_iter2_reg;
        zext_ln14_reg_1041_pp1_iter2_reg[4 : 0] <= zext_ln14_reg_1041_pp1_iter1_reg[4 : 0];
        zext_ln14_reg_1041_pp1_iter3_reg[4 : 0] <= zext_ln14_reg_1041_pp1_iter2_reg[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln23_reg_982 <= icmp_ln23_fu_817_p2;
        icmp_ln23_reg_982_pp0_iter1_reg <= icmp_ln23_reg_982;
        zext_ln23_reg_960[4 : 0] <= zext_ln23_fu_801_p1[4 : 0];
        zext_ln23_reg_960_pp0_iter1_reg[4 : 0] <= zext_ln23_reg_960[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln23_reg_982_pp0_iter2_reg <= icmp_ln23_reg_982_pp0_iter1_reg;
        icmp_ln23_reg_982_pp0_iter3_reg <= icmp_ln23_reg_982_pp0_iter2_reg;
        zext_ln23_reg_960_pp0_iter2_reg[4 : 0] <= zext_ln23_reg_960_pp0_iter1_reg[4 : 0];
        zext_ln23_reg_960_pp0_iter3_reg[4 : 0] <= zext_ln23_reg_960_pp0_iter2_reg[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        icmp_ln32_reg_1229 <= icmp_ln32_fu_939_p2;
        icmp_ln32_reg_1229_pp3_iter1_reg <= icmp_ln32_reg_1229;
        img_ga1bf_0_addr_1_reg_1195 <= zext_ln32_fu_915_p1;
        img_ga1bf_0_addr_1_reg_1195_pp3_iter1_reg <= img_ga1bf_0_addr_1_reg_1195;
        img_ga1bf_1_addr_1_reg_1212 <= zext_ln32_fu_915_p1;
        img_ga1bf_1_addr_1_reg_1212_pp3_iter1_reg <= img_ga1bf_1_addr_1_reg_1212;
        img_ga1bf_2_addr_1_reg_1233 <= zext_ln32_fu_915_p1;
        img_ga1bf_2_addr_1_reg_1233_pp3_iter1_reg <= img_ga1bf_2_addr_1_reg_1233;
        img_ga1bf_3_addr_1_reg_1250 <= zext_ln32_fu_915_p1;
        img_ga1bf_3_addr_1_reg_1250_pp3_iter1_reg <= img_ga1bf_3_addr_1_reg_1250;
        img_ga2bf_0_addr_1_reg_1201 <= zext_ln32_fu_915_p1;
        img_ga2bf_0_addr_1_reg_1201_pp3_iter1_reg <= img_ga2bf_0_addr_1_reg_1201;
        img_ga2bf_1_addr_1_reg_1218 <= zext_ln32_fu_915_p1;
        img_ga2bf_1_addr_1_reg_1218_pp3_iter1_reg <= img_ga2bf_1_addr_1_reg_1218;
        img_ga2bf_2_addr_1_reg_1239 <= zext_ln32_fu_915_p1;
        img_ga2bf_2_addr_1_reg_1239_pp3_iter1_reg <= img_ga2bf_2_addr_1_reg_1239;
        img_ga2bf_3_addr_1_reg_1256 <= zext_ln32_fu_915_p1;
        img_ga2bf_3_addr_1_reg_1256_pp3_iter1_reg <= img_ga2bf_3_addr_1_reg_1256;
        zext_ln32_reg_1179[4 : 0] <= zext_ln32_fu_915_p1[4 : 0];
        zext_ln32_reg_1179_pp3_iter1_reg[4 : 0] <= zext_ln32_reg_1179[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp3_stage0_11001)) begin
        icmp_ln32_reg_1229_pp3_iter2_reg <= icmp_ln32_reg_1229_pp3_iter1_reg;
        icmp_ln32_reg_1229_pp3_iter3_reg <= icmp_ln32_reg_1229_pp3_iter2_reg;
        img_ga1bf_0_addr_1_reg_1195_pp3_iter2_reg <= img_ga1bf_0_addr_1_reg_1195_pp3_iter1_reg;
        img_ga1bf_0_addr_1_reg_1195_pp3_iter3_reg <= img_ga1bf_0_addr_1_reg_1195_pp3_iter2_reg;
        img_ga1bf_1_addr_1_reg_1212_pp3_iter2_reg <= img_ga1bf_1_addr_1_reg_1212_pp3_iter1_reg;
        img_ga1bf_1_addr_1_reg_1212_pp3_iter3_reg <= img_ga1bf_1_addr_1_reg_1212_pp3_iter2_reg;
        img_ga1bf_2_addr_1_reg_1233_pp3_iter2_reg <= img_ga1bf_2_addr_1_reg_1233_pp3_iter1_reg;
        img_ga1bf_2_addr_1_reg_1233_pp3_iter3_reg <= img_ga1bf_2_addr_1_reg_1233_pp3_iter2_reg;
        img_ga1bf_3_addr_1_reg_1250_pp3_iter2_reg <= img_ga1bf_3_addr_1_reg_1250_pp3_iter1_reg;
        img_ga1bf_3_addr_1_reg_1250_pp3_iter3_reg <= img_ga1bf_3_addr_1_reg_1250_pp3_iter2_reg;
        img_ga2bf_0_addr_1_reg_1201_pp3_iter2_reg <= img_ga2bf_0_addr_1_reg_1201_pp3_iter1_reg;
        img_ga2bf_0_addr_1_reg_1201_pp3_iter3_reg <= img_ga2bf_0_addr_1_reg_1201_pp3_iter2_reg;
        img_ga2bf_1_addr_1_reg_1218_pp3_iter2_reg <= img_ga2bf_1_addr_1_reg_1218_pp3_iter1_reg;
        img_ga2bf_1_addr_1_reg_1218_pp3_iter3_reg <= img_ga2bf_1_addr_1_reg_1218_pp3_iter2_reg;
        img_ga2bf_2_addr_1_reg_1239_pp3_iter2_reg <= img_ga2bf_2_addr_1_reg_1239_pp3_iter1_reg;
        img_ga2bf_2_addr_1_reg_1239_pp3_iter3_reg <= img_ga2bf_2_addr_1_reg_1239_pp3_iter2_reg;
        img_ga2bf_3_addr_1_reg_1256_pp3_iter2_reg <= img_ga2bf_3_addr_1_reg_1256_pp3_iter1_reg;
        img_ga2bf_3_addr_1_reg_1256_pp3_iter3_reg <= img_ga2bf_3_addr_1_reg_1256_pp3_iter2_reg;
        zext_ln32_reg_1179_pp3_iter2_reg[4 : 0] <= zext_ln32_reg_1179_pp3_iter1_reg[4 : 0];
        zext_ln32_reg_1179_pp3_iter3_reg[4 : 0] <= zext_ln32_reg_1179_pp3_iter2_reg[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        icmp_ln7_reg_1140 <= icmp_ln7_fu_893_p2;
        icmp_ln7_reg_1140_pp2_iter1_reg <= icmp_ln7_reg_1140;
        zext_ln7_reg_1122[4 : 0] <= zext_ln7_fu_877_p1[4 : 0];
        zext_ln7_reg_1122_pp2_iter1_reg[4 : 0] <= zext_ln7_reg_1122[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp2_stage0_11001)) begin
        icmp_ln7_reg_1140_pp2_iter2_reg <= icmp_ln7_reg_1140_pp2_iter1_reg;
        icmp_ln7_reg_1140_pp2_iter3_reg <= icmp_ln7_reg_1140_pp2_iter2_reg;
        zext_ln7_reg_1122_pp2_iter2_reg[4 : 0] <= zext_ln7_reg_1122_pp2_iter1_reg[4 : 0];
        zext_ln7_reg_1122_pp2_iter3_reg[4 : 0] <= zext_ln7_reg_1122_pp2_iter2_reg[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp3_iter3 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        img_ga1bf_1_load_reg_1283 <= img_ga1bf_1_q1;
        img_ga1bf_3_load_reg_1305 <= img_ga1bf_3_q1;
        img_ga2bf_1_load_reg_1288 <= img_ga2bf_1_q1;
        img_ga2bf_3_load_reg_1310 <= img_ga2bf_3_q1;
        val_1_8_reg_1272 <= img_ga1bf_0_q1;
        val_1_9_reg_1294 <= img_ga1bf_2_q1;
        val_2_1_reg_1299 <= img_ga2bf_2_q1;
        val_2_reg_1277 <= img_ga2bf_0_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp3_iter3 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp2_iter3 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp1_iter3 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        reg_750 <= img_ga_0_q0;
        reg_759 <= img_ga_1_q0;
        reg_768 <= img_ga_2_q0;
        reg_777 <= img_ga_3_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_read_reg_951 <= y;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln23_fu_817_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln14_fu_855_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_condition_pp1_flush_enable = 1'b1;
    end else begin
        ap_condition_pp1_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln7_fu_893_p2 == 1'd0) & (1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_condition_pp2_flush_enable = 1'b1;
    end else begin
        ap_condition_pp2_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_939_p2 == 1'd0) & (1'b0 == ap_block_pp3_stage0_subdone) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        ap_condition_pp3_flush_enable = 1'b1;
    end else begin
        ap_condition_pp3_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter5 == 1'b0) & (ap_enable_reg_pp2_iter4 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0) & (ap_enable_reg_pp2_iter3 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter5 == 1'b0) & (ap_enable_reg_pp3_iter4 == 1'b0) & (ap_enable_reg_pp3_iter2 == 1'b0) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b0) & (ap_enable_reg_pp3_iter3 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga0_0_address0_local = zext_ln32_reg_1179_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp2_iter4 == 1'b1) & (1'b0 == ap_block_pp2_stage0))) begin
        img_ga0_0_address0_local = zext_ln7_reg_1122_pp2_iter3_reg;
    end else begin
        img_ga0_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp2_iter4 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp2_iter5 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        img_ga0_0_ce0_local = 1'b1;
    end else begin
        img_ga0_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga0_0_d0_local = val_1_8_reg_1272;
    end else if (((ap_enable_reg_pp2_iter4 == 1'b1) & (1'b0 == ap_block_pp2_stage0))) begin
        img_ga0_0_d0_local = reg_750;
    end else begin
        img_ga0_0_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp2_iter4 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        img_ga0_0_we0_local = 1'b1;
    end else begin
        img_ga0_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga0_1_address0_local = zext_ln32_reg_1179_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp2_iter4 == 1'b1) & (1'b0 == ap_block_pp2_stage0))) begin
        img_ga0_1_address0_local = zext_ln7_reg_1122_pp2_iter3_reg;
    end else begin
        img_ga0_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp2_iter4 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp2_iter5 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        img_ga0_1_ce0_local = 1'b1;
    end else begin
        img_ga0_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga0_1_d0_local = img_ga1bf_1_load_reg_1283;
    end else if (((ap_enable_reg_pp2_iter4 == 1'b1) & (1'b0 == ap_block_pp2_stage0))) begin
        img_ga0_1_d0_local = reg_759;
    end else begin
        img_ga0_1_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp2_iter4 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        img_ga0_1_we0_local = 1'b1;
    end else begin
        img_ga0_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga0_2_address0_local = zext_ln32_reg_1179_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp2_iter4 == 1'b1) & (1'b0 == ap_block_pp2_stage0))) begin
        img_ga0_2_address0_local = zext_ln7_reg_1122_pp2_iter3_reg;
    end else begin
        img_ga0_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp2_iter4 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp2_iter5 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        img_ga0_2_ce0_local = 1'b1;
    end else begin
        img_ga0_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga0_2_d0_local = val_1_9_reg_1294;
    end else if (((ap_enable_reg_pp2_iter4 == 1'b1) & (1'b0 == ap_block_pp2_stage0))) begin
        img_ga0_2_d0_local = reg_768;
    end else begin
        img_ga0_2_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (icmp_ln32_reg_1229_pp3_iter3_reg == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp2_iter4 == 1'b1) & (icmp_ln7_reg_1140_pp2_iter3_reg == 1'd1) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        img_ga0_2_we0_local = 1'b1;
    end else begin
        img_ga0_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga0_3_address0_local = zext_ln32_reg_1179_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp2_iter4 == 1'b1) & (1'b0 == ap_block_pp2_stage0))) begin
        img_ga0_3_address0_local = zext_ln7_reg_1122_pp2_iter3_reg;
    end else begin
        img_ga0_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp2_iter4 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp2_iter5 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        img_ga0_3_ce0_local = 1'b1;
    end else begin
        img_ga0_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga0_3_d0_local = img_ga1bf_3_load_reg_1305;
    end else if (((ap_enable_reg_pp2_iter4 == 1'b1) & (1'b0 == ap_block_pp2_stage0))) begin
        img_ga0_3_d0_local = reg_777;
    end else begin
        img_ga0_3_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (icmp_ln32_reg_1229_pp3_iter3_reg == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp2_iter4 == 1'b1) & (icmp_ln7_reg_1140_pp2_iter3_reg == 1'd1) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        img_ga0_3_we0_local = 1'b1;
    end else begin
        img_ga0_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga1_0_address0_local = zext_ln32_reg_1179_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_ga1_0_address0_local = zext_ln14_reg_1041_pp1_iter3_reg;
    end else begin
        img_ga1_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_ga1_0_ce0_local = 1'b1;
    end else begin
        img_ga1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga1_0_d0_local = val_2_reg_1277;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_ga1_0_d0_local = reg_750;
    end else begin
        img_ga1_0_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_ga1_0_we0_local = 1'b1;
    end else begin
        img_ga1_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga1_1_address0_local = zext_ln32_reg_1179_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_ga1_1_address0_local = zext_ln14_reg_1041_pp1_iter3_reg;
    end else begin
        img_ga1_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_ga1_1_ce0_local = 1'b1;
    end else begin
        img_ga1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga1_1_d0_local = img_ga2bf_1_load_reg_1288;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_ga1_1_d0_local = reg_759;
    end else begin
        img_ga1_1_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_ga1_1_we0_local = 1'b1;
    end else begin
        img_ga1_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga1_2_address0_local = zext_ln32_reg_1179_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_ga1_2_address0_local = zext_ln14_reg_1041_pp1_iter3_reg;
    end else begin
        img_ga1_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_ga1_2_ce0_local = 1'b1;
    end else begin
        img_ga1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga1_2_d0_local = val_2_1_reg_1299;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_ga1_2_d0_local = reg_768;
    end else begin
        img_ga1_2_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (icmp_ln32_reg_1229_pp3_iter3_reg == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (icmp_ln14_reg_1063_pp1_iter3_reg == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_ga1_2_we0_local = 1'b1;
    end else begin
        img_ga1_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga1_3_address0_local = zext_ln32_reg_1179_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_ga1_3_address0_local = zext_ln14_reg_1041_pp1_iter3_reg;
    end else begin
        img_ga1_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_ga1_3_ce0_local = 1'b1;
    end else begin
        img_ga1_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga1_3_d0_local = img_ga2bf_3_load_reg_1310;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_ga1_3_d0_local = reg_777;
    end else begin
        img_ga1_3_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (icmp_ln32_reg_1229_pp3_iter3_reg == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (icmp_ln14_reg_1063_pp1_iter3_reg == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_ga1_3_we0_local = 1'b1;
    end else begin
        img_ga1_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga1bf_0_address0_local = img_ga1bf_0_addr_1_reg_1195_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_ga1bf_0_address0_local = zext_ln14_reg_1041_pp1_iter3_reg;
    end else begin
        img_ga1bf_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_ga1bf_0_ce0_local = 1'b1;
    end else begin
        img_ga1bf_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        img_ga1bf_0_ce1_local = 1'b1;
    end else begin
        img_ga1bf_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga1bf_0_d0_local = val_2_reg_1277;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_ga1bf_0_d0_local = reg_750;
    end else begin
        img_ga1bf_0_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_ga1bf_0_we0_local = 1'b1;
    end else begin
        img_ga1bf_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga1bf_1_address0_local = img_ga1bf_1_addr_1_reg_1212_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_ga1bf_1_address0_local = zext_ln14_reg_1041_pp1_iter3_reg;
    end else begin
        img_ga1bf_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_ga1bf_1_ce0_local = 1'b1;
    end else begin
        img_ga1bf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        img_ga1bf_1_ce1_local = 1'b1;
    end else begin
        img_ga1bf_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga1bf_1_d0_local = img_ga2bf_1_load_reg_1288;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_ga1bf_1_d0_local = reg_759;
    end else begin
        img_ga1bf_1_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_ga1bf_1_we0_local = 1'b1;
    end else begin
        img_ga1bf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga1bf_2_address0_local = img_ga1bf_2_addr_1_reg_1233_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_ga1bf_2_address0_local = zext_ln14_reg_1041_pp1_iter3_reg;
    end else begin
        img_ga1bf_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_ga1bf_2_ce0_local = 1'b1;
    end else begin
        img_ga1bf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        img_ga1bf_2_ce1_local = 1'b1;
    end else begin
        img_ga1bf_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga1bf_2_d0_local = val_2_1_reg_1299;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_ga1bf_2_d0_local = reg_768;
    end else begin
        img_ga1bf_2_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (icmp_ln32_reg_1229_pp3_iter3_reg == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (icmp_ln14_reg_1063_pp1_iter3_reg == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_ga1bf_2_we0_local = 1'b1;
    end else begin
        img_ga1bf_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga1bf_3_address0_local = img_ga1bf_3_addr_1_reg_1250_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_ga1bf_3_address0_local = zext_ln14_reg_1041_pp1_iter3_reg;
    end else begin
        img_ga1bf_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_ga1bf_3_ce0_local = 1'b1;
    end else begin
        img_ga1bf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        img_ga1bf_3_ce1_local = 1'b1;
    end else begin
        img_ga1bf_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga1bf_3_d0_local = img_ga2bf_3_load_reg_1310;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_ga1bf_3_d0_local = reg_777;
    end else begin
        img_ga1bf_3_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (icmp_ln32_reg_1229_pp3_iter3_reg == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (icmp_ln14_reg_1063_pp1_iter3_reg == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_ga1bf_3_we0_local = 1'b1;
    end else begin
        img_ga1bf_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga2_0_address0_local = zext_ln32_reg_1179_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        img_ga2_0_address0_local = zext_ln23_reg_960_pp0_iter3_reg;
    end else begin
        img_ga2_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga2_0_ce0_local = 1'b1;
    end else begin
        img_ga2_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga2_0_we0_local = 1'b1;
    end else begin
        img_ga2_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga2_1_address0_local = zext_ln32_reg_1179_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        img_ga2_1_address0_local = zext_ln23_reg_960_pp0_iter3_reg;
    end else begin
        img_ga2_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga2_1_ce0_local = 1'b1;
    end else begin
        img_ga2_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga2_1_we0_local = 1'b1;
    end else begin
        img_ga2_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga2_2_address0_local = zext_ln32_reg_1179_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        img_ga2_2_address0_local = zext_ln23_reg_960_pp0_iter3_reg;
    end else begin
        img_ga2_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga2_2_ce0_local = 1'b1;
    end else begin
        img_ga2_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (icmp_ln32_reg_1229_pp3_iter3_reg == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln23_reg_982_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga2_2_we0_local = 1'b1;
    end else begin
        img_ga2_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga2_3_address0_local = zext_ln32_reg_1179_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        img_ga2_3_address0_local = zext_ln23_reg_960_pp0_iter3_reg;
    end else begin
        img_ga2_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga2_3_ce0_local = 1'b1;
    end else begin
        img_ga2_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (icmp_ln32_reg_1229_pp3_iter3_reg == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln23_reg_982_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga2_3_we0_local = 1'b1;
    end else begin
        img_ga2_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga2bf_0_address0_local = img_ga2bf_0_addr_1_reg_1201_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        img_ga2bf_0_address0_local = zext_ln23_reg_960_pp0_iter3_reg;
    end else begin
        img_ga2bf_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga2bf_0_ce0_local = 1'b1;
    end else begin
        img_ga2bf_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        img_ga2bf_0_ce1_local = 1'b1;
    end else begin
        img_ga2bf_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga2bf_0_we0_local = 1'b1;
    end else begin
        img_ga2bf_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga2bf_1_address0_local = img_ga2bf_1_addr_1_reg_1218_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        img_ga2bf_1_address0_local = zext_ln23_reg_960_pp0_iter3_reg;
    end else begin
        img_ga2bf_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga2bf_1_ce0_local = 1'b1;
    end else begin
        img_ga2bf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        img_ga2bf_1_ce1_local = 1'b1;
    end else begin
        img_ga2bf_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga2bf_1_we0_local = 1'b1;
    end else begin
        img_ga2bf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga2bf_2_address0_local = img_ga2bf_2_addr_1_reg_1239_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        img_ga2bf_2_address0_local = zext_ln23_reg_960_pp0_iter3_reg;
    end else begin
        img_ga2bf_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga2bf_2_ce0_local = 1'b1;
    end else begin
        img_ga2bf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        img_ga2bf_2_ce1_local = 1'b1;
    end else begin
        img_ga2bf_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (icmp_ln32_reg_1229_pp3_iter3_reg == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln23_reg_982_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga2bf_2_we0_local = 1'b1;
    end else begin
        img_ga2bf_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_ga2bf_3_address0_local = img_ga2bf_3_addr_1_reg_1256_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        img_ga2bf_3_address0_local = zext_ln23_reg_960_pp0_iter3_reg;
    end else begin
        img_ga2bf_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga2bf_3_ce0_local = 1'b1;
    end else begin
        img_ga2bf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        img_ga2bf_3_ce1_local = 1'b1;
    end else begin
        img_ga2bf_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (icmp_ln32_reg_1229_pp3_iter3_reg == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln23_reg_982_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga2bf_3_we0_local = 1'b1;
    end else begin
        img_ga2bf_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        img_ga_0_address0_local = zext_ln32_fu_915_p1;
    end else if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        img_ga_0_address0_local = zext_ln7_fu_877_p1;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        img_ga_0_address0_local = zext_ln14_fu_839_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_ga_0_address0_local = zext_ln23_fu_801_p1;
    end else begin
        img_ga_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) 
    & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_ga_0_ce0_local = 1'b1;
    end else begin
        img_ga_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        img_ga_1_address0_local = zext_ln32_fu_915_p1;
    end else if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        img_ga_1_address0_local = zext_ln7_fu_877_p1;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        img_ga_1_address0_local = zext_ln14_fu_839_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_ga_1_address0_local = zext_ln23_fu_801_p1;
    end else begin
        img_ga_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) 
    & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_ga_1_ce0_local = 1'b1;
    end else begin
        img_ga_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        img_ga_2_address0_local = zext_ln32_fu_915_p1;
    end else if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        img_ga_2_address0_local = zext_ln7_fu_877_p1;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        img_ga_2_address0_local = zext_ln14_fu_839_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_ga_2_address0_local = zext_ln23_fu_801_p1;
    end else begin
        img_ga_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) 
    & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_ga_2_ce0_local = 1'b1;
    end else begin
        img_ga_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        img_ga_3_address0_local = zext_ln32_fu_915_p1;
    end else if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        img_ga_3_address0_local = zext_ln7_fu_877_p1;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        img_ga_3_address0_local = zext_ln14_fu_839_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_ga_3_address0_local = zext_ln23_fu_801_p1;
    end else begin
        img_ga_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) 
    & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_ga_3_ce0_local = 1'b1;
    end else begin
        img_ga_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~(y_read_reg_951 == 8'd2) & ~(y_read_reg_951 == 8'd3) & ~(y_read_reg_951 == 8'd4) & (icmp_ln31_fu_786_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else if ((~(y_read_reg_951 == 8'd2) & ~(y_read_reg_951 == 8'd3) & ~(y_read_reg_951 == 8'd4) & (icmp_ln31_fu_786_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((ap_predicate_pred702_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((ap_predicate_pred675_state3 == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((ap_enable_reg_pp1_iter5 == 1'b1) & (ap_enable_reg_pp1_iter4 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((ap_enable_reg_pp1_iter5 == 1'b1) & (ap_enable_reg_pp1_iter4 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((ap_enable_reg_pp2_iter5 == 1'b1) & (ap_enable_reg_pp2_iter4 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((ap_enable_reg_pp2_iter5 == 1'b1) & (ap_enable_reg_pp2_iter4 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_pp3_stage0;
        end
        ap_ST_fsm_pp3_stage0 : begin
            if (~((ap_enable_reg_pp3_iter5 == 1'b1) & (ap_enable_reg_pp3_iter4 == 1'b0) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if (((ap_enable_reg_pp3_iter5 == 1'b1) & (ap_enable_reg_pp3_iter4 == 1'b0) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln14_fu_861_p2 = (x_5_reg_717 + 7'd4);

assign add_ln23_fu_823_p2 = (x_6_reg_706 + 7'd4);

assign add_ln32_fu_945_p2 = (x_7_reg_739 + 7'd4);

assign add_ln7_fu_899_p2 = (x_reg_728 + 7'd4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

assign ap_return = y_read_reg_951;

assign icmp_ln14_fu_855_p2 = ((or_ln_fu_847_p3 < 7'd86) ? 1'b1 : 1'b0);

assign icmp_ln23_fu_817_p2 = ((or_ln1_fu_809_p3 < 7'd86) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_786_p2 = ((y_read_reg_951 > 8'd4) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_939_p2 = ((or_ln2_fu_931_p3 < 7'd86) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_893_p2 = ((or_ln7_fu_885_p3 < 7'd86) ? 1'b1 : 1'b0);

assign img_ga0_0_address0 = img_ga0_0_address0_local;

assign img_ga0_0_ce0 = img_ga0_0_ce0_local;

assign img_ga0_0_d0 = img_ga0_0_d0_local;

assign img_ga0_0_we0 = img_ga0_0_we0_local;

assign img_ga0_1_address0 = img_ga0_1_address0_local;

assign img_ga0_1_ce0 = img_ga0_1_ce0_local;

assign img_ga0_1_d0 = img_ga0_1_d0_local;

assign img_ga0_1_we0 = img_ga0_1_we0_local;

assign img_ga0_2_address0 = img_ga0_2_address0_local;

assign img_ga0_2_ce0 = img_ga0_2_ce0_local;

assign img_ga0_2_d0 = img_ga0_2_d0_local;

assign img_ga0_2_we0 = img_ga0_2_we0_local;

assign img_ga0_3_address0 = img_ga0_3_address0_local;

assign img_ga0_3_ce0 = img_ga0_3_ce0_local;

assign img_ga0_3_d0 = img_ga0_3_d0_local;

assign img_ga0_3_we0 = img_ga0_3_we0_local;

assign img_ga1_0_address0 = img_ga1_0_address0_local;

assign img_ga1_0_ce0 = img_ga1_0_ce0_local;

assign img_ga1_0_d0 = img_ga1_0_d0_local;

assign img_ga1_0_we0 = img_ga1_0_we0_local;

assign img_ga1_1_address0 = img_ga1_1_address0_local;

assign img_ga1_1_ce0 = img_ga1_1_ce0_local;

assign img_ga1_1_d0 = img_ga1_1_d0_local;

assign img_ga1_1_we0 = img_ga1_1_we0_local;

assign img_ga1_2_address0 = img_ga1_2_address0_local;

assign img_ga1_2_ce0 = img_ga1_2_ce0_local;

assign img_ga1_2_d0 = img_ga1_2_d0_local;

assign img_ga1_2_we0 = img_ga1_2_we0_local;

assign img_ga1_3_address0 = img_ga1_3_address0_local;

assign img_ga1_3_ce0 = img_ga1_3_ce0_local;

assign img_ga1_3_d0 = img_ga1_3_d0_local;

assign img_ga1_3_we0 = img_ga1_3_we0_local;

assign img_ga1bf_0_address1 = zext_ln32_fu_915_p1;

assign img_ga1bf_1_address1 = zext_ln32_fu_915_p1;

assign img_ga1bf_2_address1 = zext_ln32_fu_915_p1;

assign img_ga1bf_3_address1 = zext_ln32_fu_915_p1;

assign img_ga2_0_address0 = img_ga2_0_address0_local;

assign img_ga2_0_ce0 = img_ga2_0_ce0_local;

assign img_ga2_0_d0 = reg_750;

assign img_ga2_0_we0 = img_ga2_0_we0_local;

assign img_ga2_1_address0 = img_ga2_1_address0_local;

assign img_ga2_1_ce0 = img_ga2_1_ce0_local;

assign img_ga2_1_d0 = reg_759;

assign img_ga2_1_we0 = img_ga2_1_we0_local;

assign img_ga2_2_address0 = img_ga2_2_address0_local;

assign img_ga2_2_ce0 = img_ga2_2_ce0_local;

assign img_ga2_2_d0 = reg_768;

assign img_ga2_2_we0 = img_ga2_2_we0_local;

assign img_ga2_3_address0 = img_ga2_3_address0_local;

assign img_ga2_3_ce0 = img_ga2_3_ce0_local;

assign img_ga2_3_d0 = reg_777;

assign img_ga2_3_we0 = img_ga2_3_we0_local;

assign img_ga2bf_0_address1 = zext_ln32_fu_915_p1;

assign img_ga2bf_1_address1 = zext_ln32_fu_915_p1;

assign img_ga2bf_2_address1 = zext_ln32_fu_915_p1;

assign img_ga2bf_3_address1 = zext_ln32_fu_915_p1;

assign img_ga_0_address0 = img_ga_0_address0_local;

assign img_ga_0_ce0 = img_ga_0_ce0_local;

assign img_ga_1_address0 = img_ga_1_address0_local;

assign img_ga_1_ce0 = img_ga_1_ce0_local;

assign img_ga_2_address0 = img_ga_2_address0_local;

assign img_ga_2_ce0 = img_ga_2_ce0_local;

assign img_ga_3_address0 = img_ga_3_address0_local;

assign img_ga_3_ce0 = img_ga_3_ce0_local;

assign lshr_ln14_fu_829_p4 = {{x_5_reg_717[6:2]}};

assign lshr_ln15_fu_905_p4 = {{x_7_reg_739[6:2]}};

assign lshr_ln7_fu_867_p4 = {{x_reg_728[6:2]}};

assign lshr_ln_fu_791_p4 = {{x_6_reg_706[6:2]}};

assign or_ln1_fu_809_p3 = {{lshr_ln_fu_791_p4}, {2'd2}};

assign or_ln2_fu_931_p3 = {{lshr_ln15_fu_905_p4}, {2'd2}};

assign or_ln7_fu_885_p3 = {{lshr_ln7_fu_867_p4}, {2'd2}};

assign or_ln_fu_847_p3 = {{lshr_ln14_fu_829_p4}, {2'd2}};

assign zext_ln14_fu_839_p1 = lshr_ln14_fu_829_p4;

assign zext_ln23_fu_801_p1 = lshr_ln_fu_791_p4;

assign zext_ln32_fu_915_p1 = lshr_ln15_fu_905_p4;

assign zext_ln7_fu_877_p1 = lshr_ln7_fu_867_p4;

always @ (posedge ap_clk) begin
    zext_ln23_reg_960[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln23_reg_960_pp0_iter1_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln23_reg_960_pp0_iter2_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln23_reg_960_pp0_iter3_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln14_reg_1041[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln14_reg_1041_pp1_iter1_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln14_reg_1041_pp1_iter2_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln14_reg_1041_pp1_iter3_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln7_reg_1122[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln7_reg_1122_pp2_iter1_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln7_reg_1122_pp2_iter2_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln7_reg_1122_pp2_iter3_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_1179[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_1179_pp3_iter1_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_1179_pp3_iter2_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_1179_pp3_iter3_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //top_module_line_buff2
