// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps

module top_module_ashr_54ns_11ns_54_7_1(clk,ce,reset,din0, din1, dout);
parameter ID = 1;
parameter NUM_STAGE = 1;
parameter din0_WIDTH = 1;
parameter din1_WIDTH = 1;
parameter dout_WIDTH = 1;
parameter OP = 1;

input clk;
input ce;
input reset;

input [din0_WIDTH - 1 : 0] din0; 
input [din0_WIDTH - 1 : 0] din1; 
output [dout_WIDTH - 1 : 0] dout;

wire signed [dout_WIDTH - 1 : 0] tmp_product;


reg signed [dout_WIDTH - 1 : 0] buff0;


reg [din0_WIDTH - 1 :0] din0_reg;
reg [din0_WIDTH - 1 :0] din1_reg;


reg signed [dout_WIDTH - 1 : 0] buff1;


reg signed [dout_WIDTH - 1 : 0] buff2;


reg signed [dout_WIDTH - 1 : 0] buff3;


reg signed [dout_WIDTH - 1 : 0] buff4;








assign tmp_product = $signed(din0_reg) >>> din1_reg;




always @(posedge clk) begin
    if (reset) begin






        buff4 <= 0;

    end
    else begin 
        if (ce) begin
            buff0 <= tmp_product;

            din0_reg <= din0;
            din1_reg <= din1;


            buff1 <= buff0;


            buff2 <= buff1;


            buff3 <= buff2;


            buff4 <= buff3;

        end
    end
end









assign dout = buff4;

endmodule
