// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_module_elaboration_data (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        peakCoordinates_2,
        peakCoordinates_0,
        peakCoordinates_3,
        peakCoordinates_1,
        ap_return
);

parameter    ap_ST_fsm_state1 = 58'd1;
parameter    ap_ST_fsm_state2 = 58'd2;
parameter    ap_ST_fsm_state3 = 58'd4;
parameter    ap_ST_fsm_state4 = 58'd8;
parameter    ap_ST_fsm_state5 = 58'd16;
parameter    ap_ST_fsm_state6 = 58'd32;
parameter    ap_ST_fsm_state7 = 58'd64;
parameter    ap_ST_fsm_state8 = 58'd128;
parameter    ap_ST_fsm_state9 = 58'd256;
parameter    ap_ST_fsm_state10 = 58'd512;
parameter    ap_ST_fsm_state11 = 58'd1024;
parameter    ap_ST_fsm_state12 = 58'd2048;
parameter    ap_ST_fsm_state13 = 58'd4096;
parameter    ap_ST_fsm_state14 = 58'd8192;
parameter    ap_ST_fsm_state15 = 58'd16384;
parameter    ap_ST_fsm_state16 = 58'd32768;
parameter    ap_ST_fsm_state17 = 58'd65536;
parameter    ap_ST_fsm_state18 = 58'd131072;
parameter    ap_ST_fsm_state19 = 58'd262144;
parameter    ap_ST_fsm_state20 = 58'd524288;
parameter    ap_ST_fsm_state21 = 58'd1048576;
parameter    ap_ST_fsm_state22 = 58'd2097152;
parameter    ap_ST_fsm_state23 = 58'd4194304;
parameter    ap_ST_fsm_state24 = 58'd8388608;
parameter    ap_ST_fsm_state25 = 58'd16777216;
parameter    ap_ST_fsm_state26 = 58'd33554432;
parameter    ap_ST_fsm_state27 = 58'd67108864;
parameter    ap_ST_fsm_state28 = 58'd134217728;
parameter    ap_ST_fsm_state29 = 58'd268435456;
parameter    ap_ST_fsm_state30 = 58'd536870912;
parameter    ap_ST_fsm_state31 = 58'd1073741824;
parameter    ap_ST_fsm_state32 = 58'd2147483648;
parameter    ap_ST_fsm_state33 = 58'd4294967296;
parameter    ap_ST_fsm_state34 = 58'd8589934592;
parameter    ap_ST_fsm_state35 = 58'd17179869184;
parameter    ap_ST_fsm_state36 = 58'd34359738368;
parameter    ap_ST_fsm_state37 = 58'd68719476736;
parameter    ap_ST_fsm_state38 = 58'd137438953472;
parameter    ap_ST_fsm_state39 = 58'd274877906944;
parameter    ap_ST_fsm_state40 = 58'd549755813888;
parameter    ap_ST_fsm_state41 = 58'd1099511627776;
parameter    ap_ST_fsm_state42 = 58'd2199023255552;
parameter    ap_ST_fsm_state43 = 58'd4398046511104;
parameter    ap_ST_fsm_state44 = 58'd8796093022208;
parameter    ap_ST_fsm_state45 = 58'd17592186044416;
parameter    ap_ST_fsm_state46 = 58'd35184372088832;
parameter    ap_ST_fsm_state47 = 58'd70368744177664;
parameter    ap_ST_fsm_state48 = 58'd140737488355328;
parameter    ap_ST_fsm_state49 = 58'd281474976710656;
parameter    ap_ST_fsm_state50 = 58'd562949953421312;
parameter    ap_ST_fsm_state51 = 58'd1125899906842624;
parameter    ap_ST_fsm_state52 = 58'd2251799813685248;
parameter    ap_ST_fsm_state53 = 58'd4503599627370496;
parameter    ap_ST_fsm_state54 = 58'd9007199254740992;
parameter    ap_ST_fsm_state55 = 58'd18014398509481984;
parameter    ap_ST_fsm_state56 = 58'd36028797018963968;
parameter    ap_ST_fsm_state57 = 58'd72057594037927936;
parameter    ap_ST_fsm_state58 = 58'd144115188075855872;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] peakCoordinates_2;
input  [7:0] peakCoordinates_0;
input  [7:0] peakCoordinates_3;
input  [7:0] peakCoordinates_1;
output  [6:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [57:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] val_div_address0;
wire   [22:0] val_div_q0;
wire   [3:0] val_div_address1;
wire   [22:0] val_div_q1;
wire   [63:0] grp_fu_147_p1;
reg   [63:0] conv3_reg_1034;
wire    ap_CS_fsm_state7;
wire   [63:0] grp_fu_150_p1;
reg   [63:0] conv3_1_reg_1039;
wire   [63:0] grp_fu_137_p2;
reg   [63:0] pf_reg_1044;
wire    ap_CS_fsm_state21;
wire   [63:0] grp_fu_142_p2;
reg   [63:0] pf_1_reg_1049;
wire    ap_CS_fsm_state22;
reg   [0:0] tmp_reg_1059;
wire   [53:0] zext_ln21_1_fu_210_p1;
reg   [53:0] zext_ln21_1_reg_1066;
wire   [11:0] sub_ln21_1_fu_226_p2;
reg   [11:0] sub_ln21_1_reg_1072;
wire   [10:0] trunc_ln21_2_fu_232_p1;
reg   [10:0] trunc_ln21_2_reg_1079;
reg   [0:0] tmp_14_reg_1090;
wire   [53:0] zext_ln21_9_fu_275_p1;
reg   [53:0] zext_ln21_9_reg_1097;
wire   [11:0] sub_ln21_4_fu_291_p2;
reg   [11:0] sub_ln21_4_reg_1103;
wire   [10:0] trunc_ln21_9_fu_297_p1;
reg   [10:0] trunc_ln21_9_reg_1110;
wire   [53:0] grp_fu_214_p2;
reg   [53:0] sub_ln21_reg_1116;
wire    ap_CS_fsm_state23;
wire   [0:0] grp_fu_220_p2;
reg   [0:0] icmp_ln21_reg_1121;
wire   [0:0] icmp_ln21_1_fu_301_p2;
reg   [0:0] icmp_ln21_1_reg_1128;
wire   [11:0] add_ln21_fu_306_p2;
reg   [11:0] add_ln21_reg_1134;
wire   [10:0] trunc_ln21_3_fu_311_p1;
reg   [10:0] trunc_ln21_3_reg_1139;
wire   [10:0] sub_ln21_2_fu_315_p2;
reg   [10:0] sub_ln21_2_reg_1144;
wire   [0:0] icmp_ln21_2_fu_320_p2;
reg   [0:0] icmp_ln21_2_reg_1149;
wire   [53:0] grp_fu_279_p2;
reg   [53:0] sub_ln21_3_reg_1155;
wire   [0:0] grp_fu_285_p2;
reg   [0:0] icmp_ln21_6_reg_1160;
wire   [0:0] icmp_ln21_7_fu_325_p2;
reg   [0:0] icmp_ln21_7_reg_1167;
wire   [11:0] add_ln21_4_fu_330_p2;
reg   [11:0] add_ln21_4_reg_1173;
wire   [10:0] trunc_ln21_10_fu_335_p1;
reg   [10:0] trunc_ln21_10_reg_1178;
wire   [10:0] sub_ln21_5_fu_339_p2;
reg   [10:0] sub_ln21_5_reg_1183;
wire   [0:0] icmp_ln21_8_fu_344_p2;
reg   [0:0] icmp_ln21_8_reg_1188;
wire   [53:0] select_ln21_fu_349_p3;
reg   [53:0] select_ln21_reg_1194;
wire    ap_CS_fsm_state24;
wire   [10:0] select_ln21_1_fu_354_p3;
reg   [10:0] select_ln21_1_reg_1200;
wire   [23:0] trunc_ln21_4_fu_359_p1;
reg   [23:0] trunc_ln21_4_reg_1208;
wire   [0:0] icmp_ln21_4_fu_363_p2;
reg   [0:0] icmp_ln21_4_reg_1214;
wire   [10:0] add_ln21_2_fu_368_p2;
reg   [10:0] add_ln21_2_reg_1219;
wire   [53:0] select_ln21_4_fu_373_p3;
reg   [53:0] select_ln21_4_reg_1224;
wire   [10:0] select_ln21_5_fu_378_p3;
reg   [10:0] select_ln21_5_reg_1230;
wire   [23:0] trunc_ln21_11_fu_383_p1;
reg   [23:0] trunc_ln21_11_reg_1238;
wire   [0:0] icmp_ln21_10_fu_387_p2;
reg   [0:0] icmp_ln21_10_reg_1244;
wire   [10:0] add_ln21_5_fu_392_p2;
reg   [10:0] add_ln21_5_reg_1249;
wire    ap_CS_fsm_state25;
wire   [0:0] grp_fu_408_p3;
reg   [0:0] tmp_10_reg_1274;
wire    ap_CS_fsm_state26;
wire   [0:0] grp_fu_426_p3;
reg   [0:0] tmp_15_reg_1279;
wire   [0:0] icmp_ln21_3_fu_433_p2;
reg   [0:0] icmp_ln21_3_reg_1284;
wire    ap_CS_fsm_state27;
wire   [0:0] icmp_ln21_5_fu_438_p2;
reg   [0:0] icmp_ln21_5_reg_1289;
wire   [0:0] cond64_i_fu_451_p3;
reg   [0:0] cond64_i_reg_1299;
wire   [0:0] icmp_ln21_9_fu_456_p2;
reg   [0:0] icmp_ln21_9_reg_1304;
wire   [0:0] icmp_ln21_11_fu_461_p2;
reg   [0:0] icmp_ln21_11_reg_1309;
wire   [0:0] cond64_i176_fu_474_p3;
reg   [0:0] cond64_i176_reg_1319;
wire   [53:0] grp_fu_400_p2;
reg   [53:0] ashr_ln21_reg_1324;
wire    ap_CS_fsm_state31;
wire   [53:0] grp_fu_418_p2;
reg   [53:0] ashr_ln21_1_reg_1329;
wire   [23:0] select_ln21_2_fu_489_p3;
reg   [23:0] select_ln21_2_reg_1334;
wire    ap_CS_fsm_state32;
wire   [23:0] select_ln21_6_fu_506_p3;
reg   [23:0] select_ln21_6_reg_1339;
wire   [23:0] grp_fu_446_p2;
reg   [23:0] shl_ln21_reg_1344;
wire    ap_CS_fsm_state33;
wire   [23:0] grp_fu_469_p2;
reg   [23:0] shl_ln21_1_reg_1354;
wire   [23:0] select_ln21_3_fu_529_p3;
reg   [23:0] select_ln21_3_reg_1364;
wire    ap_CS_fsm_state34;
wire   [23:0] grp_fu_516_p2;
reg   [23:0] add_ln21_3_reg_1369;
wire   [0:0] and_ln21_fu_540_p2;
reg   [0:0] and_ln21_reg_1374;
wire   [0:0] and_ln21_1_fu_555_p2;
reg   [0:0] and_ln21_1_reg_1379;
wire   [23:0] select_ln21_7_fu_560_p3;
reg   [23:0] select_ln21_7_reg_1384;
wire   [23:0] grp_fu_524_p2;
reg   [23:0] add_ln21_6_reg_1389;
wire   [0:0] and_ln21_2_fu_571_p2;
reg   [0:0] and_ln21_2_reg_1394;
wire   [0:0] and_ln21_3_fu_586_p2;
reg   [0:0] and_ln21_3_reg_1399;
wire   [23:0] theta_fu_598_p11;
reg  signed [23:0] theta_reg_1404;
wire    ap_CS_fsm_state35;
wire   [23:0] theta_1_fu_626_p11;
reg  signed [23:0] theta_1_reg_1409;
wire    ap_CS_fsm_state36;
wire   [31:0] grp_fu_650_p2;
reg   [31:0] mul_ln22_reg_1424;
wire    ap_CS_fsm_state40;
reg   [3:0] trunc_ln_reg_1429;
wire   [19:0] trunc_ln22_fu_675_p1;
reg   [19:0] trunc_ln22_reg_1436;
wire   [31:0] grp_fu_659_p2;
reg   [31:0] mul_ln22_1_reg_1441;
reg   [3:0] trunc_ln22_1_reg_1446;
wire   [19:0] trunc_ln22_2_fu_689_p1;
reg   [19:0] trunc_ln22_2_reg_1453;
wire   [0:0] grp_fu_693_p2;
reg   [0:0] icmp_ln22_reg_1458;
wire    ap_CS_fsm_state42;
wire   [3:0] add_ln22_fu_703_p2;
reg   [3:0] add_ln22_reg_1463;
wire   [0:0] grp_fu_698_p2;
reg   [0:0] icmp_ln22_1_reg_1468;
wire   [3:0] add_ln22_1_fu_708_p2;
reg   [3:0] add_ln22_1_reg_1473;
wire   [3:0] ind_fu_732_p2;
reg   [3:0] ind_reg_1478;
wire    ap_CS_fsm_state43;
wire   [3:0] ind_1_fu_757_p2;
reg   [3:0] ind_1_reg_1483;
wire    ap_CS_fsm_state44;
reg   [22:0] val_div_load_reg_1498;
wire    ap_CS_fsm_state47;
reg   [22:0] val_div_load_1_reg_1503;
wire    ap_CS_fsm_state48;
wire   [28:0] grp_fu_790_p2;
reg   [28:0] sub_ln27_reg_1528;
wire    ap_CS_fsm_state49;
reg   [8:0] tmp_1_reg_1533;
wire   [19:0] trunc_ln27_fu_831_p1;
reg   [19:0] trunc_ln27_reg_1540;
wire   [28:0] grp_fu_815_p2;
reg   [28:0] sub_ln27_1_reg_1545;
reg   [8:0] tmp_2_reg_1550;
wire   [19:0] trunc_ln27_3_fu_845_p1;
reg   [19:0] trunc_ln27_3_reg_1557;
wire   [0:0] grp_fu_849_p2;
reg   [0:0] icmp_ln27_reg_1562;
wire    ap_CS_fsm_state51;
wire   [8:0] add_ln27_fu_859_p2;
reg   [8:0] add_ln27_reg_1567;
wire   [0:0] grp_fu_854_p2;
reg   [0:0] icmp_ln27_1_reg_1572;
wire   [8:0] add_ln27_12_fu_864_p2;
reg   [8:0] add_ln27_12_reg_1577;
wire   [7:0] trunc_ln27_1_fu_892_p1;
reg   [7:0] trunc_ln27_1_reg_1582;
wire    ap_CS_fsm_state52;
reg   [0:0] tmp_13_reg_1587;
wire   [7:0] trunc_ln27_4_fu_927_p1;
reg   [7:0] trunc_ln27_4_reg_1592;
reg   [0:0] tmp_19_reg_1597;
wire   [7:0] distance_1_fu_939_p3;
reg   [7:0] distance_1_reg_1602;
wire    ap_CS_fsm_state53;
wire   [6:0] trunc_ln27_2_fu_945_p1;
reg   [6:0] trunc_ln27_2_reg_1607;
wire   [7:0] distance_4_fu_949_p3;
reg   [7:0] distance_4_reg_1612;
wire   [6:0] trunc_ln27_5_fu_955_p1;
reg   [6:0] trunc_ln27_5_reg_1617;
wire   [0:0] icmp_ln31_fu_959_p2;
reg   [0:0] icmp_ln31_reg_1622;
wire    ap_CS_fsm_state54;
wire   [0:0] icmp_ln31_1_fu_964_p2;
reg   [0:0] icmp_ln31_1_reg_1627;
wire   [6:0] distance_6_fu_969_p3;
reg   [6:0] distance_6_reg_1632;
wire    ap_CS_fsm_state55;
wire   [6:0] distance_7_fu_975_p3;
reg   [6:0] distance_7_reg_1639;
wire   [0:0] icmp_ln41_fu_981_p2;
reg   [0:0] icmp_ln41_reg_1646;
wire    ap_CS_fsm_state56;
reg   [6:0] trunc_ln16_reg_1652;
wire    ap_CS_fsm_state57;
wire   [63:0] zext_ln27_fu_763_p1;
wire   [63:0] zext_ln27_2_fu_767_p1;
reg    val_div_ce1_local;
wire    ap_CS_fsm_state45;
wire    ap_CS_fsm_state46;
reg    val_div_ce0_local;
wire    ap_CS_fsm_state8;
wire  signed [31:0] grp_fu_147_p0;
wire  signed [31:0] grp_fu_150_p0;
wire   [63:0] bitcast_ln716_fu_171_p1;
wire   [10:0] tmp_s_fu_186_p3;
wire   [51:0] trunc_ln21_1_fu_198_p1;
wire   [52:0] zext_ln21_1_cast_fu_202_p3;
wire   [53:0] grp_fu_214_p1;
wire   [62:0] grp_fu_220_p0;
wire   [11:0] zext_ln21_fu_194_p1;
wire   [63:0] bitcast_ln716_1_fu_236_p1;
wire   [10:0] tmp_17_fu_251_p3;
wire   [51:0] trunc_ln21_8_fu_263_p1;
wire   [52:0] zext_ln21_9_cast_fu_267_p3;
wire   [53:0] grp_fu_279_p1;
wire   [62:0] grp_fu_285_p0;
wire   [11:0] zext_ln21_5_fu_259_p1;
wire   [53:0] grp_fu_400_p1;
wire   [31:0] grp_fu_408_p2;
wire   [53:0] grp_fu_418_p1;
wire   [31:0] grp_fu_426_p2;
wire   [23:0] grp_fu_446_p1;
wire   [23:0] grp_fu_469_p1;
wire   [23:0] trunc_ln21_5_fu_486_p1;
wire   [23:0] select_ln21_8_fu_479_p3;
wire   [23:0] trunc_ln21_12_fu_503_p1;
wire   [23:0] select_ln21_9_fu_496_p3;
wire   [23:0] grp_fu_516_p1;
wire   [23:0] grp_fu_524_p1;
wire   [0:0] xor_ln21_fu_535_p2;
wire   [0:0] or_ln21_fu_545_p2;
wire   [0:0] xor_ln21_1_fu_549_p2;
wire   [0:0] xor_ln21_2_fu_566_p2;
wire   [0:0] or_ln21_1_fu_576_p2;
wire   [0:0] xor_ln21_3_fu_580_p2;
wire   [23:0] theta_fu_598_p9;
wire   [2:0] theta_fu_598_p10;
wire   [23:0] theta_1_fu_626_p9;
wire   [2:0] theta_1_fu_626_p10;
wire   [7:0] grp_fu_650_p1;
wire   [7:0] grp_fu_659_p1;
wire    ap_CS_fsm_state41;
wire   [0:0] tmp_11_fu_713_p3;
wire   [3:0] select_ln22_fu_720_p3;
wire   [3:0] the_int_fu_725_p3;
wire   [0:0] tmp_16_fu_738_p3;
wire   [3:0] select_ln22_1_fu_745_p3;
wire   [3:0] the_int_1_fu_750_p3;
wire   [27:0] peak_fu_775_p3;
wire  signed [28:0] grp_fu_790_p0;
wire  signed [28:0] grp_fu_790_p1;
wire   [27:0] peak_1_fu_800_p3;
wire  signed [28:0] grp_fu_815_p0;
wire  signed [28:0] grp_fu_815_p1;
wire    ap_CS_fsm_state50;
wire   [0:0] tmp_12_fu_869_p3;
wire   [8:0] select_ln27_fu_876_p3;
wire  signed [8:0] distance_fu_881_p3;
wire  signed [9:0] sext_ln27_33_fu_888_p1;
wire   [0:0] tmp_18_fu_904_p3;
wire   [8:0] select_ln27_1_fu_911_p3;
wire  signed [8:0] distance_3_fu_916_p3;
wire  signed [9:0] sext_ln27_36_fu_923_p1;
wire   [6:0] outData_2_fu_985_p3;
wire   [6:0] outData_fu_990_p3;
wire   [7:0] zext_ln60_fu_995_p1;
wire   [7:0] zext_ln60_1_fu_999_p1;
wire   [7:0] add_ln60_fu_1003_p2;
wire    ap_CS_fsm_state58;
reg   [57:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire   [0:0] grp_fu_408_p0;
wire   [0:0] grp_fu_426_p0;
wire  signed [2:0] theta_fu_598_p1;
wire   [2:0] theta_fu_598_p3;
wire   [2:0] theta_fu_598_p5;
wire   [2:0] theta_fu_598_p7;
wire  signed [2:0] theta_1_fu_626_p1;
wire   [2:0] theta_1_fu_626_p3;
wire   [2:0] theta_1_fu_626_p5;
wire   [2:0] theta_1_fu_626_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 58'd1;
end

top_module_elaboration_data_val_div_ROM_AUTO_3R #(
    .DataWidth( 23 ),
    .AddressRange( 11 ),
    .AddressWidth( 4 ))
val_div_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(val_div_address0),
    .ce0(val_div_ce0_local),
    .q0(val_div_q0),
    .address1(val_div_address1),
    .ce1(val_div_ce1_local),
    .q1(val_div_q1)
);

top_module_dmul_64ns_64ns_64_14_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 14 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_14_full_dsp_1_U634(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv3_reg_1034),
    .din1(64'd4580686841472271306),
    .ce(1'b1),
    .dout(grp_fu_137_p2)
);

top_module_dmul_64ns_64ns_64_14_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 14 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_14_full_dsp_1_U635(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv3_1_reg_1039),
    .din1(64'd4580686841472271306),
    .ce(1'b1),
    .dout(grp_fu_142_p2)
);

top_module_sitodp_32s_64_7_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32s_64_7_no_dsp_1_U636(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_147_p0),
    .ce(1'b1),
    .dout(grp_fu_147_p1)
);

top_module_sitodp_32s_64_7_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32s_64_7_no_dsp_1_U637(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_150_p0),
    .ce(1'b1),
    .dout(grp_fu_150_p1)
);

top_module_sub_54ns_54ns_54_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 54 ),
    .din1_WIDTH( 54 ),
    .dout_WIDTH( 54 ))
sub_54ns_54ns_54_2_1_U638(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(54'd0),
    .din1(grp_fu_214_p1),
    .ce(1'b1),
    .dout(grp_fu_214_p2)
);

top_module_icmp_63ns_63ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 63 ),
    .din1_WIDTH( 63 ),
    .OP_CODE( 0 ),
    .dout_WIDTH( 1 ))
icmp_63ns_63ns_1_2_1_U639(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_220_p0),
    .din1(63'd0),
    .ce(1'b1),
    .dout(grp_fu_220_p2)
);

top_module_sub_54ns_54ns_54_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 54 ),
    .din1_WIDTH( 54 ),
    .dout_WIDTH( 54 ))
sub_54ns_54ns_54_2_1_U640(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(54'd0),
    .din1(grp_fu_279_p1),
    .ce(1'b1),
    .dout(grp_fu_279_p2)
);

top_module_icmp_63ns_63ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 63 ),
    .din1_WIDTH( 63 ),
    .OP_CODE( 0 ),
    .dout_WIDTH( 1 ))
icmp_63ns_63ns_1_2_1_U641(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_285_p0),
    .din1(63'd0),
    .ce(1'b1),
    .dout(grp_fu_285_p2)
);

top_module_ashr_54ns_11ns_54_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .OP( 2 ),
    .din0_WIDTH( 54 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 54 ))
ashr_54ns_11ns_54_7_1_U642(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln21_reg_1194),
    .din1(grp_fu_400_p1),
    .ce(1'b1),
    .dout(grp_fu_400_p2)
);

top_module_bitselect_1ns_54ns_32ns_1_2_1 #(
    .DATAWIDTH( 54 ),
    .ADDRWIDTH( 32 ))
bitselect_1ns_54ns_32ns_1_2_1_U643(
    .clk(ap_clk),
    .din(select_ln21_reg_1194),
    .sel(grp_fu_408_p2),
    .dout(grp_fu_408_p3)
);

top_module_ashr_54ns_11ns_54_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .OP( 2 ),
    .din0_WIDTH( 54 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 54 ))
ashr_54ns_11ns_54_7_1_U644(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln21_4_reg_1224),
    .din1(grp_fu_418_p1),
    .ce(1'b1),
    .dout(grp_fu_418_p2)
);

top_module_bitselect_1ns_54ns_32ns_1_2_1 #(
    .DATAWIDTH( 54 ),
    .ADDRWIDTH( 32 ))
bitselect_1ns_54ns_32ns_1_2_1_U645(
    .clk(ap_clk),
    .din(select_ln21_4_reg_1224),
    .sel(grp_fu_426_p2),
    .dout(grp_fu_426_p3)
);

top_module_shl_24ns_11ns_24_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .OP( 0 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 24 ))
shl_24ns_11ns_24_7_1_U646(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln21_4_reg_1208),
    .din1(grp_fu_446_p1),
    .ce(1'b1),
    .dout(grp_fu_446_p2)
);

top_module_shl_24ns_11ns_24_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .OP( 0 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 24 ))
shl_24ns_11ns_24_7_1_U647(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln21_11_reg_1238),
    .din1(grp_fu_469_p1),
    .ce(1'b1),
    .dout(grp_fu_469_p2)
);

top_module_add_24ns_24ns_24_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
add_24ns_24ns_24_2_1_U648(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln21_2_reg_1334),
    .din1(grp_fu_516_p1),
    .ce(1'b1),
    .dout(grp_fu_516_p2)
);

top_module_add_24ns_24ns_24_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
add_24ns_24ns_24_2_1_U649(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln21_6_reg_1339),
    .din1(grp_fu_524_p1),
    .ce(1'b1),
    .dout(grp_fu_524_p2)
);

(* dissolve_hierarchy = "yes" *) top_module_sparsemux_9_3_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 24 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 24 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 24 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 24 ),
    .def_WIDTH( 24 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 24 ))
sparsemux_9_3_24_1_1_U650(
    .din0(24'd0),
    .din1(trunc_ln21_4_reg_1208),
    .din2(add_ln21_3_reg_1369),
    .din3(select_ln21_3_reg_1364),
    .def(theta_fu_598_p9),
    .sel(theta_fu_598_p10),
    .dout(theta_fu_598_p11)
);

(* dissolve_hierarchy = "yes" *) top_module_sparsemux_9_3_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 24 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 24 ),
    .CASE2( 3'h1 ),
    .din2_WIDTH( 24 ),
    .CASE3( 3'h0 ),
    .din3_WIDTH( 24 ),
    .def_WIDTH( 24 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 24 ))
sparsemux_9_3_24_1_1_U651(
    .din0(24'd0),
    .din1(trunc_ln21_11_reg_1238),
    .din2(add_ln21_6_reg_1389),
    .din3(select_ln21_7_reg_1384),
    .def(theta_1_fu_626_p9),
    .sel(theta_1_fu_626_p10),
    .dout(theta_1_fu_626_p11)
);

top_module_mul_24s_8ns_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_24s_8ns_32_5_1_U652(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(theta_reg_1404),
    .din1(grp_fu_650_p1),
    .ce(1'b1),
    .dout(grp_fu_650_p2)
);

top_module_mul_24s_8ns_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mul_24s_8ns_32_5_1_U653(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(theta_1_reg_1409),
    .din1(grp_fu_659_p1),
    .ce(1'b1),
    .dout(grp_fu_659_p2)
);

top_module_icmp_20ns_20ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 20 ),
    .OP_CODE( 1 ),
    .dout_WIDTH( 1 ))
icmp_20ns_20ns_1_2_1_U654(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln22_reg_1436),
    .din1(20'd0),
    .ce(1'b1),
    .dout(grp_fu_693_p2)
);

top_module_icmp_20ns_20ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 20 ),
    .OP_CODE( 1 ),
    .dout_WIDTH( 1 ))
icmp_20ns_20ns_1_2_1_U655(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln22_2_reg_1453),
    .din1(20'd0),
    .ce(1'b1),
    .dout(grp_fu_698_p2)
);

top_module_sub_29s_29s_29_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 29 ),
    .din1_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
sub_29s_29s_29_2_1_U656(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_790_p0),
    .din1(grp_fu_790_p1),
    .ce(1'b1),
    .dout(grp_fu_790_p2)
);

top_module_sub_29s_29s_29_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 29 ),
    .din1_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
sub_29s_29s_29_2_1_U657(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_815_p0),
    .din1(grp_fu_815_p1),
    .ce(1'b1),
    .dout(grp_fu_815_p2)
);

top_module_icmp_20ns_20ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 20 ),
    .OP_CODE( 1 ),
    .dout_WIDTH( 1 ))
icmp_20ns_20ns_1_2_1_U658(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln27_reg_1540),
    .din1(20'd0),
    .ce(1'b1),
    .dout(grp_fu_849_p2)
);

top_module_icmp_20ns_20ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 20 ),
    .OP_CODE( 1 ),
    .dout_WIDTH( 1 ))
icmp_20ns_20ns_1_2_1_U659(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln27_3_reg_1557),
    .din1(20'd0),
    .ce(1'b1),
    .dout(grp_fu_854_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        add_ln21_2_reg_1219 <= add_ln21_2_fu_368_p2;
        add_ln21_5_reg_1249 <= add_ln21_5_fu_392_p2;
        icmp_ln21_10_reg_1244 <= icmp_ln21_10_fu_387_p2;
        icmp_ln21_4_reg_1214 <= icmp_ln21_4_fu_363_p2;
        select_ln21_1_reg_1200 <= select_ln21_1_fu_354_p3;
        select_ln21_4_reg_1224 <= select_ln21_4_fu_373_p3;
        select_ln21_5_reg_1230 <= select_ln21_5_fu_378_p3;
        select_ln21_reg_1194 <= select_ln21_fu_349_p3;
        trunc_ln21_11_reg_1238 <= trunc_ln21_11_fu_383_p1;
        trunc_ln21_4_reg_1208 <= trunc_ln21_4_fu_359_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        add_ln21_3_reg_1369 <= grp_fu_516_p2;
        add_ln21_6_reg_1389 <= grp_fu_524_p2;
        and_ln21_1_reg_1379 <= and_ln21_1_fu_555_p2;
        and_ln21_2_reg_1394 <= and_ln21_2_fu_571_p2;
        and_ln21_3_reg_1399 <= and_ln21_3_fu_586_p2;
        and_ln21_reg_1374 <= and_ln21_fu_540_p2;
        select_ln21_3_reg_1364 <= select_ln21_3_fu_529_p3;
        select_ln21_7_reg_1384 <= select_ln21_7_fu_560_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        add_ln21_4_reg_1173 <= add_ln21_4_fu_330_p2;
        add_ln21_reg_1134 <= add_ln21_fu_306_p2;
        icmp_ln21_1_reg_1128 <= icmp_ln21_1_fu_301_p2;
        icmp_ln21_2_reg_1149 <= icmp_ln21_2_fu_320_p2;
        icmp_ln21_6_reg_1160 <= grp_fu_285_p2;
        icmp_ln21_7_reg_1167 <= icmp_ln21_7_fu_325_p2;
        icmp_ln21_8_reg_1188 <= icmp_ln21_8_fu_344_p2;
        icmp_ln21_reg_1121 <= grp_fu_220_p2;
        sub_ln21_2_reg_1144 <= sub_ln21_2_fu_315_p2;
        sub_ln21_3_reg_1155 <= grp_fu_279_p2;
        sub_ln21_5_reg_1183 <= sub_ln21_5_fu_339_p2;
        sub_ln21_reg_1116 <= grp_fu_214_p2;
        trunc_ln21_10_reg_1178 <= trunc_ln21_10_fu_335_p1;
        trunc_ln21_3_reg_1139 <= trunc_ln21_3_fu_311_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        add_ln22_1_reg_1473 <= add_ln22_1_fu_708_p2;
        add_ln22_reg_1463 <= add_ln22_fu_703_p2;
        icmp_ln22_1_reg_1468 <= grp_fu_698_p2;
        icmp_ln22_reg_1458 <= grp_fu_693_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        add_ln27_12_reg_1577 <= add_ln27_12_fu_864_p2;
        add_ln27_reg_1567 <= add_ln27_fu_859_p2;
        icmp_ln27_1_reg_1572 <= grp_fu_854_p2;
        icmp_ln27_reg_1562 <= grp_fu_849_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        ashr_ln21_1_reg_1329 <= grp_fu_418_p2;
        ashr_ln21_reg_1324 <= grp_fu_400_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        cond64_i176_reg_1319 <= cond64_i176_fu_474_p3;
        cond64_i_reg_1299 <= cond64_i_fu_451_p3;
        icmp_ln21_11_reg_1309 <= icmp_ln21_11_fu_461_p2;
        icmp_ln21_3_reg_1284 <= icmp_ln21_3_fu_433_p2;
        icmp_ln21_5_reg_1289 <= icmp_ln21_5_fu_438_p2;
        icmp_ln21_9_reg_1304 <= icmp_ln21_9_fu_456_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        conv3_1_reg_1039 <= grp_fu_150_p1;
        conv3_reg_1034 <= grp_fu_147_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        distance_1_reg_1602 <= distance_1_fu_939_p3;
        distance_4_reg_1612 <= distance_4_fu_949_p3;
        trunc_ln27_2_reg_1607 <= trunc_ln27_2_fu_945_p1;
        trunc_ln27_5_reg_1617 <= trunc_ln27_5_fu_955_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        distance_6_reg_1632 <= distance_6_fu_969_p3;
        distance_7_reg_1639 <= distance_7_fu_975_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state54)) begin
        icmp_ln31_1_reg_1627 <= icmp_ln31_1_fu_964_p2;
        icmp_ln31_reg_1622 <= icmp_ln31_fu_959_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        icmp_ln41_reg_1646 <= icmp_ln41_fu_981_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        ind_1_reg_1483 <= ind_1_fu_757_p2;
        ind_reg_1478 <= ind_fu_732_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        mul_ln22_1_reg_1441 <= grp_fu_659_p2;
        mul_ln22_reg_1424 <= grp_fu_650_p2;
        trunc_ln22_1_reg_1446 <= {{grp_fu_659_p2[23:20]}};
        trunc_ln22_2_reg_1453 <= trunc_ln22_2_fu_689_p1;
        trunc_ln22_reg_1436 <= trunc_ln22_fu_675_p1;
        trunc_ln_reg_1429 <= {{grp_fu_650_p2[23:20]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        pf_1_reg_1049 <= grp_fu_142_p2;
        pf_reg_1044 <= grp_fu_137_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        select_ln21_2_reg_1334 <= select_ln21_2_fu_489_p3;
        select_ln21_6_reg_1339 <= select_ln21_6_fu_506_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        shl_ln21_1_reg_1354 <= grp_fu_469_p2;
        shl_ln21_reg_1344 <= grp_fu_446_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        sub_ln21_1_reg_1072 <= sub_ln21_1_fu_226_p2;
        sub_ln21_4_reg_1103 <= sub_ln21_4_fu_291_p2;
        tmp_14_reg_1090 <= bitcast_ln716_1_fu_236_p1[32'd63];
        tmp_reg_1059 <= bitcast_ln716_fu_171_p1[32'd63];
        trunc_ln21_2_reg_1079 <= trunc_ln21_2_fu_232_p1;
        trunc_ln21_9_reg_1110 <= trunc_ln21_9_fu_297_p1;
        zext_ln21_1_reg_1066[51 : 0] <= zext_ln21_1_fu_210_p1[51 : 0];
        zext_ln21_9_reg_1097[51 : 0] <= zext_ln21_9_fu_275_p1[51 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        sub_ln27_1_reg_1545 <= grp_fu_815_p2;
        sub_ln27_reg_1528 <= grp_fu_790_p2;
        tmp_1_reg_1533 <= {{grp_fu_790_p2[28:20]}};
        tmp_2_reg_1550 <= {{grp_fu_815_p2[28:20]}};
        trunc_ln27_3_reg_1557 <= trunc_ln27_3_fu_845_p1;
        trunc_ln27_reg_1540 <= trunc_ln27_fu_831_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        theta_1_reg_1409 <= theta_1_fu_626_p11;
        theta_reg_1404 <= theta_fu_598_p11;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        tmp_10_reg_1274 <= grp_fu_408_p3;
        tmp_15_reg_1279 <= grp_fu_426_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        tmp_13_reg_1587 <= sext_ln27_33_fu_888_p1[32'd9];
        tmp_19_reg_1597 <= sext_ln27_36_fu_923_p1[32'd9];
        trunc_ln27_1_reg_1582 <= trunc_ln27_1_fu_892_p1;
        trunc_ln27_4_reg_1592 <= trunc_ln27_4_fu_927_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        trunc_ln16_reg_1652 <= {{add_ln60_fu_1003_p2[7:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        val_div_load_1_reg_1503 <= val_div_q0;
        val_div_load_reg_1498 <= val_div_q1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state58) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44))) begin
        val_div_ce0_local = 1'b1;
    end else begin
        val_div_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44))) begin
        val_div_ce1_local = 1'b1;
    end else begin
        val_div_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln21_2_fu_368_p2 = ($signed(trunc_ln21_2_reg_1079) + $signed(11'd2027));

assign add_ln21_4_fu_330_p2 = ($signed(sub_ln21_4_reg_1103) + $signed(12'd4076));

assign add_ln21_5_fu_392_p2 = ($signed(trunc_ln21_9_reg_1110) + $signed(11'd2027));

assign add_ln21_fu_306_p2 = ($signed(sub_ln21_1_reg_1072) + $signed(12'd4076));

assign add_ln22_1_fu_708_p2 = (trunc_ln22_1_reg_1446 + 4'd1);

assign add_ln22_fu_703_p2 = (trunc_ln_reg_1429 + 4'd1);

assign add_ln27_12_fu_864_p2 = (tmp_2_reg_1550 + 9'd1);

assign add_ln27_fu_859_p2 = (tmp_1_reg_1533 + 9'd1);

assign add_ln60_fu_1003_p2 = (zext_ln60_fu_995_p1 + zext_ln60_1_fu_999_p1);

assign and_ln21_1_fu_555_p2 = (xor_ln21_1_fu_549_p2 & icmp_ln21_1_reg_1128);

assign and_ln21_2_fu_571_p2 = (xor_ln21_2_fu_566_p2 & icmp_ln21_8_reg_1188);

assign and_ln21_3_fu_586_p2 = (xor_ln21_3_fu_580_p2 & icmp_ln21_7_reg_1167);

assign and_ln21_fu_540_p2 = (xor_ln21_fu_535_p2 & icmp_ln21_2_reg_1149);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_return = (trunc_ln16_reg_1652 + 7'd3);

assign bitcast_ln716_1_fu_236_p1 = pf_1_reg_1049;

assign bitcast_ln716_fu_171_p1 = pf_reg_1044;

assign cond64_i176_fu_474_p3 = ((icmp_ln21_10_reg_1244[0:0] == 1'b1) ? tmp_14_reg_1090 : tmp_15_reg_1279);

assign cond64_i_fu_451_p3 = ((icmp_ln21_4_reg_1214[0:0] == 1'b1) ? tmp_reg_1059 : tmp_10_reg_1274);

assign distance_1_fu_939_p3 = ((tmp_13_reg_1587[0:0] == 1'b1) ? 8'd0 : trunc_ln27_1_reg_1582);

assign distance_3_fu_916_p3 = ((tmp_18_fu_904_p3[0:0] == 1'b1) ? select_ln27_1_fu_911_p3 : tmp_2_reg_1550);

assign distance_4_fu_949_p3 = ((tmp_19_reg_1597[0:0] == 1'b1) ? 8'd0 : trunc_ln27_4_reg_1592);

assign distance_6_fu_969_p3 = ((icmp_ln31_reg_1622[0:0] == 1'b1) ? 7'd87 : trunc_ln27_2_reg_1607);

assign distance_7_fu_975_p3 = ((icmp_ln31_1_reg_1627[0:0] == 1'b1) ? 7'd87 : trunc_ln27_5_reg_1617);

assign distance_fu_881_p3 = ((tmp_12_fu_869_p3[0:0] == 1'b1) ? select_ln27_fu_876_p3 : tmp_1_reg_1533);

assign grp_fu_147_p0 = $signed(peakCoordinates_2);

assign grp_fu_150_p0 = $signed(peakCoordinates_3);

assign grp_fu_214_p1 = zext_ln21_1_cast_fu_202_p3;

assign grp_fu_220_p0 = bitcast_ln716_fu_171_p1[62:0];

assign grp_fu_279_p1 = zext_ln21_9_cast_fu_267_p3;

assign grp_fu_285_p0 = bitcast_ln716_1_fu_236_p1[62:0];

assign grp_fu_400_p1 = select_ln21_1_reg_1200;

assign grp_fu_408_p2 = add_ln21_2_reg_1219;

assign grp_fu_418_p1 = select_ln21_5_reg_1230;

assign grp_fu_426_p2 = add_ln21_5_reg_1249;

assign grp_fu_446_p1 = select_ln21_1_reg_1200;

assign grp_fu_469_p1 = select_ln21_5_reg_1230;

assign grp_fu_516_p1 = cond64_i_reg_1299;

assign grp_fu_524_p1 = cond64_i176_reg_1319;

assign grp_fu_650_p1 = 32'd100;

assign grp_fu_659_p1 = 32'd100;

assign grp_fu_790_p0 = $signed(peak_fu_775_p3);

assign grp_fu_790_p1 = $signed(val_div_load_reg_1498);

assign grp_fu_815_p0 = $signed(peak_1_fu_800_p3);

assign grp_fu_815_p1 = $signed(val_div_load_1_reg_1503);

assign icmp_ln21_10_fu_387_p2 = (($signed(add_ln21_4_reg_1173) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln21_11_fu_461_p2 = ((select_ln21_5_reg_1230 < 11'd24) ? 1'b1 : 1'b0);

assign icmp_ln21_1_fu_301_p2 = (($signed(sub_ln21_1_reg_1072) > $signed(12'd20)) ? 1'b1 : 1'b0);

assign icmp_ln21_2_fu_320_p2 = ((sub_ln21_1_reg_1072 == 12'd20) ? 1'b1 : 1'b0);

assign icmp_ln21_3_fu_433_p2 = ((select_ln21_1_reg_1200 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln21_4_fu_363_p2 = (($signed(add_ln21_reg_1134) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign icmp_ln21_5_fu_438_p2 = ((select_ln21_1_reg_1200 < 11'd24) ? 1'b1 : 1'b0);

assign icmp_ln21_7_fu_325_p2 = (($signed(sub_ln21_4_reg_1103) > $signed(12'd20)) ? 1'b1 : 1'b0);

assign icmp_ln21_8_fu_344_p2 = ((sub_ln21_4_reg_1103 == 12'd20) ? 1'b1 : 1'b0);

assign icmp_ln21_9_fu_456_p2 = ((select_ln21_5_reg_1230 < 11'd54) ? 1'b1 : 1'b0);

assign icmp_ln31_1_fu_964_p2 = ((distance_4_reg_1612 > 8'd87) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_959_p2 = ((distance_1_reg_1602 > 8'd87) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_981_p2 = ((distance_7_reg_1639 > distance_6_reg_1632) ? 1'b1 : 1'b0);

assign ind_1_fu_757_p2 = (the_int_1_fu_750_p3 + 4'd5);

assign ind_fu_732_p2 = (the_int_fu_725_p3 + 4'd5);

assign or_ln21_1_fu_576_p2 = (icmp_ln21_8_reg_1188 | icmp_ln21_6_reg_1160);

assign or_ln21_fu_545_p2 = (icmp_ln21_reg_1121 | icmp_ln21_2_reg_1149);

assign outData_2_fu_985_p3 = ((icmp_ln41_reg_1646[0:0] == 1'b1) ? distance_6_reg_1632 : distance_7_reg_1639);

assign outData_fu_990_p3 = ((icmp_ln41_reg_1646[0:0] == 1'b1) ? distance_7_reg_1639 : distance_6_reg_1632);

assign peak_1_fu_800_p3 = {{peakCoordinates_1}, {20'd0}};

assign peak_fu_775_p3 = {{peakCoordinates_0}, {20'd0}};

assign select_ln21_1_fu_354_p3 = ((icmp_ln21_1_reg_1128[0:0] == 1'b1) ? trunc_ln21_3_reg_1139 : sub_ln21_2_reg_1144);

assign select_ln21_2_fu_489_p3 = ((icmp_ln21_3_reg_1284[0:0] == 1'b1) ? trunc_ln21_5_fu_486_p1 : select_ln21_8_fu_479_p3);

assign select_ln21_3_fu_529_p3 = ((icmp_ln21_5_reg_1289[0:0] == 1'b1) ? shl_ln21_reg_1344 : 24'd0);

assign select_ln21_4_fu_373_p3 = ((tmp_14_reg_1090[0:0] == 1'b1) ? sub_ln21_3_reg_1155 : zext_ln21_9_reg_1097);

assign select_ln21_5_fu_378_p3 = ((icmp_ln21_7_reg_1167[0:0] == 1'b1) ? trunc_ln21_10_reg_1178 : sub_ln21_5_reg_1183);

assign select_ln21_6_fu_506_p3 = ((icmp_ln21_9_reg_1304[0:0] == 1'b1) ? trunc_ln21_12_fu_503_p1 : select_ln21_9_fu_496_p3);

assign select_ln21_7_fu_560_p3 = ((icmp_ln21_11_reg_1309[0:0] == 1'b1) ? shl_ln21_1_reg_1354 : 24'd0);

assign select_ln21_8_fu_479_p3 = ((tmp_reg_1059[0:0] == 1'b1) ? 24'd16777215 : 24'd0);

assign select_ln21_9_fu_496_p3 = ((tmp_14_reg_1090[0:0] == 1'b1) ? 24'd16777215 : 24'd0);

assign select_ln21_fu_349_p3 = ((tmp_reg_1059[0:0] == 1'b1) ? sub_ln21_reg_1116 : zext_ln21_1_reg_1066);

assign select_ln22_1_fu_745_p3 = ((icmp_ln22_1_reg_1468[0:0] == 1'b1) ? add_ln22_1_reg_1473 : trunc_ln22_1_reg_1446);

assign select_ln22_fu_720_p3 = ((icmp_ln22_reg_1458[0:0] == 1'b1) ? add_ln22_reg_1463 : trunc_ln_reg_1429);

assign select_ln27_1_fu_911_p3 = ((icmp_ln27_1_reg_1572[0:0] == 1'b1) ? add_ln27_12_reg_1577 : tmp_2_reg_1550);

assign select_ln27_fu_876_p3 = ((icmp_ln27_reg_1562[0:0] == 1'b1) ? add_ln27_reg_1567 : tmp_1_reg_1533);

assign sext_ln27_33_fu_888_p1 = distance_fu_881_p3;

assign sext_ln27_36_fu_923_p1 = distance_3_fu_916_p3;

assign sub_ln21_1_fu_226_p2 = (12'd1075 - zext_ln21_fu_194_p1);

assign sub_ln21_2_fu_315_p2 = (11'd20 - trunc_ln21_2_reg_1079);

assign sub_ln21_4_fu_291_p2 = (12'd1075 - zext_ln21_5_fu_259_p1);

assign sub_ln21_5_fu_339_p2 = (11'd20 - trunc_ln21_9_reg_1110);

assign the_int_1_fu_750_p3 = ((tmp_16_fu_738_p3[0:0] == 1'b1) ? select_ln22_1_fu_745_p3 : trunc_ln22_1_reg_1446);

assign the_int_fu_725_p3 = ((tmp_11_fu_713_p3[0:0] == 1'b1) ? select_ln22_fu_720_p3 : trunc_ln_reg_1429);

assign theta_1_fu_626_p10 = {{{icmp_ln21_6_reg_1160}, {and_ln21_2_reg_1394}}, {and_ln21_3_reg_1399}};

assign theta_1_fu_626_p9 = 'bx;

assign theta_fu_598_p10 = {{{icmp_ln21_reg_1121}, {and_ln21_reg_1374}}, {and_ln21_1_reg_1379}};

assign theta_fu_598_p9 = 'bx;

assign tmp_11_fu_713_p3 = mul_ln22_reg_1424[32'd31];

assign tmp_12_fu_869_p3 = sub_ln27_reg_1528[32'd28];

assign tmp_16_fu_738_p3 = mul_ln22_1_reg_1441[32'd31];

assign tmp_17_fu_251_p3 = {{bitcast_ln716_1_fu_236_p1[62:52]}};

assign tmp_18_fu_904_p3 = sub_ln27_1_reg_1545[32'd28];

assign tmp_s_fu_186_p3 = {{bitcast_ln716_fu_171_p1[62:52]}};

assign trunc_ln21_10_fu_335_p1 = add_ln21_4_fu_330_p2[10:0];

assign trunc_ln21_11_fu_383_p1 = select_ln21_4_fu_373_p3[23:0];

assign trunc_ln21_12_fu_503_p1 = ashr_ln21_1_reg_1329[23:0];

assign trunc_ln21_1_fu_198_p1 = bitcast_ln716_fu_171_p1[51:0];

assign trunc_ln21_2_fu_232_p1 = sub_ln21_1_fu_226_p2[10:0];

assign trunc_ln21_3_fu_311_p1 = add_ln21_fu_306_p2[10:0];

assign trunc_ln21_4_fu_359_p1 = select_ln21_fu_349_p3[23:0];

assign trunc_ln21_5_fu_486_p1 = ashr_ln21_reg_1324[23:0];

assign trunc_ln21_8_fu_263_p1 = bitcast_ln716_1_fu_236_p1[51:0];

assign trunc_ln21_9_fu_297_p1 = sub_ln21_4_fu_291_p2[10:0];

assign trunc_ln22_2_fu_689_p1 = grp_fu_659_p2[19:0];

assign trunc_ln22_fu_675_p1 = grp_fu_650_p2[19:0];

assign trunc_ln27_1_fu_892_p1 = distance_fu_881_p3[7:0];

assign trunc_ln27_2_fu_945_p1 = distance_1_fu_939_p3[6:0];

assign trunc_ln27_3_fu_845_p1 = grp_fu_815_p2[19:0];

assign trunc_ln27_4_fu_927_p1 = distance_3_fu_916_p3[7:0];

assign trunc_ln27_5_fu_955_p1 = distance_4_fu_949_p3[6:0];

assign trunc_ln27_fu_831_p1 = grp_fu_790_p2[19:0];

assign val_div_address0 = zext_ln27_2_fu_767_p1;

assign val_div_address1 = zext_ln27_fu_763_p1;

assign xor_ln21_1_fu_549_p2 = (or_ln21_fu_545_p2 ^ 1'd1);

assign xor_ln21_2_fu_566_p2 = (icmp_ln21_6_reg_1160 ^ 1'd1);

assign xor_ln21_3_fu_580_p2 = (or_ln21_1_fu_576_p2 ^ 1'd1);

assign xor_ln21_fu_535_p2 = (icmp_ln21_reg_1121 ^ 1'd1);

assign zext_ln21_1_cast_fu_202_p3 = {{1'd1}, {trunc_ln21_1_fu_198_p1}};

assign zext_ln21_1_fu_210_p1 = zext_ln21_1_cast_fu_202_p3;

assign zext_ln21_5_fu_259_p1 = tmp_17_fu_251_p3;

assign zext_ln21_9_cast_fu_267_p3 = {{1'd1}, {trunc_ln21_8_fu_263_p1}};

assign zext_ln21_9_fu_275_p1 = zext_ln21_9_cast_fu_267_p3;

assign zext_ln21_fu_194_p1 = tmp_s_fu_186_p3;

assign zext_ln27_2_fu_767_p1 = ind_1_reg_1483;

assign zext_ln27_fu_763_p1 = ind_reg_1478;

assign zext_ln60_1_fu_999_p1 = outData_fu_990_p3;

assign zext_ln60_fu_995_p1 = outData_2_fu_985_p3;

always @ (posedge ap_clk) begin
    zext_ln21_1_reg_1066[53:52] <= 2'b01;
    zext_ln21_9_reg_1097[53:52] <= 2'b01;
end

endmodule //top_module_elaboration_data
