// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_module_gaussian (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        y,
        img_ga_0_address0,
        img_ga_0_ce0,
        img_ga_0_we0,
        img_ga_0_d0,
        img_ga_1_address0,
        img_ga_1_ce0,
        img_ga_1_we0,
        img_ga_1_d0,
        img_ga_2_address0,
        img_ga_2_ce0,
        img_ga_2_we0,
        img_ga_2_d0,
        img_ga_3_address0,
        img_ga_3_ce0,
        img_ga_3_we0,
        img_ga_3_d0,
        img_in0_0_address0,
        img_in0_0_ce0,
        img_in0_0_q0,
        img_in0_0_address1,
        img_in0_0_ce1,
        img_in0_0_q1,
        img_in0_1_address0,
        img_in0_1_ce0,
        img_in0_1_q0,
        img_in0_1_address1,
        img_in0_1_ce1,
        img_in0_1_q1,
        img_in0_2_address0,
        img_in0_2_ce0,
        img_in0_2_q0,
        img_in0_3_address0,
        img_in0_3_ce0,
        img_in0_3_q0,
        img_in1_0_address0,
        img_in1_0_ce0,
        img_in1_0_q0,
        img_in1_0_address1,
        img_in1_0_ce1,
        img_in1_0_q1,
        img_in1_1_address0,
        img_in1_1_ce0,
        img_in1_1_q0,
        img_in1_1_address1,
        img_in1_1_ce1,
        img_in1_1_q1,
        img_in1_2_address0,
        img_in1_2_ce0,
        img_in1_2_q0,
        img_in1_3_address0,
        img_in1_3_ce0,
        img_in1_3_q0,
        img_in2_0_address0,
        img_in2_0_ce0,
        img_in2_0_q0,
        img_in2_0_address1,
        img_in2_0_ce1,
        img_in2_0_q1,
        img_in2_1_address0,
        img_in2_1_ce0,
        img_in2_1_q0,
        img_in2_1_address1,
        img_in2_1_ce1,
        img_in2_1_q1,
        img_in2_2_address0,
        img_in2_2_ce0,
        img_in2_2_q0,
        img_in2_3_address0,
        img_in2_3_ce0,
        img_in2_3_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state15 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] y;
output  [4:0] img_ga_0_address0;
output   img_ga_0_ce0;
output   img_ga_0_we0;
output  [7:0] img_ga_0_d0;
output  [4:0] img_ga_1_address0;
output   img_ga_1_ce0;
output   img_ga_1_we0;
output  [7:0] img_ga_1_d0;
output  [4:0] img_ga_2_address0;
output   img_ga_2_ce0;
output   img_ga_2_we0;
output  [7:0] img_ga_2_d0;
output  [4:0] img_ga_3_address0;
output   img_ga_3_ce0;
output   img_ga_3_we0;
output  [7:0] img_ga_3_d0;
output  [4:0] img_in0_0_address0;
output   img_in0_0_ce0;
input  [7:0] img_in0_0_q0;
output  [4:0] img_in0_0_address1;
output   img_in0_0_ce1;
input  [7:0] img_in0_0_q1;
output  [4:0] img_in0_1_address0;
output   img_in0_1_ce0;
input  [7:0] img_in0_1_q0;
output  [4:0] img_in0_1_address1;
output   img_in0_1_ce1;
input  [7:0] img_in0_1_q1;
output  [4:0] img_in0_2_address0;
output   img_in0_2_ce0;
input  [7:0] img_in0_2_q0;
output  [4:0] img_in0_3_address0;
output   img_in0_3_ce0;
input  [7:0] img_in0_3_q0;
output  [4:0] img_in1_0_address0;
output   img_in1_0_ce0;
input  [7:0] img_in1_0_q0;
output  [4:0] img_in1_0_address1;
output   img_in1_0_ce1;
input  [7:0] img_in1_0_q1;
output  [4:0] img_in1_1_address0;
output   img_in1_1_ce0;
input  [7:0] img_in1_1_q0;
output  [4:0] img_in1_1_address1;
output   img_in1_1_ce1;
input  [7:0] img_in1_1_q1;
output  [4:0] img_in1_2_address0;
output   img_in1_2_ce0;
input  [7:0] img_in1_2_q0;
output  [4:0] img_in1_3_address0;
output   img_in1_3_ce0;
input  [7:0] img_in1_3_q0;
output  [4:0] img_in2_0_address0;
output   img_in2_0_ce0;
input  [7:0] img_in2_0_q0;
output  [4:0] img_in2_0_address1;
output   img_in2_0_ce1;
input  [7:0] img_in2_0_q1;
output  [4:0] img_in2_1_address0;
output   img_in2_1_ce0;
input  [7:0] img_in2_1_q0;
output  [4:0] img_in2_1_address1;
output   img_in2_1_ce1;
input  [7:0] img_in2_1_q1;
output  [4:0] img_in2_2_address0;
output   img_in2_2_ce0;
input  [7:0] img_in2_2_q0;
output  [4:0] img_in2_3_address0;
output   img_in2_3_ce0;
input  [7:0] img_in2_3_q0;
output  [7:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [6:0] x_reg_376;
reg   [7:0] y_read_reg_1131;
reg    ap_block_state1;
reg   [6:0] tmp_reg_1135;
wire   [0:0] icmp_ln6_fu_397_p2;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln8_fu_412_p1;
reg   [63:0] zext_ln8_reg_1144;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0_11001;
reg   [63:0] zext_ln8_reg_1144_pp0_iter1_reg;
reg   [63:0] zext_ln8_reg_1144_pp0_iter2_reg;
reg   [63:0] zext_ln8_reg_1144_pp0_iter3_reg;
reg   [63:0] zext_ln8_reg_1144_pp0_iter4_reg;
reg   [63:0] zext_ln8_reg_1144_pp0_iter5_reg;
reg   [63:0] zext_ln8_reg_1144_pp0_iter6_reg;
reg   [63:0] zext_ln8_reg_1144_pp0_iter7_reg;
reg   [63:0] zext_ln8_reg_1144_pp0_iter8_reg;
wire   [0:0] icmp_ln8_fu_430_p2;
reg   [0:0] icmp_ln8_reg_1188;
reg   [0:0] icmp_ln8_reg_1188_pp0_iter1_reg;
reg   [0:0] icmp_ln8_reg_1188_pp0_iter2_reg;
reg   [0:0] icmp_ln8_reg_1188_pp0_iter3_reg;
reg   [0:0] icmp_ln8_reg_1188_pp0_iter4_reg;
reg   [0:0] icmp_ln8_reg_1188_pp0_iter5_reg;
reg   [0:0] icmp_ln8_reg_1188_pp0_iter6_reg;
reg   [0:0] icmp_ln8_reg_1188_pp0_iter7_reg;
reg   [0:0] icmp_ln8_reg_1188_pp0_iter8_reg;
reg   [4:0] lshr_ln25_7_reg_1192;
reg   [4:0] lshr_ln25_7_reg_1192_pp0_iter1_reg;
reg   [4:0] lshr_ln25_s_reg_1197;
reg   [4:0] lshr_ln25_s_reg_1197_pp0_iter1_reg;
wire   [6:0] add_ln8_fu_468_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [63:0] zext_ln25_1_fu_480_p1;
reg   [63:0] zext_ln25_1_reg_1252;
reg   [3:0] trunc_ln_reg_1267;
reg   [4:0] trunc_ln25_1_reg_1272;
reg   [4:0] trunc_ln25_1_reg_1272_pp0_iter4_reg;
reg   [3:0] trunc_ln25_2_reg_1277;
reg   [3:0] trunc_ln27_2_reg_1282;
reg   [3:0] trunc_ln25_3_reg_1287;
reg   [4:0] trunc_ln25_4_reg_1292;
reg   [3:0] trunc_ln25_5_reg_1297;
reg   [4:0] trunc_ln27_4_reg_1302;
reg   [4:0] trunc_ln27_4_reg_1302_pp0_iter4_reg;
reg   [3:0] trunc_ln27_5_reg_1307;
reg   [4:0] trunc_ln25_6_reg_1312;
reg   [4:0] trunc_ln25_6_reg_1312_pp0_iter4_reg;
reg   [4:0] trunc_ln25_6_reg_1312_pp0_iter5_reg;
reg   [4:0] trunc_ln27_6_reg_1317;
reg   [4:0] trunc_ln27_6_reg_1317_pp0_iter4_reg;
reg   [5:0] trunc_ln26_1_reg_1327;
reg  signed [4:0] trunc_ln26_2_reg_1332;
reg   [4:0] trunc_ln27_1_reg_1338;
reg   [4:0] trunc_ln27_1_reg_1338_pp0_iter5_reg;
reg   [4:0] trunc_ln27_1_reg_1338_pp0_iter6_reg;
wire   [4:0] add_ln27_fu_631_p2;
reg   [4:0] add_ln27_reg_1343;
wire  signed [4:0] sext_ln25_1_fu_637_p1;
reg  signed [4:0] sext_ln25_1_reg_1348;
reg  signed [4:0] sext_ln25_1_reg_1348_pp0_iter5_reg;
reg   [4:0] trunc_ln26_3_reg_1353;
reg   [5:0] trunc_ln26_4_reg_1358;
reg   [4:0] trunc_ln26_5_reg_1363;
reg   [3:0] trunc_ln27_3_reg_1368;
wire   [5:0] add_ln27_5_fu_689_p2;
reg   [5:0] add_ln27_5_reg_1373;
wire  signed [4:0] add_ln25_14_fu_698_p2;
reg  signed [4:0] add_ln25_14_reg_1378;
reg  signed [4:0] add_ln25_14_reg_1378_pp0_iter5_reg;
reg   [5:0] trunc_ln26_6_reg_1384;
wire   [4:0] add_ln27_7_fu_714_p2;
reg   [4:0] add_ln27_7_reg_1389;
reg   [4:0] trunc_ln14_reg_1394;
reg   [3:0] trunc_ln15_reg_1399;
wire   [5:0] add_ln27_3_fu_746_p2;
reg   [5:0] add_ln27_3_reg_1404;
wire   [6:0] add_ln25_fu_758_p2;
reg   [6:0] add_ln25_reg_1409;
reg   [6:0] add_ln25_reg_1409_pp0_iter6_reg;
wire   [6:0] add_ln27_6_fu_773_p2;
reg   [6:0] add_ln27_6_reg_1414;
wire   [6:0] add_ln25_11_fu_788_p2;
reg   [6:0] add_ln25_11_reg_1419;
wire   [5:0] add_ln25_13_fu_794_p2;
reg   [5:0] add_ln25_13_reg_1424;
reg   [3:0] trunc_ln25_7_reg_1429;
reg   [4:0] trunc_ln26_7_reg_1434;
reg   [4:0] trunc_ln26_7_reg_1434_pp0_iter6_reg;
wire   [5:0] add_ln27_8_fu_826_p2;
reg   [5:0] add_ln27_8_reg_1439;
reg   [3:0] trunc_ln27_7_reg_1444;
wire   [6:0] add_ln25_16_fu_848_p2;
reg   [6:0] add_ln25_16_reg_1449;
reg   [6:0] add_ln25_16_reg_1449_pp0_iter6_reg;
reg   [4:0] trunc_ln25_8_reg_1454;
reg   [3:0] trunc_ln25_9_reg_1459;
reg   [5:0] trunc_ln26_8_reg_1464;
reg   [4:0] trunc_ln27_8_reg_1469;
wire   [5:0] add_ln27_10_fu_897_p2;
reg   [5:0] add_ln27_10_reg_1474;
reg   [3:0] trunc_ln27_9_reg_1479;
wire   [6:0] add_ln27_4_fu_919_p2;
reg   [6:0] add_ln27_4_reg_1484;
wire   [4:0] add_ln25_6_fu_928_p2;
reg   [4:0] add_ln25_6_reg_1489;
wire   [7:0] add_ln25_12_fu_939_p2;
reg   [7:0] add_ln25_12_reg_1494;
wire   [6:0] add_ln25_15_fu_951_p2;
reg   [6:0] add_ln25_15_reg_1499;
wire   [6:0] add_ln27_9_fu_966_p2;
reg   [6:0] add_ln27_9_reg_1504;
wire   [4:0] add_ln25_18_fu_975_p2;
reg   [4:0] add_ln25_18_reg_1509;
reg   [4:0] trunc_ln26_9_reg_1514;
wire   [6:0] add_ln27_11_fu_1003_p2;
reg   [6:0] add_ln27_11_reg_1519;
wire   [6:0] add_ln25_20_fu_1015_p2;
reg   [6:0] add_ln25_20_reg_1524;
wire   [4:0] add_ln25_22_fu_1021_p2;
reg   [4:0] add_ln25_22_reg_1529;
wire   [7:0] add_ln25_3_fu_1036_p2;
reg   [7:0] add_ln25_3_reg_1534;
wire   [5:0] add_ln25_9_fu_1045_p2;
reg   [5:0] add_ln25_9_reg_1539;
wire   [7:0] add_ln25_4_fu_1054_p2;
reg   [7:0] add_ln25_4_reg_1544;
wire   [7:0] add_ln25_17_fu_1068_p2;
reg   [7:0] add_ln25_17_reg_1549;
wire   [5:0] add_ln25_19_fu_1077_p2;
reg   [5:0] add_ln25_19_reg_1554;
wire   [7:0] add_ln25_21_fu_1092_p2;
reg   [7:0] add_ln25_21_reg_1559;
wire   [5:0] add_ln25_23_fu_1101_p2;
reg   [5:0] add_ln25_23_reg_1564;
wire   [7:0] add_ln25_2_fu_1110_p2;
reg   [7:0] add_ln25_2_reg_1569;
wire   [7:0] add_ln25_7_fu_1118_p2;
reg   [7:0] add_ln25_7_reg_1579;
wire   [7:0] add_ln25_10_fu_1126_p2;
reg   [7:0] add_ln25_10_reg_1584;
wire    ap_CS_fsm_state3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln25_fu_474_p1;
reg    img_in0_0_ce1_local;
reg    img_in0_0_ce0_local;
reg    img_in0_1_ce1_local;
reg    img_in0_1_ce0_local;
reg    img_in0_2_ce0_local;
reg    img_in2_2_ce0_local;
reg    img_in0_3_ce0_local;
reg    img_in2_3_ce0_local;
reg    img_in1_1_ce1_local;
reg    img_in1_1_ce0_local;
reg    img_in1_2_ce0_local;
reg    img_in2_1_ce1_local;
reg    img_in2_1_ce0_local;
reg    img_in1_3_ce0_local;
reg    img_in1_0_ce1_local;
reg    img_in1_0_ce0_local;
reg    img_in2_0_ce1_local;
reg    img_in2_0_ce0_local;
reg    img_ga_1_we0_local;
reg    img_ga_1_ce0_local;
reg    img_ga_0_we0_local;
reg    img_ga_0_ce0_local;
reg    img_ga_2_we0_local;
reg    img_ga_2_ce0_local;
reg    img_ga_3_we0_local;
reg    img_ga_3_ce0_local;
wire   [4:0] lshr_ln8_fu_402_p4;
wire   [6:0] or_ln8_fu_422_p3;
wire   [6:0] add_ln25_5_fu_436_p2;
wire   [6:0] add_ln25_8_fu_452_p2;
wire  signed [4:0] sext_ln25_fu_595_p1;
wire  signed [4:0] sext_ln26_fu_598_p1;
wire  signed [5:0] sext_ln27_10_fu_686_p1;
wire  signed [5:0] sext_ln25_2_fu_640_p1;
wire  signed [4:0] sext_ln26_1_fu_643_p1;
wire  signed [4:0] sext_ln25_6_fu_695_p1;
wire  signed [5:0] sext_ln27_3_fu_743_p1;
wire  signed [5:0] sext_ln27_fu_740_p1;
wire  signed [6:0] sext_ln27_5_fu_752_p1;
wire  signed [6:0] sext_ln27_7_fu_755_p1;
wire  signed [6:0] sext_ln27_12_fu_767_p1;
wire  signed [6:0] sext_ln27_11_fu_764_p1;
wire  signed [6:0] sext_ln27_13_fu_770_p1;
wire  signed [6:0] sext_ln27_16_fu_782_p1;
wire  signed [5:0] sext_ln27_17_fu_785_p1;
wire  signed [5:0] sext_ln27_15_fu_779_p1;
wire  signed [5:0] sext_ln27_19_fu_823_p1;
wire  signed [5:0] sext_ln27_6_fu_800_p1;
wire  signed [6:0] sext_ln27_21_fu_832_p1;
wire  signed [6:0] sext_ln27_23_fu_835_p1;
wire  signed [5:0] sext_ln27_26_fu_894_p1;
wire  signed [6:0] sext_ln27_2_fu_916_p1;
wire  signed [6:0] sext_ln27_1_fu_913_p1;
wire  signed [4:0] sext_ln27_8_fu_925_p1;
wire  signed [7:0] sext_ln25_7_fu_936_p1;
wire  signed [7:0] sext_ln27_14_fu_933_p1;
wire  signed [6:0] sext_ln25_9_fu_948_p1;
wire  signed [6:0] sext_ln25_8_fu_945_p1;
wire  signed [6:0] sext_ln27_20_fu_963_p1;
wire  signed [6:0] sext_ln27_18_fu_960_p1;
wire  signed [4:0] sext_ln26_2_fu_957_p1;
wire  signed [4:0] sext_ln25_11_fu_972_p1;
wire  signed [6:0] sext_ln27_27_fu_997_p1;
wire  signed [6:0] sext_ln27_25_fu_994_p1;
wire  signed [6:0] sext_ln27_28_fu_1000_p1;
wire  signed [6:0] sext_ln27_30_fu_1009_p1;
wire  signed [4:0] sext_ln26_3_fu_981_p1;
wire  signed [4:0] sext_ln25_15_fu_1012_p1;
wire  signed [7:0] sext_ln25_3_fu_1033_p1;
wire  signed [7:0] sext_ln27_4_fu_1027_p1;
wire  signed [5:0] sext_ln25_4_fu_1042_p1;
wire  signed [5:0] sext_ln27_9_fu_1030_p1;
wire  signed [7:0] sext_ln25_10_fu_1051_p1;
wire  signed [7:0] sext_ln25_12_fu_1065_p1;
wire  signed [7:0] sext_ln27_22_fu_1059_p1;
wire  signed [5:0] sext_ln25_13_fu_1074_p1;
wire  signed [5:0] sext_ln27_24_fu_1062_p1;
wire  signed [7:0] sext_ln25_16_fu_1089_p1;
wire  signed [7:0] sext_ln27_29_fu_1083_p1;
wire  signed [5:0] sext_ln25_17_fu_1098_p1;
wire  signed [5:0] sext_ln27_31_fu_1086_p1;
wire  signed [7:0] sext_ln25_5_fu_1107_p1;
wire  signed [7:0] sext_ln25_14_fu_1115_p1;
wire  signed [7:0] sext_ln25_18_fu_1123_p1;
wire    ap_CS_fsm_state15;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state15)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter10 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_reg_376 <= 7'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln8_fu_430_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_reg_376 <= add_ln8_fu_468_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln25_10_reg_1584 <= add_ln25_10_fu_1126_p2;
        add_ln25_11_reg_1419 <= add_ln25_11_fu_788_p2;
        add_ln25_12_reg_1494 <= add_ln25_12_fu_939_p2;
        add_ln25_13_reg_1424 <= add_ln25_13_fu_794_p2;
        add_ln25_14_reg_1378 <= add_ln25_14_fu_698_p2;
        add_ln25_14_reg_1378_pp0_iter5_reg <= add_ln25_14_reg_1378;
        add_ln25_15_reg_1499 <= add_ln25_15_fu_951_p2;
        add_ln25_16_reg_1449 <= add_ln25_16_fu_848_p2;
        add_ln25_16_reg_1449_pp0_iter6_reg <= add_ln25_16_reg_1449;
        add_ln25_17_reg_1549 <= add_ln25_17_fu_1068_p2;
        add_ln25_18_reg_1509 <= add_ln25_18_fu_975_p2;
        add_ln25_19_reg_1554 <= add_ln25_19_fu_1077_p2;
        add_ln25_20_reg_1524 <= add_ln25_20_fu_1015_p2;
        add_ln25_21_reg_1559 <= add_ln25_21_fu_1092_p2;
        add_ln25_22_reg_1529 <= add_ln25_22_fu_1021_p2;
        add_ln25_23_reg_1564 <= add_ln25_23_fu_1101_p2;
        add_ln25_2_reg_1569 <= add_ln25_2_fu_1110_p2;
        add_ln25_3_reg_1534 <= add_ln25_3_fu_1036_p2;
        add_ln25_4_reg_1544 <= add_ln25_4_fu_1054_p2;
        add_ln25_6_reg_1489 <= add_ln25_6_fu_928_p2;
        add_ln25_7_reg_1579 <= add_ln25_7_fu_1118_p2;
        add_ln25_9_reg_1539 <= add_ln25_9_fu_1045_p2;
        add_ln25_reg_1409 <= add_ln25_fu_758_p2;
        add_ln25_reg_1409_pp0_iter6_reg <= add_ln25_reg_1409;
        add_ln27_10_reg_1474 <= add_ln27_10_fu_897_p2;
        add_ln27_11_reg_1519 <= add_ln27_11_fu_1003_p2;
        add_ln27_3_reg_1404 <= add_ln27_3_fu_746_p2;
        add_ln27_4_reg_1484 <= add_ln27_4_fu_919_p2;
        add_ln27_5_reg_1373 <= add_ln27_5_fu_689_p2;
        add_ln27_6_reg_1414 <= add_ln27_6_fu_773_p2;
        add_ln27_7_reg_1389 <= add_ln27_7_fu_714_p2;
        add_ln27_8_reg_1439 <= add_ln27_8_fu_826_p2;
        add_ln27_9_reg_1504 <= add_ln27_9_fu_966_p2;
        add_ln27_reg_1343 <= add_ln27_fu_631_p2;
        icmp_ln8_reg_1188_pp0_iter2_reg <= icmp_ln8_reg_1188_pp0_iter1_reg;
        icmp_ln8_reg_1188_pp0_iter3_reg <= icmp_ln8_reg_1188_pp0_iter2_reg;
        icmp_ln8_reg_1188_pp0_iter4_reg <= icmp_ln8_reg_1188_pp0_iter3_reg;
        icmp_ln8_reg_1188_pp0_iter5_reg <= icmp_ln8_reg_1188_pp0_iter4_reg;
        icmp_ln8_reg_1188_pp0_iter6_reg <= icmp_ln8_reg_1188_pp0_iter5_reg;
        icmp_ln8_reg_1188_pp0_iter7_reg <= icmp_ln8_reg_1188_pp0_iter6_reg;
        icmp_ln8_reg_1188_pp0_iter8_reg <= icmp_ln8_reg_1188_pp0_iter7_reg;
        sext_ln25_1_reg_1348 <= sext_ln25_1_fu_637_p1;
        sext_ln25_1_reg_1348_pp0_iter5_reg <= sext_ln25_1_reg_1348;
        trunc_ln14_reg_1394 <= {{img_in1_0_q1[7:3]}};
        trunc_ln15_reg_1399 <= {{img_in2_0_q1[7:4]}};
        trunc_ln25_1_reg_1272 <= {{img_in0_1_q1[7:3]}};
        trunc_ln25_1_reg_1272_pp0_iter4_reg <= trunc_ln25_1_reg_1272;
        trunc_ln25_2_reg_1277 <= {{img_in0_2_q0[7:4]}};
        trunc_ln25_3_reg_1287 <= {{img_in0_1_q1[7:4]}};
        trunc_ln25_4_reg_1292 <= {{img_in0_2_q0[7:3]}};
        trunc_ln25_5_reg_1297 <= {{img_in0_3_q0[7:4]}};
        trunc_ln25_6_reg_1312 <= {{img_in0_3_q0[7:3]}};
        trunc_ln25_6_reg_1312_pp0_iter4_reg <= trunc_ln25_6_reg_1312;
        trunc_ln25_6_reg_1312_pp0_iter5_reg <= trunc_ln25_6_reg_1312_pp0_iter4_reg;
        trunc_ln25_7_reg_1429 <= {{img_in0_0_q0[7:4]}};
        trunc_ln25_8_reg_1454 <= {{img_in0_0_q0[7:3]}};
        trunc_ln25_9_reg_1459 <= {{img_in0_1_q0[7:4]}};
        trunc_ln26_1_reg_1327 <= {{img_in1_1_q1[7:2]}};
        trunc_ln26_2_reg_1332 <= {{img_in1_2_q0[7:3]}};
        trunc_ln26_3_reg_1353 <= {{img_in1_1_q1[7:3]}};
        trunc_ln26_4_reg_1358 <= {{img_in1_2_q0[7:2]}};
        trunc_ln26_5_reg_1363 <= {{img_in1_3_q0[7:3]}};
        trunc_ln26_6_reg_1384 <= {{img_in1_3_q0[7:2]}};
        trunc_ln26_7_reg_1434 <= {{img_in1_0_q0[7:3]}};
        trunc_ln26_7_reg_1434_pp0_iter6_reg <= trunc_ln26_7_reg_1434;
        trunc_ln26_8_reg_1464 <= {{img_in1_0_q0[7:2]}};
        trunc_ln26_9_reg_1514 <= {{img_in1_1_q0[7:3]}};
        trunc_ln27_1_reg_1338 <= {{img_in2_1_q1[7:3]}};
        trunc_ln27_1_reg_1338_pp0_iter5_reg <= trunc_ln27_1_reg_1338;
        trunc_ln27_1_reg_1338_pp0_iter6_reg <= trunc_ln27_1_reg_1338_pp0_iter5_reg;
        trunc_ln27_2_reg_1282 <= {{img_in2_2_q0[7:4]}};
        trunc_ln27_3_reg_1368 <= {{img_in2_1_q1[7:4]}};
        trunc_ln27_4_reg_1302 <= {{img_in2_2_q0[7:3]}};
        trunc_ln27_4_reg_1302_pp0_iter4_reg <= trunc_ln27_4_reg_1302;
        trunc_ln27_5_reg_1307 <= {{img_in2_3_q0[7:4]}};
        trunc_ln27_6_reg_1317 <= {{img_in2_3_q0[7:3]}};
        trunc_ln27_6_reg_1317_pp0_iter4_reg <= trunc_ln27_6_reg_1317;
        trunc_ln27_7_reg_1444 <= {{img_in2_0_q0[7:4]}};
        trunc_ln27_8_reg_1469 <= {{img_in2_0_q0[7:3]}};
        trunc_ln27_9_reg_1479 <= {{img_in2_1_q0[7:4]}};
        trunc_ln_reg_1267 <= {{img_in0_0_q1[7:4]}};
        zext_ln25_1_reg_1252[4 : 0] <= zext_ln25_1_fu_480_p1[4 : 0];
        zext_ln8_reg_1144_pp0_iter2_reg[4 : 0] <= zext_ln8_reg_1144_pp0_iter1_reg[4 : 0];
        zext_ln8_reg_1144_pp0_iter3_reg[4 : 0] <= zext_ln8_reg_1144_pp0_iter2_reg[4 : 0];
        zext_ln8_reg_1144_pp0_iter4_reg[4 : 0] <= zext_ln8_reg_1144_pp0_iter3_reg[4 : 0];
        zext_ln8_reg_1144_pp0_iter5_reg[4 : 0] <= zext_ln8_reg_1144_pp0_iter4_reg[4 : 0];
        zext_ln8_reg_1144_pp0_iter6_reg[4 : 0] <= zext_ln8_reg_1144_pp0_iter5_reg[4 : 0];
        zext_ln8_reg_1144_pp0_iter7_reg[4 : 0] <= zext_ln8_reg_1144_pp0_iter6_reg[4 : 0];
        zext_ln8_reg_1144_pp0_iter8_reg[4 : 0] <= zext_ln8_reg_1144_pp0_iter7_reg[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln8_reg_1188 <= icmp_ln8_fu_430_p2;
        icmp_ln8_reg_1188_pp0_iter1_reg <= icmp_ln8_reg_1188;
        lshr_ln25_7_reg_1192 <= {{add_ln25_5_fu_436_p2[6:2]}};
        lshr_ln25_7_reg_1192_pp0_iter1_reg <= lshr_ln25_7_reg_1192;
        lshr_ln25_s_reg_1197 <= {{add_ln25_8_fu_452_p2[6:2]}};
        lshr_ln25_s_reg_1197_pp0_iter1_reg <= lshr_ln25_s_reg_1197;
        zext_ln8_reg_1144[4 : 0] <= zext_ln8_fu_412_p1[4 : 0];
        zext_ln8_reg_1144_pp0_iter1_reg[4 : 0] <= zext_ln8_reg_1144[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        tmp_reg_1135 <= {{y[7:1]}};
        y_read_reg_1131 <= y;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln8_fu_430_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga_0_ce0_local = 1'b1;
    end else begin
        img_ga_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_ga_0_we0_local = 1'b1;
    end else begin
        img_ga_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga_1_ce0_local = 1'b1;
    end else begin
        img_ga_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_ga_1_we0_local = 1'b1;
    end else begin
        img_ga_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga_2_ce0_local = 1'b1;
    end else begin
        img_ga_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (icmp_ln8_reg_1188_pp0_iter8_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_ga_2_we0_local = 1'b1;
    end else begin
        img_ga_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_ga_3_ce0_local = 1'b1;
    end else begin
        img_ga_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (icmp_ln8_reg_1188_pp0_iter8_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_ga_3_we0_local = 1'b1;
    end else begin
        img_ga_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in0_0_ce0_local = 1'b1;
    end else begin
        img_in0_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in0_0_ce1_local = 1'b1;
    end else begin
        img_in0_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in0_1_ce0_local = 1'b1;
    end else begin
        img_in0_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in0_1_ce1_local = 1'b1;
    end else begin
        img_in0_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in0_2_ce0_local = 1'b1;
    end else begin
        img_in0_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in0_3_ce0_local = 1'b1;
    end else begin
        img_in0_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in1_0_ce0_local = 1'b1;
    end else begin
        img_in1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in1_0_ce1_local = 1'b1;
    end else begin
        img_in1_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in1_1_ce0_local = 1'b1;
    end else begin
        img_in1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in1_1_ce1_local = 1'b1;
    end else begin
        img_in1_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in1_2_ce0_local = 1'b1;
    end else begin
        img_in1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in1_3_ce0_local = 1'b1;
    end else begin
        img_in1_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in2_0_ce0_local = 1'b1;
    end else begin
        img_in2_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in2_0_ce1_local = 1'b1;
    end else begin
        img_in2_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in2_1_ce0_local = 1'b1;
    end else begin
        img_in2_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in2_1_ce1_local = 1'b1;
    end else begin
        img_in2_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in2_2_ce0_local = 1'b1;
    end else begin
        img_in2_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in2_3_ce0_local = 1'b1;
    end else begin
        img_in2_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln6_fu_397_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter10 == 1'b1) & (ap_enable_reg_pp0_iter9 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter10 == 1'b1) & (ap_enable_reg_pp0_iter9 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln25_10_fu_1126_p2 = ($signed(sext_ln25_18_fu_1123_p1) + $signed(add_ln25_21_reg_1559));

assign add_ln25_11_fu_788_p2 = ($signed(sext_ln27_13_fu_770_p1) + $signed(sext_ln27_16_fu_782_p1));

assign add_ln25_12_fu_939_p2 = ($signed(sext_ln25_7_fu_936_p1) + $signed(sext_ln27_14_fu_933_p1));

assign add_ln25_13_fu_794_p2 = ($signed(sext_ln27_17_fu_785_p1) + $signed(sext_ln27_15_fu_779_p1));

assign add_ln25_14_fu_698_p2 = ($signed(sext_ln26_1_fu_643_p1) + $signed(sext_ln25_6_fu_695_p1));

assign add_ln25_15_fu_951_p2 = ($signed(sext_ln25_9_fu_948_p1) + $signed(sext_ln25_8_fu_945_p1));

assign add_ln25_16_fu_848_p2 = ($signed(sext_ln27_21_fu_832_p1) + $signed(sext_ln27_23_fu_835_p1));

assign add_ln25_17_fu_1068_p2 = ($signed(sext_ln25_12_fu_1065_p1) + $signed(sext_ln27_22_fu_1059_p1));

assign add_ln25_18_fu_975_p2 = ($signed(sext_ln26_2_fu_957_p1) + $signed(sext_ln25_11_fu_972_p1));

assign add_ln25_19_fu_1077_p2 = ($signed(sext_ln25_13_fu_1074_p1) + $signed(sext_ln27_24_fu_1062_p1));

assign add_ln25_20_fu_1015_p2 = ($signed(sext_ln27_28_fu_1000_p1) + $signed(sext_ln27_30_fu_1009_p1));

assign add_ln25_21_fu_1092_p2 = ($signed(sext_ln25_16_fu_1089_p1) + $signed(sext_ln27_29_fu_1083_p1));

assign add_ln25_22_fu_1021_p2 = ($signed(sext_ln26_3_fu_981_p1) + $signed(sext_ln25_15_fu_1012_p1));

assign add_ln25_23_fu_1101_p2 = ($signed(sext_ln25_17_fu_1098_p1) + $signed(sext_ln27_31_fu_1086_p1));

assign add_ln25_2_fu_1110_p2 = ($signed(sext_ln25_5_fu_1107_p1) + $signed(add_ln25_3_reg_1534));

assign add_ln25_3_fu_1036_p2 = ($signed(sext_ln25_3_fu_1033_p1) + $signed(sext_ln27_4_fu_1027_p1));

assign add_ln25_4_fu_1054_p2 = ($signed(sext_ln25_10_fu_1051_p1) + $signed(add_ln25_12_reg_1494));

assign add_ln25_5_fu_436_p2 = (or_ln8_fu_422_p3 + 7'd2);

assign add_ln25_6_fu_928_p2 = ($signed(sext_ln27_8_fu_925_p1) + $signed(sext_ln25_1_reg_1348_pp0_iter5_reg));

assign add_ln25_7_fu_1118_p2 = ($signed(sext_ln25_14_fu_1115_p1) + $signed(add_ln25_17_reg_1549));

assign add_ln25_8_fu_452_p2 = (x_reg_376 + 7'd5);

assign add_ln25_9_fu_1045_p2 = ($signed(sext_ln25_4_fu_1042_p1) + $signed(sext_ln27_9_fu_1030_p1));

assign add_ln25_fu_758_p2 = ($signed(sext_ln27_5_fu_752_p1) + $signed(sext_ln27_7_fu_755_p1));

assign add_ln27_10_fu_897_p2 = ($signed(sext_ln27_26_fu_894_p1) + $signed(sext_ln27_17_fu_785_p1));

assign add_ln27_11_fu_1003_p2 = ($signed(sext_ln27_27_fu_997_p1) + $signed(sext_ln27_25_fu_994_p1));

assign add_ln27_3_fu_746_p2 = ($signed(sext_ln27_3_fu_743_p1) + $signed(sext_ln27_fu_740_p1));

assign add_ln27_4_fu_919_p2 = ($signed(sext_ln27_2_fu_916_p1) + $signed(sext_ln27_1_fu_913_p1));

assign add_ln27_5_fu_689_p2 = ($signed(sext_ln27_10_fu_686_p1) + $signed(sext_ln25_2_fu_640_p1));

assign add_ln27_6_fu_773_p2 = ($signed(sext_ln27_12_fu_767_p1) + $signed(sext_ln27_11_fu_764_p1));

assign add_ln27_7_fu_714_p2 = ($signed(sext_ln26_fu_598_p1) + $signed(sext_ln25_1_fu_637_p1));

assign add_ln27_8_fu_826_p2 = ($signed(sext_ln27_19_fu_823_p1) + $signed(sext_ln27_6_fu_800_p1));

assign add_ln27_9_fu_966_p2 = ($signed(sext_ln27_20_fu_963_p1) + $signed(sext_ln27_18_fu_960_p1));

assign add_ln27_fu_631_p2 = ($signed(sext_ln25_fu_595_p1) + $signed(sext_ln26_fu_598_p1));

assign add_ln8_fu_468_p2 = (x_reg_376 + 7'd4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return = y_read_reg_1131;

assign icmp_ln6_fu_397_p2 = ((tmp_reg_1135 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln8_fu_430_p2 = ((or_ln8_fu_422_p3 < 7'd86) ? 1'b1 : 1'b0);

assign img_ga_0_address0 = zext_ln8_reg_1144_pp0_iter8_reg;

assign img_ga_0_ce0 = img_ga_0_ce0_local;

assign img_ga_0_d0 = add_ln25_2_reg_1569;

assign img_ga_0_we0 = img_ga_0_we0_local;

assign img_ga_1_address0 = zext_ln8_reg_1144_pp0_iter7_reg;

assign img_ga_1_ce0 = img_ga_1_ce0_local;

assign img_ga_1_d0 = add_ln25_4_reg_1544;

assign img_ga_1_we0 = img_ga_1_we0_local;

assign img_ga_2_address0 = zext_ln8_reg_1144_pp0_iter8_reg;

assign img_ga_2_ce0 = img_ga_2_ce0_local;

assign img_ga_2_d0 = add_ln25_7_reg_1579;

assign img_ga_2_we0 = img_ga_2_we0_local;

assign img_ga_3_address0 = zext_ln8_reg_1144_pp0_iter8_reg;

assign img_ga_3_ce0 = img_ga_3_ce0_local;

assign img_ga_3_d0 = add_ln25_10_reg_1584;

assign img_ga_3_we0 = img_ga_3_we0_local;

assign img_in0_0_address0 = zext_ln25_fu_474_p1;

assign img_in0_0_address1 = zext_ln8_fu_412_p1;

assign img_in0_0_ce0 = img_in0_0_ce0_local;

assign img_in0_0_ce1 = img_in0_0_ce1_local;

assign img_in0_1_address0 = zext_ln25_1_fu_480_p1;

assign img_in0_1_address1 = zext_ln8_fu_412_p1;

assign img_in0_1_ce0 = img_in0_1_ce0_local;

assign img_in0_1_ce1 = img_in0_1_ce1_local;

assign img_in0_2_address0 = zext_ln8_fu_412_p1;

assign img_in0_2_ce0 = img_in0_2_ce0_local;

assign img_in0_3_address0 = zext_ln8_fu_412_p1;

assign img_in0_3_ce0 = img_in0_3_ce0_local;

assign img_in1_0_address0 = zext_ln25_fu_474_p1;

assign img_in1_0_address1 = zext_ln8_reg_1144_pp0_iter1_reg;

assign img_in1_0_ce0 = img_in1_0_ce0_local;

assign img_in1_0_ce1 = img_in1_0_ce1_local;

assign img_in1_1_address0 = zext_ln25_1_reg_1252;

assign img_in1_1_address1 = zext_ln8_reg_1144;

assign img_in1_1_ce0 = img_in1_1_ce0_local;

assign img_in1_1_ce1 = img_in1_1_ce1_local;

assign img_in1_2_address0 = zext_ln8_reg_1144;

assign img_in1_2_ce0 = img_in1_2_ce0_local;

assign img_in1_3_address0 = zext_ln8_reg_1144;

assign img_in1_3_ce0 = img_in1_3_ce0_local;

assign img_in2_0_address0 = zext_ln25_fu_474_p1;

assign img_in2_0_address1 = zext_ln8_reg_1144_pp0_iter1_reg;

assign img_in2_0_ce0 = img_in2_0_ce0_local;

assign img_in2_0_ce1 = img_in2_0_ce1_local;

assign img_in2_1_address0 = zext_ln25_1_fu_480_p1;

assign img_in2_1_address1 = zext_ln8_reg_1144;

assign img_in2_1_ce0 = img_in2_1_ce0_local;

assign img_in2_1_ce1 = img_in2_1_ce1_local;

assign img_in2_2_address0 = zext_ln8_fu_412_p1;

assign img_in2_2_ce0 = img_in2_2_ce0_local;

assign img_in2_3_address0 = zext_ln8_fu_412_p1;

assign img_in2_3_ce0 = img_in2_3_ce0_local;

assign lshr_ln8_fu_402_p4 = {{x_reg_376[6:2]}};

assign or_ln8_fu_422_p3 = {{lshr_ln8_fu_402_p4}, {2'd2}};

assign sext_ln25_10_fu_1051_p1 = $signed(add_ln25_15_reg_1499);

assign sext_ln25_11_fu_972_p1 = $signed(trunc_ln27_7_reg_1444);

assign sext_ln25_12_fu_1065_p1 = $signed(add_ln25_16_reg_1449_pp0_iter6_reg);

assign sext_ln25_13_fu_1074_p1 = $signed(add_ln25_18_reg_1509);

assign sext_ln25_14_fu_1115_p1 = $signed(add_ln25_19_reg_1554);

assign sext_ln25_15_fu_1012_p1 = $signed(trunc_ln27_9_reg_1479);

assign sext_ln25_16_fu_1089_p1 = $signed(add_ln25_20_reg_1524);

assign sext_ln25_17_fu_1098_p1 = $signed(add_ln25_22_reg_1529);

assign sext_ln25_18_fu_1123_p1 = $signed(add_ln25_23_reg_1564);

assign sext_ln25_1_fu_637_p1 = $signed(trunc_ln27_2_reg_1282);

assign sext_ln25_2_fu_640_p1 = $signed(trunc_ln25_3_reg_1287);

assign sext_ln25_3_fu_1033_p1 = $signed(add_ln25_reg_1409_pp0_iter6_reg);

assign sext_ln25_4_fu_1042_p1 = $signed(add_ln25_6_reg_1489);

assign sext_ln25_5_fu_1107_p1 = $signed(add_ln25_9_reg_1539);

assign sext_ln25_6_fu_695_p1 = $signed(trunc_ln27_5_reg_1307);

assign sext_ln25_7_fu_936_p1 = $signed(add_ln25_11_reg_1419);

assign sext_ln25_8_fu_945_p1 = $signed(add_ln25_13_reg_1424);

assign sext_ln25_9_fu_948_p1 = add_ln25_14_reg_1378_pp0_iter5_reg;

assign sext_ln25_fu_595_p1 = $signed(trunc_ln_reg_1267);

assign sext_ln26_1_fu_643_p1 = $signed(trunc_ln25_5_reg_1297);

assign sext_ln26_2_fu_957_p1 = $signed(trunc_ln25_7_reg_1429);

assign sext_ln26_3_fu_981_p1 = $signed(trunc_ln25_9_reg_1459);

assign sext_ln26_fu_598_p1 = $signed(trunc_ln25_2_reg_1277);

assign sext_ln27_10_fu_686_p1 = $signed(trunc_ln25_4_reg_1292);

assign sext_ln27_11_fu_764_p1 = $signed(trunc_ln26_3_reg_1353);

assign sext_ln27_12_fu_767_p1 = $signed(add_ln27_5_reg_1373);

assign sext_ln27_13_fu_770_p1 = $signed(trunc_ln26_4_reg_1358);

assign sext_ln27_14_fu_933_p1 = $signed(add_ln27_6_reg_1414);

assign sext_ln27_15_fu_779_p1 = $signed(trunc_ln27_3_reg_1368);

assign sext_ln27_16_fu_782_p1 = $signed(trunc_ln27_4_reg_1302_pp0_iter4_reg);

assign sext_ln27_17_fu_785_p1 = $signed(trunc_ln26_5_reg_1363);

assign sext_ln27_18_fu_960_p1 = $signed(trunc_ln25_6_reg_1312_pp0_iter5_reg);

assign sext_ln27_19_fu_823_p1 = $signed(add_ln27_7_reg_1389);

assign sext_ln27_1_fu_913_p1 = $signed(trunc_ln14_reg_1394);

assign sext_ln27_20_fu_963_p1 = $signed(add_ln27_8_reg_1439);

assign sext_ln27_21_fu_832_p1 = $signed(trunc_ln26_6_reg_1384);

assign sext_ln27_22_fu_1059_p1 = $signed(add_ln27_9_reg_1504);

assign sext_ln27_23_fu_835_p1 = $signed(trunc_ln27_6_reg_1317_pp0_iter4_reg);

assign sext_ln27_24_fu_1062_p1 = $signed(trunc_ln26_7_reg_1434_pp0_iter6_reg);

assign sext_ln27_25_fu_994_p1 = $signed(trunc_ln25_8_reg_1454);

assign sext_ln27_26_fu_894_p1 = add_ln25_14_reg_1378;

assign sext_ln27_27_fu_997_p1 = $signed(add_ln27_10_reg_1474);

assign sext_ln27_28_fu_1000_p1 = $signed(trunc_ln26_8_reg_1464);

assign sext_ln27_29_fu_1083_p1 = $signed(add_ln27_11_reg_1519);

assign sext_ln27_2_fu_916_p1 = $signed(add_ln27_3_reg_1404);

assign sext_ln27_30_fu_1009_p1 = $signed(trunc_ln27_8_reg_1469);

assign sext_ln27_31_fu_1086_p1 = $signed(trunc_ln26_9_reg_1514);

assign sext_ln27_3_fu_743_p1 = $signed(add_ln27_reg_1343);

assign sext_ln27_4_fu_1027_p1 = $signed(add_ln27_4_reg_1484);

assign sext_ln27_5_fu_752_p1 = $signed(trunc_ln26_1_reg_1327);

assign sext_ln27_6_fu_800_p1 = trunc_ln26_2_reg_1332;

assign sext_ln27_7_fu_755_p1 = trunc_ln26_2_reg_1332;

assign sext_ln27_8_fu_925_p1 = $signed(trunc_ln15_reg_1399);

assign sext_ln27_9_fu_1030_p1 = $signed(trunc_ln27_1_reg_1338_pp0_iter6_reg);

assign sext_ln27_fu_740_p1 = $signed(trunc_ln25_1_reg_1272_pp0_iter4_reg);

assign zext_ln25_1_fu_480_p1 = lshr_ln25_s_reg_1197_pp0_iter1_reg;

assign zext_ln25_fu_474_p1 = lshr_ln25_7_reg_1192_pp0_iter1_reg;

assign zext_ln8_fu_412_p1 = lshr_ln8_fu_402_p4;

always @ (posedge ap_clk) begin
    zext_ln8_reg_1144[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln8_reg_1144_pp0_iter1_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln8_reg_1144_pp0_iter2_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln8_reg_1144_pp0_iter3_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln8_reg_1144_pp0_iter4_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln8_reg_1144_pp0_iter5_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln8_reg_1144_pp0_iter6_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln8_reg_1144_pp0_iter7_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln8_reg_1144_pp0_iter8_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln25_1_reg_1252[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //top_module_gaussian
