-- -------------------------------------------------------------------------------
-- This file has been automatically generated by the Caph compiler (version 2.8.4d)
-- from file main.cph, on 2018-05-11 at 16:31:33, by <unknown>
-- For more information, see : http://caph.univ-bpclermont.fr
-- -------------------------------------------------------------------------------

library ieee,caph,work;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;
use work.all;
use work.edgeDetectionOk_globals.all;

entity roberts_y is
   port (
    arg0_empty: in std_logic;
    arg0: in std_logic_vector(7 downto 0);
    arg0_rd: out std_logic;
    arg1_empty: in std_logic;
    arg1: in std_logic_vector(7 downto 0);
    arg1_rd: out std_logic;
    arg2_empty: in std_logic;
    arg2: in std_logic_vector(7 downto 0);
    arg2_rd: out std_logic;
    arg3_empty: in std_logic;
    arg3: in std_logic_vector(7 downto 0);
    arg3_rd: out std_logic;
    arg4_full: in std_logic;
    arg4: out std_logic_vector(13 downto 0);
    arg4_wr: out std_logic;
    clock: in std_logic;
    reset: in std_logic
    );
end roberts_y;

architecture FSM of roberts_y is
begin
  comb: process(arg0, arg0_empty, arg1, arg1_empty, arg2, arg2_empty, arg3, arg3_empty, arg4_full)
    variable p_p00 : unsigned(7 downto 0);
    variable p_p01 : unsigned(7 downto 0);
    variable p_p10 : unsigned(7 downto 0);
    variable p_p11 : unsigned(7 downto 0);
  begin
    -- arg3.rdy, arg2.rdy, arg1.rdy, arg0.rdy, arg4.rdy / p_p11=arg3, p_p10=arg2, p_p01=arg1, p_p00=arg0, wr(arg4,(p_p01 : signed<14>)-(p_p10 : signed<14>))
    if arg3_empty='0' and arg2_empty='0' and arg1_empty='0' and arg0_empty='0' and arg4_full='0' then
      p_p11 := from_std_logic_vector(arg3,8);
      arg3_rd <= '1';
      p_p10 := from_std_logic_vector(arg2,8);
      arg2_rd <= '1';
      p_p01 := from_std_logic_vector(arg1,8);
      arg1_rd <= '1';
      p_p00 := from_std_logic_vector(arg0,8);
      arg0_rd <= '1';
      arg4 <= std_logic_vector((conv_signed(p_p01,14)) - (conv_signed(p_p10,14)));
      arg4_wr <= '1';
    else
      arg0_rd <= '0';
      arg1_rd <= '0';
      arg2_rd <= '0';
      arg3_rd <= '0';
      arg4_wr <= '0';
      arg4 <= (others => 'X');
    end if;
  end process;
  seq: process(clock, reset)
  begin
    if (reset='0') then
    elsif rising_edge(clock) then
    end if;
  end process;
end FSM;
