-- -------------------------------------------------------------------------------
-- This file has been automatically generated by the Caph compiler (version 2.8.4d)
-- from file main.cph, on 2018-05-11 at 12:39:30, by <unknown>
-- For more information, see : http://caph.univ-bpclermont.fr
-- -------------------------------------------------------------------------------

library ieee,caph,work;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;
use work.all;
use work.edgeDetectionOk_globals.all;

entity delay is
   port (
    arg0_empty: in std_logic;
    arg0: in std_logic_vector(7 downto 0);
    arg0_rd: out std_logic;
    arg1_full: in std_logic;
    arg1: out std_logic_vector(7 downto 0);
    arg1_wr: out std_logic;
    clock: in std_logic;
    reset: in std_logic
    );
end delay;

architecture FSM of delay is
    signal data : unsigned(7 downto 0);
    signal n_data : unsigned(7 downto 0);
    signal en_data : boolean;
begin
  comb: process(arg0, arg0_empty, arg1_full, data)
    variable p_pel : unsigned(7 downto 0);
  begin
    -- arg0.rdy, arg1.rdy / p_pel=arg0, wr(arg1,data), data:=p_pel
    if arg0_empty='0' and arg1_full='0' then
      p_pel := from_std_logic_vector(arg0,8);
      arg0_rd <= '1';
      arg1 <= std_logic_vector(data);
      arg1_wr <= '1';
      n_data <= p_pel;
      en_data <= true;
    else
      arg0_rd <= '0';
      arg1_wr <= '0';
      arg1 <= (others => 'X');
      en_data <= false;
      n_data <= data;
    end if;
  end process;
  seq: process(clock, reset)
  begin
    if (reset='0') then
      data <= "00000000";
    elsif rising_edge(clock) then
      if ( en_data ) then
        data <= n_data after 1 ns;
      end if;
    end if;
  end process;
end FSM;
