-- -------------------------------------------------------------------------------
-- This file has been automatically generated by the Caph compiler (version 2.8.4d)
-- from file main.cph, on 2018-05-11 at 16:30:56, by <unknown>
-- For more information, see : http://caph.univ-bpclermont.fr
-- -------------------------------------------------------------------------------

library ieee,caph,work;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;
use work.all;
use work.edgeDetectionOk_globals.all;

entity sobel_y is
   port (
    arg0_empty: in std_logic;
    arg0: in std_logic_vector(7 downto 0);
    arg0_rd: out std_logic;
    arg1_empty: in std_logic;
    arg1: in std_logic_vector(7 downto 0);
    arg1_rd: out std_logic;
    arg2_empty: in std_logic;
    arg2: in std_logic_vector(7 downto 0);
    arg2_rd: out std_logic;
    arg3_empty: in std_logic;
    arg3: in std_logic_vector(7 downto 0);
    arg3_rd: out std_logic;
    arg4_empty: in std_logic;
    arg4: in std_logic_vector(7 downto 0);
    arg4_rd: out std_logic;
    arg5_empty: in std_logic;
    arg5: in std_logic_vector(7 downto 0);
    arg5_rd: out std_logic;
    arg6_empty: in std_logic;
    arg6: in std_logic_vector(7 downto 0);
    arg6_rd: out std_logic;
    arg7_empty: in std_logic;
    arg7: in std_logic_vector(7 downto 0);
    arg7_rd: out std_logic;
    arg8_empty: in std_logic;
    arg8: in std_logic_vector(7 downto 0);
    arg8_rd: out std_logic;
    arg9_full: in std_logic;
    arg9: out std_logic_vector(13 downto 0);
    arg9_wr: out std_logic;
    clock: in std_logic;
    reset: in std_logic
    );
end sobel_y;

architecture FSM of sobel_y is
begin
  comb: process(arg0, arg0_empty, arg1, arg1_empty, arg2, arg2_empty, arg3, arg3_empty, arg4, arg4_empty, arg5, arg5_empty, arg6, arg6_empty, arg7, arg7_empty, arg8, arg8_empty, arg9_full)
    variable p_p00 : unsigned(7 downto 0);
    variable p_p01 : unsigned(7 downto 0);
    variable p_p02 : unsigned(7 downto 0);
    variable p_p10 : unsigned(7 downto 0);
    variable p_p11 : unsigned(7 downto 0);
    variable p_p12 : unsigned(7 downto 0);
    variable p_p20 : unsigned(7 downto 0);
    variable p_p21 : unsigned(7 downto 0);
    variable p_p22 : unsigned(7 downto 0);
  begin
    -- arg8.rdy, arg7.rdy, arg6.rdy, arg5.rdy, arg4.rdy, arg3.rdy, arg2.rdy, arg1.rdy, arg0.rdy, arg9.rdy / p_p22=arg8, p_p21=arg7, p_p20=arg6, p_p12=arg5, p_p11=arg4, p_p10=arg3, p_p02=arg2, p_p01=arg1, p_p00=arg0, wr(arg9,(p_p00 : signed<14>)+(p_p01 : signed<14>)*2+(p_p02 : signed<14>)-(p_p20 : signed<14>)+2*(p_p21 : signed<14>)+(p_p22 : signed<14>))
    if arg8_empty='0' and arg7_empty='0' and arg6_empty='0' and arg5_empty='0' and arg4_empty='0' and arg3_empty='0' and arg2_empty='0' and arg1_empty='0' and arg0_empty='0' and arg9_full='0' then
      p_p22 := from_std_logic_vector(arg8,8);
      arg8_rd <= '1';
      p_p21 := from_std_logic_vector(arg7,8);
      arg7_rd <= '1';
      p_p20 := from_std_logic_vector(arg6,8);
      arg6_rd <= '1';
      p_p12 := from_std_logic_vector(arg5,8);
      arg5_rd <= '1';
      p_p11 := from_std_logic_vector(arg4,8);
      arg4_rd <= '1';
      p_p10 := from_std_logic_vector(arg3,8);
      arg3_rd <= '1';
      p_p02 := from_std_logic_vector(arg2,8);
      arg2_rd <= '1';
      p_p01 := from_std_logic_vector(arg1,8);
      arg1_rd <= '1';
      p_p00 := from_std_logic_vector(arg0,8);
      arg0_rd <= '1';
      arg9 <= std_logic_vector((((conv_signed(p_p00,14)) + (mul(conv_signed(p_p01,14),to_signed(2,14)))) + (conv_signed(p_p02,14))) - (((conv_signed(p_p20,14)) + (mul(to_signed(2,14),conv_signed(p_p21,14)))) + (conv_signed(p_p22,14))));
      arg9_wr <= '1';
    else
      arg0_rd <= '0';
      arg1_rd <= '0';
      arg2_rd <= '0';
      arg3_rd <= '0';
      arg4_rd <= '0';
      arg5_rd <= '0';
      arg6_rd <= '0';
      arg7_rd <= '0';
      arg8_rd <= '0';
      arg9_wr <= '0';
      arg9 <= (others => 'X');
    end if;
  end process;
  seq: process(clock, reset)
  begin
    if (reset='0') then
    elsif rising_edge(clock) then
    end if;
  end process;
end FSM;
