// ----------------------------------------------------------------------------
//
// This file has been automatically generated by:
// Multi-Dataflow Composer tool - Platform Composer
// Template Interface Layer module - Memory-Mapped type
// on 2026/07/23 16:24:02
// More info available at http://sites.unica.it/rpct/
//
// ----------------------------------------------------------------------------

// ----------------------------------------------------------------------------
// Module Interface
// ----------------------------------------------------------------------------
module s_accelerator#
(
	// Parameters of Axi Slave Bus Interface S00_AXIS
	parameter integer C_S00_AXIS_TDATA_WIDTH	= 32,
// Parameters of Axi Slave Bus Interface S01_AXIS
	parameter integer C_S01_AXIS_TDATA_WIDTH	= 32,

	// Parameters of Axi Master Bus Interface M00_AXIS
	parameter integer C_M00_AXIS_TDATA_WIDTH	= 32,
	parameter integer C_M00_AXIS_START_COUNT	= 32,
	
	// Parameters of Axi Slave Bus Interface S00_AXI
	parameter integer C_S00_AXI_DATA_WIDTH	= 32,
	parameter integer C_S00_AXI_ADDR_WIDTH	= 3
)
(
	// Ports of Axi Slave Bus Interface S00_AXIS
	input wire  s00_axis_aclk,
	input wire  s00_axis_aresetn,
	output wire  s00_axis_tready,
	input wire [C_S00_AXIS_TDATA_WIDTH-1 : 0] s00_axis_tdata,
	input wire [(C_S00_AXIS_TDATA_WIDTH/8)-1 : 0] s00_axis_tkeep,
	input wire  s00_axis_tlast,
	input wire  s00_axis_tvalid,
	input wire [31 : 0] s00_axis_data_count,
// Ports of Axi Slave Bus Interface S01_AXIS
	input wire  s01_axis_aclk,
	input wire  s01_axis_aresetn,
	output wire  s01_axis_tready,
	input wire [C_S01_AXIS_TDATA_WIDTH-1 : 0] s01_axis_tdata,
	input wire [(C_S01_AXIS_TDATA_WIDTH/8)-1 : 0] s01_axis_tkeep,
	input wire  s01_axis_tlast,
	input wire  s01_axis_tvalid,
	input wire [31 : 0] s01_axis_data_count,
	// Ports of Axi Master Bus Interface M00_AXIS
	input wire  m00_axis_aclk,
	input wire  m00_axis_aresetn,
	output wire  m00_axis_tvalid,
	output wire [C_M00_AXIS_TDATA_WIDTH-1 : 0] m00_axis_tdata,
	output wire [(C_M00_AXIS_TDATA_WIDTH/8)-1 : 0] m00_axis_tkeep,
	output wire  m00_axis_tlast,
	input wire  m00_axis_tready,
	
	// Monitoring
	
	// Ports of Axi Slave Bus Interface S00_AXI
	input wire  s00_axi_aclk,
	input wire  s00_axi_aresetn,
	input wire [C_S00_AXI_ADDR_WIDTH-1 : 0] s00_axi_awaddr,
	input wire [2 : 0] s00_axi_awprot,
	input wire  s00_axi_awvalid,
	output wire  s00_axi_awready,
	input wire [C_S00_AXI_DATA_WIDTH-1 : 0] s00_axi_wdata,
	input wire [(C_S00_AXI_DATA_WIDTH/8)-1 : 0] s00_axi_wstrb,
	input wire  s00_axi_wvalid,
	output wire  s00_axi_wready,
	output wire [1 : 0] s00_axi_bresp,
	output wire  s00_axi_bvalid,
	input wire  s00_axi_bready,
	input wire [C_S00_AXI_ADDR_WIDTH-1 : 0] s00_axi_araddr,
	input wire [2 : 0] s00_axi_arprot,
	input wire  s00_axi_arvalid,
	output wire  s00_axi_arready,
	output wire [C_S00_AXI_DATA_WIDTH-1 : 0] s00_axi_rdata,
	output wire [1 : 0] s00_axi_rresp,
	output wire  s00_axi_rvalid,
	input wire  s00_axi_rready
);


// ----------------------------------------------------------------------------
// Module Signals
// ----------------------------------------------------------------------------
// Parameters
// output counter 3 (out0) for tlast
parameter SIZE_COUNT_3 = 8;

// Wire(s) and Reg(s)
wire [31 : 0] slv_reg0;
wire [7 : 0] in0_data;
wire in0_push;
wire in0_full;
wire [5 : 0] in1_data;
wire in1_push;
wire in1_full;
wire [7 : 0] out0_data;
wire out0_push;
wire out0_full;
wire [31 : 0] slv_reg1;


// ----------------------------------------------------------------------------
// Body
// ----------------------------------------------------------------------------
// Configuration Registers
// ----------------------------------------------------------------------------
// Instantiation of Configuration Registers
config_registers # ( 
	.C_S_AXI_DATA_WIDTH(C_S00_AXI_DATA_WIDTH),
	.C_S_AXI_ADDR_WIDTH(C_S00_AXI_ADDR_WIDTH)
) i_config_registers (
	.S_AXI_ACLK(s00_axi_aclk),
	.S_AXI_ARESETN(s00_axi_aresetn),
	.S_AXI_AWADDR(s00_axi_awaddr),
	.S_AXI_AWPROT(s00_axi_awprot),
	.S_AXI_AWVALID(s00_axi_awvalid),
	.S_AXI_AWREADY(s00_axi_awready),
	.S_AXI_WDATA(s00_axi_wdata),
	.S_AXI_WSTRB(s00_axi_wstrb),
	.S_AXI_WVALID(s00_axi_wvalid),
	.S_AXI_WREADY(s00_axi_wready),
	.S_AXI_BRESP(s00_axi_bresp),
	.S_AXI_BVALID(s00_axi_bvalid),
	.S_AXI_BREADY(s00_axi_bready),
	.S_AXI_ARADDR(s00_axi_araddr),
	.S_AXI_ARPROT(s00_axi_arprot),
	.S_AXI_ARVALID(s00_axi_arvalid),
	.S_AXI_ARREADY(s00_axi_arready),
	.S_AXI_RDATA(s00_axi_rdata),
	.S_AXI_RRESP(s00_axi_rresp),
	.S_AXI_RVALID(s00_axi_rvalid),
	.S_AXI_RREADY(s00_axi_rready),
			.slv_reg1(slv_reg1),
    .slv_reg0(slv_reg0)
);
// ----------------------------------------------------------------------------

// ----------------------------------------------------------------------------
	
// Multi-Dataflow Reconfigurable Datapath
// ----------------------------------------------------------------------------
// to adapt profiling
multi_dataflow reconf_dpath (
	// Multi-Dataflow Input(s)
	.in0_data(in0_data),
	.in0_wr(in0_push),
	.in0_full(in0_full),
	.in1_data(in1_data),
	.in1_wr(in1_push),
	.in1_full(in1_full),
	// Multi-Dataflow Output(s)
	.out0_data(out0_data),
	.out0_wr(out0_push),
	.out0_full(out0_full),
	// Monitoring
	// System Signal(s)
	.clock(s00_axi_aclk),
	.reset(s00_axi_aresetn),
	// Multi-Dataflow Kernel ID
	.ID(slv_reg0[31:24])
);
assign s00_axis_tready = !in0_full;
assign in0_data = s00_axis_tdata [7 : 0];
//assign = s00_axis_tkeep;
//assign = s00_axis_tlast;
assign in0_push = s00_axis_tvalid& s00_axis_tready;
//assign = s00_axis_data_count;
assign s01_axis_tready = !in1_full;
assign in1_data = s01_axis_tdata [5 : 0];
//assign = s01_axis_tkeep;
//assign = s01_axis_tlast;
assign in1_push = s01_axis_tvalid& s01_axis_tready;
//assign = s01_axis_data_count;
assign m00_axis_tvalid = out0_push;
assign m00_axis_tdata = {{24{1'b0}},out0_data};
assign m00_axis_tkeep = 4'b1111;
//assign m00_axis_tlast = 1'b0;
assign out0_full = !m00_axis_tready;
// ----------------------------------------------------------------------------	


// Output Counter(s)
// ----------------------------------------------------------------------------
counter #(			
	.SIZE(SIZE_COUNT_3) ) 
i_counter_out0 (
	.aclk(s00_axi_aclk),
	.aresetn(s00_axi_aresetn),
	.clr(slv_reg0[2]),
	.en(out0_push),
	.max(slv_reg1[SIZE_COUNT_3-1:0]),
	.count(),
	.last(m00_axis_tlast)
);
// ----------------------------------------------------------------------------

endmodule
// ----------------------------------------------------------------------------
// ----------------------------------------------------------------------------
// ----------------------------------------------------------------------------
