// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_module_line_buff3_dir (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        y,
        img_dir_0_address0,
        img_dir_0_ce0,
        img_dir_0_we0,
        img_dir_0_d0,
        img_dir_1_address0,
        img_dir_1_ce0,
        img_dir_1_we0,
        img_dir_1_d0,
        img_dir_2_address0,
        img_dir_2_ce0,
        img_dir_2_we0,
        img_dir_2_d0,
        img_dir_3_address0,
        img_dir_3_ce0,
        img_dir_3_we0,
        img_dir_3_d0,
        edgeDirection_0_address0,
        edgeDirection_0_ce0,
        edgeDirection_0_q0,
        edgeDirection_1_address0,
        edgeDirection_1_ce0,
        edgeDirection_1_q0,
        edgeDirection_2_address0,
        edgeDirection_2_ce0,
        edgeDirection_2_q0,
        edgeDirection_3_address0,
        edgeDirection_3_ce0,
        edgeDirection_3_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_pp0_stage0 = 7'd8;
parameter    ap_ST_fsm_state10 = 7'd16;
parameter    ap_ST_fsm_state11 = 7'd32;
parameter    ap_ST_fsm_pp1_stage0 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] y;
output  [4:0] img_dir_0_address0;
output   img_dir_0_ce0;
output   img_dir_0_we0;
output  [7:0] img_dir_0_d0;
output  [4:0] img_dir_1_address0;
output   img_dir_1_ce0;
output   img_dir_1_we0;
output  [7:0] img_dir_1_d0;
output  [4:0] img_dir_2_address0;
output   img_dir_2_ce0;
output   img_dir_2_we0;
output  [7:0] img_dir_2_d0;
output  [4:0] img_dir_3_address0;
output   img_dir_3_ce0;
output   img_dir_3_we0;
output  [7:0] img_dir_3_d0;
output  [4:0] edgeDirection_0_address0;
output   edgeDirection_0_ce0;
input  [7:0] edgeDirection_0_q0;
output  [4:0] edgeDirection_1_address0;
output   edgeDirection_1_ce0;
input  [7:0] edgeDirection_1_q0;
output  [4:0] edgeDirection_2_address0;
output   edgeDirection_2_ce0;
input  [7:0] edgeDirection_2_q0;
output  [4:0] edgeDirection_3_address0;
output   edgeDirection_3_ce0;
input  [7:0] edgeDirection_3_q0;
output  [7:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] img_dirbf_0_address1;
wire   [7:0] img_dirbf_0_q1;
wire   [4:0] img_dirbf_1_address1;
wire   [7:0] img_dirbf_1_q1;
wire   [4:0] img_dirbf_2_address1;
wire   [7:0] img_dirbf_2_q1;
wire   [4:0] img_dirbf_3_address1;
wire   [7:0] img_dirbf_3_q1;
reg   [6:0] x_4118_reg_306;
reg   [6:0] x117_reg_317;
reg   [7:0] reg_328;
reg    ap_enable_reg_pp0_iter3;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp1_stage0_11001;
reg    ap_enable_reg_pp1_iter3;
reg   [7:0] reg_333;
reg   [7:0] reg_338;
reg   [7:0] reg_343;
reg   [7:0] y_read_reg_420;
reg    ap_block_state1;
wire   [0:0] icmp_ln5_fu_348_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln13_fu_353_p2;
wire   [63:0] zext_ln14_fu_368_p1;
reg   [63:0] zext_ln14_reg_434;
wire    ap_CS_fsm_pp0_stage0;
reg   [63:0] zext_ln14_reg_434_pp0_iter1_reg;
reg   [63:0] zext_ln14_reg_434_pp0_iter2_reg;
reg   [63:0] zext_ln14_reg_434_pp0_iter3_reg;
reg   [4:0] img_dirbf_0_addr_1_reg_447;
reg   [4:0] img_dirbf_0_addr_1_reg_447_pp0_iter1_reg;
reg   [4:0] img_dirbf_0_addr_1_reg_447_pp0_iter2_reg;
reg   [4:0] img_dirbf_0_addr_1_reg_447_pp0_iter3_reg;
reg   [4:0] img_dirbf_1_addr_1_reg_458;
reg   [4:0] img_dirbf_1_addr_1_reg_458_pp0_iter1_reg;
reg   [4:0] img_dirbf_1_addr_1_reg_458_pp0_iter2_reg;
reg   [4:0] img_dirbf_1_addr_1_reg_458_pp0_iter3_reg;
reg   [4:0] img_dirbf_2_addr_1_reg_469;
reg   [4:0] img_dirbf_2_addr_1_reg_469_pp0_iter1_reg;
reg   [4:0] img_dirbf_2_addr_1_reg_469_pp0_iter2_reg;
reg   [4:0] img_dirbf_2_addr_1_reg_469_pp0_iter3_reg;
reg   [4:0] img_dirbf_3_addr_1_reg_480;
reg   [4:0] img_dirbf_3_addr_1_reg_480_pp0_iter1_reg;
reg   [4:0] img_dirbf_3_addr_1_reg_480_pp0_iter2_reg;
reg   [4:0] img_dirbf_3_addr_1_reg_480_pp0_iter3_reg;
wire   [6:0] x_4_fu_380_p2;
reg   [6:0] x_4_reg_486;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] icmp_ln14_fu_386_p2;
reg   [7:0] valma_2_reg_496;
reg   [7:0] img_dirbf_1_load_reg_501;
reg   [7:0] img_dirbf_2_load_reg_506;
reg   [7:0] img_dirbf_3_load_reg_511;
wire   [63:0] zext_ln6_fu_401_p1;
reg   [63:0] zext_ln6_reg_536;
wire    ap_CS_fsm_pp1_stage0;
reg   [63:0] zext_ln6_reg_536_pp1_iter1_reg;
reg   [63:0] zext_ln6_reg_536_pp1_iter2_reg;
reg   [63:0] zext_ln6_reg_536_pp1_iter3_reg;
wire   [6:0] x_fu_409_p2;
reg   [6:0] x_reg_564;
reg    ap_enable_reg_pp1_iter0;
wire   [0:0] icmp_ln6_fu_415_p2;
wire    ap_CS_fsm_state3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_condition_pp0_flush_enable;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
wire    ap_CS_fsm_state11;
wire    ap_block_pp1_stage0_subdone;
reg    ap_enable_reg_pp1_iter1;
reg    ap_condition_pp1_flush_enable;
reg    ap_enable_reg_pp1_iter2;
reg    ap_enable_reg_pp1_iter4;
reg    ap_enable_reg_pp1_iter5;
reg   [6:0] ap_phi_mux_x_4118_phi_fu_310_p4;
wire    ap_block_pp0_stage0;
reg   [6:0] ap_phi_mux_x117_phi_fu_321_p4;
wire    ap_block_pp1_stage0;
reg    edgeDirection_0_ce0_local;
reg   [4:0] edgeDirection_0_address0_local;
reg    img_dirbf_0_ce1_local;
reg    img_dirbf_0_we0_local;
reg    img_dirbf_0_ce0_local;
reg   [4:0] img_dirbf_0_address0_local;
reg    edgeDirection_1_ce0_local;
reg   [4:0] edgeDirection_1_address0_local;
reg    edgeDirection_2_ce0_local;
reg   [4:0] edgeDirection_2_address0_local;
reg    edgeDirection_3_ce0_local;
reg   [4:0] edgeDirection_3_address0_local;
reg    img_dirbf_1_ce1_local;
reg    img_dirbf_1_we0_local;
reg    img_dirbf_1_ce0_local;
reg   [4:0] img_dirbf_1_address0_local;
reg    img_dirbf_2_ce1_local;
reg    img_dirbf_2_we0_local;
reg    img_dirbf_2_ce0_local;
reg   [4:0] img_dirbf_2_address0_local;
reg    img_dirbf_3_ce1_local;
reg    img_dirbf_3_we0_local;
reg    img_dirbf_3_ce0_local;
reg   [4:0] img_dirbf_3_address0_local;
reg    img_dir_0_we0_local;
reg    img_dir_0_ce0_local;
reg    img_dir_1_we0_local;
reg    img_dir_1_ce0_local;
reg    img_dir_2_we0_local;
reg    img_dir_2_ce0_local;
reg    img_dir_3_we0_local;
reg    img_dir_3_ce0_local;
wire   [4:0] lshr_ln14_fu_358_p4;
wire   [4:0] lshr_ln6_fu_391_p4;
wire    ap_CS_fsm_state10;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
end

top_module_line_buff3_dir_img_dirbf_0_RAM_AUTO_3R2W #(
    .DataWidth( 8 ),
    .AddressRange( 21 ),
    .AddressWidth( 5 ))
img_dirbf_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(img_dirbf_0_address0_local),
    .ce0(img_dirbf_0_ce0_local),
    .we0(img_dirbf_0_we0_local),
    .d0(reg_328),
    .address1(img_dirbf_0_address1),
    .ce1(img_dirbf_0_ce1_local),
    .q1(img_dirbf_0_q1)
);

top_module_line_buff3_dir_img_dirbf_0_RAM_AUTO_3R2W #(
    .DataWidth( 8 ),
    .AddressRange( 21 ),
    .AddressWidth( 5 ))
img_dirbf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(img_dirbf_1_address0_local),
    .ce0(img_dirbf_1_ce0_local),
    .we0(img_dirbf_1_we0_local),
    .d0(reg_333),
    .address1(img_dirbf_1_address1),
    .ce1(img_dirbf_1_ce1_local),
    .q1(img_dirbf_1_q1)
);

top_module_line_buff3_dir_img_dirbf_0_RAM_AUTO_3R2W #(
    .DataWidth( 8 ),
    .AddressRange( 21 ),
    .AddressWidth( 5 ))
img_dirbf_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(img_dirbf_2_address0_local),
    .ce0(img_dirbf_2_ce0_local),
    .we0(img_dirbf_2_we0_local),
    .d0(reg_338),
    .address1(img_dirbf_2_address1),
    .ce1(img_dirbf_2_ce1_local),
    .q1(img_dirbf_2_q1)
);

top_module_line_buff3_dir_img_dirbf_0_RAM_AUTO_3R2W #(
    .DataWidth( 8 ),
    .AddressRange( 21 ),
    .AddressWidth( 5 ))
img_dirbf_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(img_dirbf_3_address0_local),
    .ce0(img_dirbf_3_ce0_local),
    .we0(img_dirbf_3_we0_local),
    .d0(reg_343),
    .address1(img_dirbf_3_address1),
    .ce1(img_dirbf_3_ce1_local),
    .q1(img_dirbf_3_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp1_flush_enable)) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state11)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp1_flush_enable)) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end else if ((1'b1 == ap_CS_fsm_state11)) begin
            ap_enable_reg_pp1_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        x117_reg_317 <= 7'd0;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln6_fu_415_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        x117_reg_317 <= x_reg_564;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_4118_reg_306 <= 7'd0;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln14_fu_386_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_4118_reg_306 <= x_4_reg_486;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_dirbf_0_addr_1_reg_447 <= zext_ln14_fu_368_p1;
        img_dirbf_0_addr_1_reg_447_pp0_iter1_reg <= img_dirbf_0_addr_1_reg_447;
        img_dirbf_1_addr_1_reg_458 <= zext_ln14_fu_368_p1;
        img_dirbf_1_addr_1_reg_458_pp0_iter1_reg <= img_dirbf_1_addr_1_reg_458;
        img_dirbf_2_addr_1_reg_469 <= zext_ln14_fu_368_p1;
        img_dirbf_2_addr_1_reg_469_pp0_iter1_reg <= img_dirbf_2_addr_1_reg_469;
        img_dirbf_3_addr_1_reg_480 <= zext_ln14_fu_368_p1;
        img_dirbf_3_addr_1_reg_480_pp0_iter1_reg <= img_dirbf_3_addr_1_reg_480;
        zext_ln14_reg_434[4 : 0] <= zext_ln14_fu_368_p1[4 : 0];
        zext_ln14_reg_434_pp0_iter1_reg[4 : 0] <= zext_ln14_reg_434[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        img_dirbf_0_addr_1_reg_447_pp0_iter2_reg <= img_dirbf_0_addr_1_reg_447_pp0_iter1_reg;
        img_dirbf_0_addr_1_reg_447_pp0_iter3_reg <= img_dirbf_0_addr_1_reg_447_pp0_iter2_reg;
        img_dirbf_1_addr_1_reg_458_pp0_iter2_reg <= img_dirbf_1_addr_1_reg_458_pp0_iter1_reg;
        img_dirbf_1_addr_1_reg_458_pp0_iter3_reg <= img_dirbf_1_addr_1_reg_458_pp0_iter2_reg;
        img_dirbf_2_addr_1_reg_469_pp0_iter2_reg <= img_dirbf_2_addr_1_reg_469_pp0_iter1_reg;
        img_dirbf_2_addr_1_reg_469_pp0_iter3_reg <= img_dirbf_2_addr_1_reg_469_pp0_iter2_reg;
        img_dirbf_3_addr_1_reg_480_pp0_iter2_reg <= img_dirbf_3_addr_1_reg_480_pp0_iter1_reg;
        img_dirbf_3_addr_1_reg_480_pp0_iter3_reg <= img_dirbf_3_addr_1_reg_480_pp0_iter2_reg;
        zext_ln14_reg_434_pp0_iter2_reg[4 : 0] <= zext_ln14_reg_434_pp0_iter1_reg[4 : 0];
        zext_ln14_reg_434_pp0_iter3_reg[4 : 0] <= zext_ln14_reg_434_pp0_iter2_reg[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        img_dirbf_1_load_reg_501 <= img_dirbf_1_q1;
        img_dirbf_2_load_reg_506 <= img_dirbf_2_q1;
        img_dirbf_3_load_reg_511 <= img_dirbf_3_q1;
        valma_2_reg_496 <= img_dirbf_0_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp1_iter3 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        reg_328 <= edgeDirection_0_q0;
        reg_333 <= edgeDirection_1_q0;
        reg_338 <= edgeDirection_2_q0;
        reg_343 <= edgeDirection_3_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_4_reg_486 <= x_4_fu_380_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        x_reg_564 <= x_fu_409_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        y_read_reg_420 <= y;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        zext_ln6_reg_536[4 : 0] <= zext_ln6_fu_401_p1[4 : 0];
        zext_ln6_reg_536_pp1_iter1_reg[4 : 0] <= zext_ln6_reg_536[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        zext_ln6_reg_536_pp1_iter2_reg[4 : 0] <= zext_ln6_reg_536_pp1_iter1_reg[4 : 0];
        zext_ln6_reg_536_pp1_iter3_reg[4 : 0] <= zext_ln6_reg_536_pp1_iter2_reg[4 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln14_fu_386_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln6_fu_415_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
        ap_condition_pp1_flush_enable = 1'b1;
    end else begin
        ap_condition_pp1_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln6_fu_415_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        ap_phi_mux_x117_phi_fu_321_p4 = x_reg_564;
    end else begin
        ap_phi_mux_x117_phi_fu_321_p4 = x117_reg_317;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln14_fu_386_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_x_4118_phi_fu_310_p4 = x_4_reg_486;
    end else begin
        ap_phi_mux_x_4118_phi_fu_310_p4 = x_4118_reg_306;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        edgeDirection_0_address0_local = zext_ln6_fu_401_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        edgeDirection_0_address0_local = zext_ln14_fu_368_p1;
    end else begin
        edgeDirection_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        edgeDirection_0_ce0_local = 1'b1;
    end else begin
        edgeDirection_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        edgeDirection_1_address0_local = zext_ln6_fu_401_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        edgeDirection_1_address0_local = zext_ln14_fu_368_p1;
    end else begin
        edgeDirection_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        edgeDirection_1_ce0_local = 1'b1;
    end else begin
        edgeDirection_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        edgeDirection_2_address0_local = zext_ln6_fu_401_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        edgeDirection_2_address0_local = zext_ln14_fu_368_p1;
    end else begin
        edgeDirection_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        edgeDirection_2_ce0_local = 1'b1;
    end else begin
        edgeDirection_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        edgeDirection_3_address0_local = zext_ln6_fu_401_p1;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        edgeDirection_3_address0_local = zext_ln14_fu_368_p1;
    end else begin
        edgeDirection_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        edgeDirection_3_ce0_local = 1'b1;
    end else begin
        edgeDirection_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_dir_0_ce0_local = 1'b1;
    end else begin
        img_dir_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_dir_0_we0_local = 1'b1;
    end else begin
        img_dir_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_dir_1_ce0_local = 1'b1;
    end else begin
        img_dir_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_dir_1_we0_local = 1'b1;
    end else begin
        img_dir_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_dir_2_ce0_local = 1'b1;
    end else begin
        img_dir_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_dir_2_we0_local = 1'b1;
    end else begin
        img_dir_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_dir_3_ce0_local = 1'b1;
    end else begin
        img_dir_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_dir_3_we0_local = 1'b1;
    end else begin
        img_dir_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_dirbf_0_address0_local = zext_ln6_reg_536_pp1_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        img_dirbf_0_address0_local = img_dirbf_0_addr_1_reg_447_pp0_iter3_reg;
    end else begin
        img_dirbf_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_dirbf_0_ce0_local = 1'b1;
    end else begin
        img_dirbf_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_dirbf_0_ce1_local = 1'b1;
    end else begin
        img_dirbf_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_dirbf_0_we0_local = 1'b1;
    end else begin
        img_dirbf_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_dirbf_1_address0_local = zext_ln6_reg_536_pp1_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        img_dirbf_1_address0_local = img_dirbf_1_addr_1_reg_458_pp0_iter3_reg;
    end else begin
        img_dirbf_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_dirbf_1_ce0_local = 1'b1;
    end else begin
        img_dirbf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_dirbf_1_ce1_local = 1'b1;
    end else begin
        img_dirbf_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_dirbf_1_we0_local = 1'b1;
    end else begin
        img_dirbf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_dirbf_2_address0_local = zext_ln6_reg_536_pp1_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        img_dirbf_2_address0_local = img_dirbf_2_addr_1_reg_469_pp0_iter3_reg;
    end else begin
        img_dirbf_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_dirbf_2_ce0_local = 1'b1;
    end else begin
        img_dirbf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_dirbf_2_ce1_local = 1'b1;
    end else begin
        img_dirbf_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_dirbf_2_we0_local = 1'b1;
    end else begin
        img_dirbf_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_dirbf_3_address0_local = zext_ln6_reg_536_pp1_iter3_reg;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        img_dirbf_3_address0_local = img_dirbf_3_addr_1_reg_480_pp0_iter3_reg;
    end else begin
        img_dirbf_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_dirbf_3_ce0_local = 1'b1;
    end else begin
        img_dirbf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_dirbf_3_ce1_local = 1'b1;
    end else begin
        img_dirbf_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_dirbf_3_we0_local = 1'b1;
    end else begin
        img_dirbf_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln13_fu_353_p2 == 1'd0) & (icmp_ln5_fu_348_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln13_fu_353_p2 == 1'd1) & (icmp_ln5_fu_348_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((ap_enable_reg_pp1_iter5 == 1'b1) & (ap_enable_reg_pp1_iter4 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((ap_enable_reg_pp1_iter5 == 1'b1) & (ap_enable_reg_pp1_iter4 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_return = y_read_reg_420;

assign edgeDirection_0_address0 = edgeDirection_0_address0_local;

assign edgeDirection_0_ce0 = edgeDirection_0_ce0_local;

assign edgeDirection_1_address0 = edgeDirection_1_address0_local;

assign edgeDirection_1_ce0 = edgeDirection_1_ce0_local;

assign edgeDirection_2_address0 = edgeDirection_2_address0_local;

assign edgeDirection_2_ce0 = edgeDirection_2_ce0_local;

assign edgeDirection_3_address0 = edgeDirection_3_address0_local;

assign edgeDirection_3_ce0 = edgeDirection_3_ce0_local;

assign icmp_ln13_fu_353_p2 = ((y_read_reg_420 > 8'd5) ? 1'b1 : 1'b0);

assign icmp_ln14_fu_386_p2 = ((x_4_reg_486 < 7'd84) ? 1'b1 : 1'b0);

assign icmp_ln5_fu_348_p2 = ((y_read_reg_420 == 8'd5) ? 1'b1 : 1'b0);

assign icmp_ln6_fu_415_p2 = ((x_reg_564 < 7'd84) ? 1'b1 : 1'b0);

assign img_dir_0_address0 = zext_ln14_reg_434_pp0_iter3_reg;

assign img_dir_0_ce0 = img_dir_0_ce0_local;

assign img_dir_0_d0 = valma_2_reg_496;

assign img_dir_0_we0 = img_dir_0_we0_local;

assign img_dir_1_address0 = zext_ln14_reg_434_pp0_iter3_reg;

assign img_dir_1_ce0 = img_dir_1_ce0_local;

assign img_dir_1_d0 = img_dirbf_1_load_reg_501;

assign img_dir_1_we0 = img_dir_1_we0_local;

assign img_dir_2_address0 = zext_ln14_reg_434_pp0_iter3_reg;

assign img_dir_2_ce0 = img_dir_2_ce0_local;

assign img_dir_2_d0 = img_dirbf_2_load_reg_506;

assign img_dir_2_we0 = img_dir_2_we0_local;

assign img_dir_3_address0 = zext_ln14_reg_434_pp0_iter3_reg;

assign img_dir_3_ce0 = img_dir_3_ce0_local;

assign img_dir_3_d0 = img_dirbf_3_load_reg_511;

assign img_dir_3_we0 = img_dir_3_we0_local;

assign img_dirbf_0_address1 = zext_ln14_fu_368_p1;

assign img_dirbf_1_address1 = zext_ln14_fu_368_p1;

assign img_dirbf_2_address1 = zext_ln14_fu_368_p1;

assign img_dirbf_3_address1 = zext_ln14_fu_368_p1;

assign lshr_ln14_fu_358_p4 = {{ap_phi_mux_x_4118_phi_fu_310_p4[6:2]}};

assign lshr_ln6_fu_391_p4 = {{ap_phi_mux_x117_phi_fu_321_p4[6:2]}};

assign x_4_fu_380_p2 = (ap_phi_mux_x_4118_phi_fu_310_p4 + 7'd4);

assign x_fu_409_p2 = (ap_phi_mux_x117_phi_fu_321_p4 + 7'd4);

assign zext_ln14_fu_368_p1 = lshr_ln14_fu_358_p4;

assign zext_ln6_fu_401_p1 = lshr_ln6_fu_391_p4;

always @ (posedge ap_clk) begin
    zext_ln14_reg_434[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln14_reg_434_pp0_iter1_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln14_reg_434_pp0_iter2_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln14_reg_434_pp0_iter3_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln6_reg_536[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln6_reg_536_pp1_iter1_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln6_reg_536_pp1_iter2_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln6_reg_536_pp1_iter3_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //top_module_line_buff3_dir
