// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_module_line_buff1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        im_axis_in_TDATA,
        im_axis_in_TVALID,
        im_axis_in_TREADY,
        im_axis_in_TKEEP,
        im_axis_in_TSTRB,
        im_axis_in_TLAST,
        y,
        img_in0_0_address0,
        img_in0_0_ce0,
        img_in0_0_we0,
        img_in0_0_d0,
        img_in0_1_address0,
        img_in0_1_ce0,
        img_in0_1_we0,
        img_in0_1_d0,
        img_in0_2_address0,
        img_in0_2_ce0,
        img_in0_2_we0,
        img_in0_2_d0,
        img_in0_3_address0,
        img_in0_3_ce0,
        img_in0_3_we0,
        img_in0_3_d0,
        img_in1_0_address0,
        img_in1_0_ce0,
        img_in1_0_we0,
        img_in1_0_d0,
        img_in1_1_address0,
        img_in1_1_ce0,
        img_in1_1_we0,
        img_in1_1_d0,
        img_in1_2_address0,
        img_in1_2_ce0,
        img_in1_2_we0,
        img_in1_2_d0,
        img_in1_3_address0,
        img_in1_3_ce0,
        img_in1_3_we0,
        img_in1_3_d0,
        img_in2_0_address0,
        img_in2_0_ce0,
        img_in2_0_we0,
        img_in2_0_d0,
        img_in2_1_address0,
        img_in2_1_ce0,
        img_in2_1_we0,
        img_in2_1_d0,
        img_in2_2_address0,
        img_in2_2_ce0,
        img_in2_2_we0,
        img_in2_2_d0,
        img_in2_3_address0,
        img_in2_3_ce0,
        img_in2_3_we0,
        img_in2_3_d0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_pp0_stage0 = 10'd4;
parameter    ap_ST_fsm_state6 = 10'd8;
parameter    ap_ST_fsm_pp1_stage0 = 10'd16;
parameter    ap_ST_fsm_state10 = 10'd32;
parameter    ap_ST_fsm_pp2_stage0 = 10'd64;
parameter    ap_ST_fsm_state15 = 10'd128;
parameter    ap_ST_fsm_pp3_stage0 = 10'd256;
parameter    ap_ST_fsm_state22 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] im_axis_in_TDATA;
input   im_axis_in_TVALID;
output   im_axis_in_TREADY;
input  [3:0] im_axis_in_TKEEP;
input  [3:0] im_axis_in_TSTRB;
input  [0:0] im_axis_in_TLAST;
input  [7:0] y;
output  [4:0] img_in0_0_address0;
output   img_in0_0_ce0;
output   img_in0_0_we0;
output  [7:0] img_in0_0_d0;
output  [4:0] img_in0_1_address0;
output   img_in0_1_ce0;
output   img_in0_1_we0;
output  [7:0] img_in0_1_d0;
output  [4:0] img_in0_2_address0;
output   img_in0_2_ce0;
output   img_in0_2_we0;
output  [7:0] img_in0_2_d0;
output  [4:0] img_in0_3_address0;
output   img_in0_3_ce0;
output   img_in0_3_we0;
output  [7:0] img_in0_3_d0;
output  [4:0] img_in1_0_address0;
output   img_in1_0_ce0;
output   img_in1_0_we0;
output  [7:0] img_in1_0_d0;
output  [4:0] img_in1_1_address0;
output   img_in1_1_ce0;
output   img_in1_1_we0;
output  [7:0] img_in1_1_d0;
output  [4:0] img_in1_2_address0;
output   img_in1_2_ce0;
output   img_in1_2_we0;
output  [7:0] img_in1_2_d0;
output  [4:0] img_in1_3_address0;
output   img_in1_3_ce0;
output   img_in1_3_we0;
output  [7:0] img_in1_3_d0;
output  [4:0] img_in2_0_address0;
output   img_in2_0_ce0;
output   img_in2_0_we0;
output  [7:0] img_in2_0_d0;
output  [4:0] img_in2_1_address0;
output   img_in2_1_ce0;
output   img_in2_1_we0;
output  [7:0] img_in2_1_d0;
output  [4:0] img_in2_2_address0;
output   img_in2_2_ce0;
output   img_in2_2_we0;
output  [7:0] img_in2_2_d0;
output  [4:0] img_in2_3_address0;
output   img_in2_3_ce0;
output   img_in2_3_we0;
output  [7:0] img_in2_3_d0;
output  [7:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg im_axis_in_TREADY;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] img_in1bf_address1;
wire   [31:0] img_in1bf_q1;
wire   [4:0] img_in2bf_address1;
wire   [31:0] img_in2bf_q1;
reg    im_axis_in_TDATA_blk_n;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter1;
wire    ap_block_pp2_stage0_grp3;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_pp1_stage0;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire    ap_CS_fsm_pp3_stage0;
reg    ap_enable_reg_pp3_iter0;
wire    ap_block_pp3_stage0;
reg   [4:0] cnt_2168_reg_438;
reg   [6:0] x_10169_reg_450;
reg   [4:0] cnt_1166_reg_461;
reg   [6:0] x_9167_reg_473;
reg   [6:0] x_8165_reg_484;
reg   [4:0] cnt170_reg_495;
reg   [6:0] x171_reg_506;
reg   [31:0] reg_551;
reg    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_state7_pp1_stage0_iter0;
reg    ap_block_pp1_stage0_11001;
reg    ap_block_state16_pp3_stage0_iter0;
reg    ap_block_pp3_stage0_11001;
reg   [7:0] reg_557;
reg    ap_block_pp2_stage0_11001_grp3;
reg   [7:0] reg_564;
reg   [7:0] reg_571;
reg   [7:0] y_read_reg_814;
reg    ap_block_state1;
wire   [7:0] num4_2_fu_578_p1;
reg   [7:0] num4_2_reg_818;
wire   [4:0] cnt_1_fu_582_p2;
reg   [4:0] cnt_1_reg_823;
wire   [0:0] icmp_ln48_fu_588_p2;
reg   [0:0] icmp_ln48_reg_828;
reg   [0:0] icmp_ln48_reg_828_pp0_iter1_reg;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_subdone;
wire   [6:0] x_9_fu_617_p2;
reg   [6:0] x_9_reg_857;
reg    ap_enable_reg_pp0_iter1;
wire   [7:0] num4_1_fu_623_p1;
reg   [7:0] num4_1_reg_862;
wire   [4:0] cnt_fu_627_p2;
reg   [4:0] cnt_reg_867;
wire   [0:0] icmp_ln30_fu_633_p2;
reg   [0:0] icmp_ln30_reg_872;
reg   [0:0] icmp_ln30_reg_872_pp1_iter1_reg;
wire    ap_block_pp1_stage0_11001_grp0;
reg    ap_block_pp1_stage0_subdone_grp0_done_reg;
wire    ap_block_pp1_stage0_subdone_grp0;
reg    ap_block_pp1_stage0_subdone;
wire   [6:0] x_8_fu_662_p2;
reg   [6:0] x_8_reg_901;
reg    ap_enable_reg_pp1_iter1;
reg   [4:0] lshr_ln16_reg_906;
reg    ap_block_pp2_stage0_11001;
reg   [4:0] lshr_ln16_reg_906_pp2_iter1_reg;
wire   [6:0] x_fu_678_p2;
reg   [6:0] x_reg_911;
reg    ap_enable_reg_pp2_iter0;
wire   [7:0] num4_fu_684_p1;
reg   [7:0] num4_reg_917;
wire   [0:0] icmp_ln14_fu_688_p2;
wire    ap_block_pp2_stage0_11001_grp0;
reg    ap_block_pp2_stage0_subdone_grp0_done_reg;
wire    ap_block_pp2_stage0_subdone_grp0;
reg    ap_block_pp2_stage0_subdone;
reg   [4:0] img_in1bf_addr_reg_946;
reg   [4:0] img_in1bf_addr_reg_946_pp3_iter1_reg;
reg   [4:0] img_in1bf_addr_reg_946_pp3_iter2_reg;
reg   [4:0] img_in1bf_addr_reg_946_pp3_iter3_reg;
reg   [4:0] img_in2bf_addr_reg_952;
wire   [7:0] num3_4_fu_706_p1;
reg   [7:0] num3_4_reg_958;
wire   [4:0] cnt_2_fu_710_p2;
reg   [4:0] cnt_2_reg_963;
wire   [0:0] icmp_ln66_fu_716_p2;
reg   [0:0] icmp_ln66_reg_968;
reg   [0:0] icmp_ln66_reg_968_pp3_iter1_reg;
wire   [63:0] zext_ln11_fu_732_p1;
reg   [63:0] zext_ln11_reg_972;
reg   [63:0] zext_ln11_reg_972_pp3_iter2_reg;
reg   [63:0] zext_ln11_reg_972_pp3_iter3_reg;
wire   [6:0] x_10_fu_740_p2;
reg   [6:0] x_10_reg_1004;
reg    ap_enable_reg_pp3_iter1;
reg   [7:0] num1_1_reg_1009;
reg   [7:0] num1_2_reg_1014;
reg   [7:0] num1_3_reg_1019;
wire   [7:0] num1_4_fu_776_p1;
reg   [7:0] num1_4_reg_1024;
reg   [31:0] val_2_reg_1029;
reg    ap_enable_reg_pp3_iter3;
reg   [7:0] num2_1_reg_1034;
reg   [7:0] num2_2_reg_1039;
reg   [7:0] num2_3_reg_1044;
wire   [7:0] num2_4_fu_810_p1;
reg   [7:0] num2_4_reg_1049;
wire    ap_block_pp3_stage0_11001_grp0;
reg    ap_block_pp3_stage0_subdone_grp0_done_reg;
wire    ap_block_pp3_stage0_subdone_grp0;
reg    ap_block_pp3_stage0_subdone;
wire    ap_CS_fsm_state2;
reg    ap_condition_pp0_flush_enable;
reg    ap_enable_reg_pp0_iter2;
reg    ap_condition_pp1_flush_enable;
reg    ap_enable_reg_pp1_iter2;
reg    ap_condition_pp2_flush_enable;
reg    ap_enable_reg_pp2_iter2;
reg    ap_enable_reg_pp2_iter3;
reg    ap_condition_pp3_flush_enable;
reg    ap_enable_reg_pp3_iter2;
reg    ap_enable_reg_pp3_iter4;
reg    ap_enable_reg_pp3_iter5;
reg   [4:0] ap_phi_mux_cnt_2168_phi_fu_442_p4;
reg   [6:0] ap_phi_mux_x_10169_phi_fu_454_p4;
reg   [4:0] ap_phi_mux_cnt_1166_phi_fu_465_p4;
reg   [6:0] ap_phi_mux_x_9167_phi_fu_477_p4;
reg   [6:0] ap_phi_mux_x_8165_phi_fu_488_p4;
wire    ap_block_pp2_stage0;
reg   [4:0] ap_phi_mux_cnt170_phi_fu_499_p4;
reg   [6:0] ap_phi_mux_x171_phi_fu_510_p4;
wire   [63:0] zext_ln48_fu_594_p1;
wire    ap_block_pp0_stage0_grp0;
wire   [63:0] zext_ln52_fu_609_p1;
wire   [63:0] zext_ln30_fu_639_p1;
wire    ap_block_pp1_stage0_grp0;
wire   [63:0] zext_ln34_fu_654_p1;
wire   [63:0] zext_ln18_fu_693_p1;
wire    ap_block_pp2_stage0_grp0;
wire   [63:0] zext_ln66_fu_700_p1;
wire    ap_block_pp3_stage0_grp0;
reg    img_in2bf_we0_local;
reg    img_in2bf_ce0_local;
reg   [4:0] img_in2bf_address0_local;
reg    img_in2bf_ce1_local;
reg    img_in2_0_we0_local;
reg    img_in2_0_ce0_local;
reg   [4:0] img_in2_0_address0_local;
reg    img_in2_1_we0_local;
reg    img_in2_1_ce0_local;
reg   [4:0] img_in2_1_address0_local;
reg    img_in2_2_we0_local;
reg    img_in2_2_ce0_local;
reg   [4:0] img_in2_2_address0_local;
reg    img_in2_3_we0_local;
reg   [7:0] img_in2_3_d0_local;
reg    img_in2_3_ce0_local;
reg   [4:0] img_in2_3_address0_local;
reg    img_in1bf_we0_local;
reg   [31:0] img_in1bf_d0_local;
reg    img_in1bf_ce0_local;
reg   [4:0] img_in1bf_address0_local;
reg    img_in1bf_ce1_local;
reg    img_in1_0_we0_local;
reg   [7:0] img_in1_0_d0_local;
reg    img_in1_0_ce0_local;
reg   [4:0] img_in1_0_address0_local;
reg    img_in1_1_we0_local;
reg   [7:0] img_in1_1_d0_local;
reg    img_in1_1_ce0_local;
reg   [4:0] img_in1_1_address0_local;
reg    img_in1_2_we0_local;
reg   [7:0] img_in1_2_d0_local;
reg    img_in1_2_ce0_local;
reg   [4:0] img_in1_2_address0_local;
reg    img_in1_3_we0_local;
reg   [7:0] img_in1_3_d0_local;
reg    img_in1_3_ce0_local;
reg   [4:0] img_in1_3_address0_local;
reg    img_in0_0_we0_local;
reg   [7:0] img_in0_0_d0_local;
reg    img_in0_0_ce0_local;
reg   [4:0] img_in0_0_address0_local;
reg    img_in0_1_we0_local;
reg   [7:0] img_in0_1_d0_local;
reg    img_in0_1_ce0_local;
reg   [4:0] img_in0_1_address0_local;
reg    img_in0_2_we0_local;
reg   [7:0] img_in0_2_d0_local;
reg    img_in0_2_ce0_local;
reg   [4:0] img_in0_2_address0_local;
reg    img_in0_3_we0_local;
reg   [7:0] img_in0_3_d0_local;
reg    img_in0_3_ce0_local;
reg   [4:0] img_in0_3_address0_local;
wire   [4:0] lshr_ln17_fu_599_p4;
wire   [4:0] lshr_ln_fu_644_p4;
wire   [4:0] lshr_ln11_fu_722_p4;
wire    ap_CS_fsm_state22;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_idle_pp3;
wire    ap_enable_pp3;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_block_pp1_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_block_pp2_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter3 = 1'b0;
#0 ap_block_pp3_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter3 = 1'b0;
#0 ap_enable_reg_pp3_iter2 = 1'b0;
#0 ap_enable_reg_pp3_iter4 = 1'b0;
#0 ap_enable_reg_pp3_iter5 = 1'b0;
end

top_module_line_buff1_img_in1bf_RAM_AUTO_3R2W #(
    .DataWidth( 32 ),
    .AddressRange( 22 ),
    .AddressWidth( 5 ))
img_in1bf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(img_in1bf_address0_local),
    .ce0(img_in1bf_ce0_local),
    .we0(img_in1bf_we0_local),
    .d0(img_in1bf_d0_local),
    .address1(img_in1bf_address1),
    .ce1(img_in1bf_ce1_local),
    .q1(img_in1bf_q1)
);

top_module_line_buff1_img_in1bf_RAM_AUTO_3R2W #(
    .DataWidth( 32 ),
    .AddressRange( 22 ),
    .AddressWidth( 5 ))
img_in2bf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(img_in2bf_address0_local),
    .ce0(img_in2bf_ce0_local),
    .we0(img_in2bf_we0_local),
    .d0(reg_551),
    .address1(img_in2bf_address1),
    .ce1(img_in2bf_ce1_local),
    .q1(img_in2bf_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp1_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_block_pp1_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp1_stage0_subdone_grp0)) begin
            ap_block_pp1_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp2_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_block_pp2_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp2_stage0_subdone_grp0)) begin
            ap_block_pp2_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp3_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_block_pp3_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp3_stage0_subdone_grp0)) begin
            ap_block_pp3_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state22)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((y_read_reg_814 == 8'd2) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((y_read_reg_814 == 8'd2) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp1_flush_enable)) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((y_read_reg_814 == 8'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end else if (((y_read_reg_814 == 8'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp1_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp2_flush_enable)) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if (((y_read_reg_814 == 8'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp2_flush_enable)) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end else if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter3 <= ap_enable_reg_pp2_iter2;
        end else if (((y_read_reg_814 == 8'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp2_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp3_flush_enable)) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if ((~(y_read_reg_814 == 8'd0) & ~(y_read_reg_814 == 8'd1) & ~(y_read_reg_814 == 8'd2) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter2 <= ap_enable_reg_pp3_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter3 <= ap_enable_reg_pp3_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter4 <= ap_enable_reg_pp3_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter5 <= ap_enable_reg_pp3_iter4;
        end else if ((~(y_read_reg_814 == 8'd0) & ~(y_read_reg_814 == 8'd1) & ~(y_read_reg_814 == 8'd2) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp3_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~(y_read_reg_814 == 8'd0) & ~(y_read_reg_814 == 8'd1) & ~(y_read_reg_814 == 8'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        cnt170_reg_495 <= 5'd0;
    end else if (((ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln66_reg_968 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        cnt170_reg_495 <= cnt_2_reg_963;
    end
end

always @ (posedge ap_clk) begin
    if (((y_read_reg_814 == 8'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        cnt_1166_reg_461 <= 5'd0;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln30_reg_872 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        cnt_1166_reg_461 <= cnt_reg_867;
    end
end

always @ (posedge ap_clk) begin
    if (((y_read_reg_814 == 8'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        cnt_2168_reg_438 <= 5'd0;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln48_reg_828 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cnt_2168_reg_438 <= cnt_1_reg_823;
    end
end

always @ (posedge ap_clk) begin
    if ((~(y_read_reg_814 == 8'd0) & ~(y_read_reg_814 == 8'd1) & ~(y_read_reg_814 == 8'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        x171_reg_506 <= 7'd0;
    end else if (((ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln66_reg_968_pp3_iter1_reg == 1'd0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        x171_reg_506 <= x_10_reg_1004;
    end
end

always @ (posedge ap_clk) begin
    if (((y_read_reg_814 == 8'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        x_10169_reg_450 <= 7'd0;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln48_reg_828_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_10169_reg_450 <= x_9_reg_857;
    end
end

always @ (posedge ap_clk) begin
    if (((y_read_reg_814 == 8'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        x_8165_reg_484 <= 7'd0;
    end else if (((icmp_ln14_fu_688_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1))) begin
        x_8165_reg_484 <= x_reg_911;
    end
end

always @ (posedge ap_clk) begin
    if (((y_read_reg_814 == 8'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        x_9167_reg_473 <= 7'd0;
    end else if (((ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln30_reg_872_pp1_iter1_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        x_9167_reg_473 <= x_8_reg_901;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cnt_1_reg_823 <= cnt_1_fu_582_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        cnt_2_reg_963 <= cnt_2_fu_710_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        cnt_reg_867 <= cnt_fu_627_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        icmp_ln30_reg_872 <= icmp_ln30_fu_633_p2;
        icmp_ln30_reg_872_pp1_iter1_reg <= icmp_ln30_reg_872;
        num4_1_reg_862 <= num4_1_fu_623_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln48_reg_828 <= icmp_ln48_fu_588_p2;
        icmp_ln48_reg_828_pp0_iter1_reg <= icmp_ln48_reg_828;
        num4_2_reg_818 <= num4_2_fu_578_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        icmp_ln66_reg_968 <= icmp_ln66_fu_716_p2;
        icmp_ln66_reg_968_pp3_iter1_reg <= icmp_ln66_reg_968;
        img_in1bf_addr_reg_946 <= zext_ln66_fu_700_p1;
        img_in1bf_addr_reg_946_pp3_iter1_reg <= img_in1bf_addr_reg_946;
        img_in2bf_addr_reg_952 <= zext_ln66_fu_700_p1;
        num3_4_reg_958 <= num3_4_fu_706_p1;
        zext_ln11_reg_972[4 : 0] <= zext_ln11_fu_732_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp3_stage0_11001)) begin
        img_in1bf_addr_reg_946_pp3_iter2_reg <= img_in1bf_addr_reg_946_pp3_iter1_reg;
        img_in1bf_addr_reg_946_pp3_iter3_reg <= img_in1bf_addr_reg_946_pp3_iter2_reg;
        num1_1_reg_1009 <= {{img_in1bf_q1[31:24]}};
        num1_2_reg_1014 <= {{img_in1bf_q1[23:16]}};
        num1_3_reg_1019 <= {{img_in1bf_q1[15:8]}};
        num1_4_reg_1024 <= num1_4_fu_776_p1;
        num2_1_reg_1034 <= {{img_in2bf_q1[31:24]}};
        num2_2_reg_1039 <= {{img_in2bf_q1[23:16]}};
        num2_3_reg_1044 <= {{img_in2bf_q1[15:8]}};
        num2_4_reg_1049 <= num2_4_fu_810_p1;
        zext_ln11_reg_972_pp3_iter2_reg[4 : 0] <= zext_ln11_reg_972[4 : 0];
        zext_ln11_reg_972_pp3_iter3_reg[4 : 0] <= zext_ln11_reg_972_pp3_iter2_reg[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        lshr_ln16_reg_906 <= {{ap_phi_mux_x_8165_phi_fu_488_p4[6:2]}};
        lshr_ln16_reg_906_pp2_iter1_reg <= lshr_ln16_reg_906;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001_grp3))) begin
        num4_reg_917 <= num4_fu_684_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        reg_551 <= im_axis_in_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001_grp3) & (ap_enable_reg_pp2_iter1 == 1'b1)))) begin
        reg_557 <= {{im_axis_in_TDATA[31:24]}};
        reg_564 <= {{im_axis_in_TDATA[23:16]}};
        reg_571 <= {{im_axis_in_TDATA[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp3_iter3 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        val_2_reg_1029 <= img_in2bf_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        x_10_reg_1004 <= x_10_fu_740_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        x_8_reg_901 <= x_8_fu_662_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_9_reg_857 <= x_9_fu_617_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        x_reg_911 <= x_fu_678_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        y_read_reg_814 <= y;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln48_fu_588_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln30_fu_633_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
        ap_condition_pp1_flush_enable = 1'b1;
    end else begin
        ap_condition_pp1_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln14_fu_688_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter1 == 1'b1))) begin
        ap_condition_pp2_flush_enable = 1'b1;
    end else begin
        ap_condition_pp2_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln66_fu_716_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
        ap_condition_pp3_flush_enable = 1'b1;
    end else begin
        ap_condition_pp3_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter3 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter5 == 1'b0) & (ap_enable_reg_pp3_iter4 == 1'b0) & (ap_enable_reg_pp3_iter2 == 1'b0) & (ap_enable_reg_pp3_iter3 == 1'b0) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln66_reg_968 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0))) begin
        ap_phi_mux_cnt170_phi_fu_499_p4 = cnt_2_reg_963;
    end else begin
        ap_phi_mux_cnt170_phi_fu_499_p4 = cnt170_reg_495;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln30_reg_872 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        ap_phi_mux_cnt_1166_phi_fu_465_p4 = cnt_reg_867;
    end else begin
        ap_phi_mux_cnt_1166_phi_fu_465_p4 = cnt_1166_reg_461;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln48_reg_828 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_cnt_2168_phi_fu_442_p4 = cnt_1_reg_823;
    end else begin
        ap_phi_mux_cnt_2168_phi_fu_442_p4 = cnt_2168_reg_438;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln66_reg_968_pp3_iter1_reg == 1'd0) & (1'b0 == ap_block_pp3_stage0))) begin
        ap_phi_mux_x171_phi_fu_510_p4 = x_10_reg_1004;
    end else begin
        ap_phi_mux_x171_phi_fu_510_p4 = x171_reg_506;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln48_reg_828_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_x_10169_phi_fu_454_p4 = x_9_reg_857;
    end else begin
        ap_phi_mux_x_10169_phi_fu_454_p4 = x_10169_reg_450;
    end
end

always @ (*) begin
    if (((icmp_ln14_fu_688_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1))) begin
        ap_phi_mux_x_8165_phi_fu_488_p4 = x_reg_911;
    end else begin
        ap_phi_mux_x_8165_phi_fu_488_p4 = x_8165_reg_484;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln30_reg_872_pp1_iter1_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0))) begin
        ap_phi_mux_x_9167_phi_fu_477_p4 = x_8_reg_901;
    end else begin
        ap_phi_mux_x_9167_phi_fu_477_p4 = x_9167_reg_473;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0)) | ((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_grp3) & (ap_enable_reg_pp2_iter1 == 1'b1)))) begin
        im_axis_in_TDATA_blk_n = im_axis_in_TVALID;
    end else begin
        im_axis_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001_grp3) & (ap_enable_reg_pp2_iter1 == 1'b1)))) begin
        im_axis_in_TREADY = 1'b1;
    end else begin
        im_axis_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_grp0))) begin
        img_in0_0_address0_local = zext_ln11_reg_972_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_grp0))) begin
        img_in0_0_address0_local = zext_ln18_fu_693_p1;
    end else begin
        img_in0_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp2_iter3 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp2_stage0_11001_grp0)) | ((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp2_stage0_11001_grp0)))) begin
        img_in0_0_ce0_local = 1'b1;
    end else begin
        img_in0_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_grp0))) begin
        img_in0_0_d0_local = num1_1_reg_1009;
    end else if (((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_grp0))) begin
        img_in0_0_d0_local = reg_557;
    end else begin
        img_in0_0_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp2_stage0_11001_grp0)))) begin
        img_in0_0_we0_local = 1'b1;
    end else begin
        img_in0_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_grp0))) begin
        img_in0_1_address0_local = zext_ln11_reg_972_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_grp0))) begin
        img_in0_1_address0_local = zext_ln18_fu_693_p1;
    end else begin
        img_in0_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp2_iter3 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp2_stage0_11001_grp0)) | ((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp2_stage0_11001_grp0)))) begin
        img_in0_1_ce0_local = 1'b1;
    end else begin
        img_in0_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_grp0))) begin
        img_in0_1_d0_local = num1_2_reg_1014;
    end else if (((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_grp0))) begin
        img_in0_1_d0_local = reg_564;
    end else begin
        img_in0_1_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp2_stage0_11001_grp0)))) begin
        img_in0_1_we0_local = 1'b1;
    end else begin
        img_in0_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_grp0))) begin
        img_in0_2_address0_local = zext_ln11_reg_972_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_grp0))) begin
        img_in0_2_address0_local = zext_ln18_fu_693_p1;
    end else begin
        img_in0_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp2_iter3 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp2_stage0_11001_grp0)) | ((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp2_stage0_11001_grp0)))) begin
        img_in0_2_ce0_local = 1'b1;
    end else begin
        img_in0_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_grp0))) begin
        img_in0_2_d0_local = num1_3_reg_1019;
    end else if (((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_grp0))) begin
        img_in0_2_d0_local = reg_571;
    end else begin
        img_in0_2_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp2_stage0_11001_grp0)))) begin
        img_in0_2_we0_local = 1'b1;
    end else begin
        img_in0_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_grp0))) begin
        img_in0_3_address0_local = zext_ln11_reg_972_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_grp0))) begin
        img_in0_3_address0_local = zext_ln18_fu_693_p1;
    end else begin
        img_in0_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp2_iter3 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp2_stage0_11001_grp0)) | ((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp2_stage0_11001_grp0)))) begin
        img_in0_3_ce0_local = 1'b1;
    end else begin
        img_in0_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_grp0))) begin
        img_in0_3_d0_local = num1_4_reg_1024;
    end else if (((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_grp0))) begin
        img_in0_3_d0_local = num4_reg_917;
    end else begin
        img_in0_3_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp2_iter2 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp2_stage0_11001_grp0)))) begin
        img_in0_3_we0_local = 1'b1;
    end else begin
        img_in0_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_grp0))) begin
        img_in1_0_address0_local = zext_ln11_reg_972_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        img_in1_0_address0_local = zext_ln34_fu_654_p1;
    end else begin
        img_in1_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_in1_0_ce0_local = 1'b1;
    end else begin
        img_in1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_grp0))) begin
        img_in1_0_d0_local = num2_1_reg_1034;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        img_in1_0_d0_local = reg_557;
    end else begin
        img_in1_0_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_in1_0_we0_local = 1'b1;
    end else begin
        img_in1_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_grp0))) begin
        img_in1_1_address0_local = zext_ln11_reg_972_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        img_in1_1_address0_local = zext_ln34_fu_654_p1;
    end else begin
        img_in1_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_in1_1_ce0_local = 1'b1;
    end else begin
        img_in1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_grp0))) begin
        img_in1_1_d0_local = num2_2_reg_1039;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        img_in1_1_d0_local = reg_564;
    end else begin
        img_in1_1_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_in1_1_we0_local = 1'b1;
    end else begin
        img_in1_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_grp0))) begin
        img_in1_2_address0_local = zext_ln11_reg_972_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        img_in1_2_address0_local = zext_ln34_fu_654_p1;
    end else begin
        img_in1_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_in1_2_ce0_local = 1'b1;
    end else begin
        img_in1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_grp0))) begin
        img_in1_2_d0_local = num2_3_reg_1044;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        img_in1_2_d0_local = reg_571;
    end else begin
        img_in1_2_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_in1_2_we0_local = 1'b1;
    end else begin
        img_in1_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_grp0))) begin
        img_in1_3_address0_local = zext_ln11_reg_972_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        img_in1_3_address0_local = zext_ln34_fu_654_p1;
    end else begin
        img_in1_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_in1_3_ce0_local = 1'b1;
    end else begin
        img_in1_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_grp0))) begin
        img_in1_3_d0_local = num2_4_reg_1049;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        img_in1_3_d0_local = num4_1_reg_862;
    end else begin
        img_in1_3_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp3_stage0_11001_grp0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        img_in1_3_we0_local = 1'b1;
    end else begin
        img_in1_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_in1bf_address0_local = img_in1bf_addr_reg_946_pp3_iter3_reg;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_grp0))) begin
        img_in1bf_address0_local = zext_ln30_fu_639_p1;
    end else begin
        img_in1bf_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter5 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp1_stage0_11001_grp0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp1_stage0_11001_grp0)))) begin
        img_in1bf_ce0_local = 1'b1;
    end else begin
        img_in1bf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)))) begin
        img_in1bf_ce1_local = 1'b1;
    end else begin
        img_in1bf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_in1bf_d0_local = val_2_reg_1029;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_grp0))) begin
        img_in1bf_d0_local = reg_551;
    end else begin
        img_in1bf_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter4 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp1_stage0_11001_grp0)))) begin
        img_in1bf_we0_local = 1'b1;
    end else begin
        img_in1bf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0))) begin
        img_in2_0_address0_local = zext_ln11_fu_732_p1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        img_in2_0_address0_local = zext_ln52_fu_609_p1;
    end else begin
        img_in2_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in2_0_ce0_local = 1'b1;
    end else begin
        img_in2_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in2_0_we0_local = 1'b1;
    end else begin
        img_in2_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0))) begin
        img_in2_1_address0_local = zext_ln11_fu_732_p1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        img_in2_1_address0_local = zext_ln52_fu_609_p1;
    end else begin
        img_in2_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in2_1_ce0_local = 1'b1;
    end else begin
        img_in2_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in2_1_we0_local = 1'b1;
    end else begin
        img_in2_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0))) begin
        img_in2_2_address0_local = zext_ln11_fu_732_p1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        img_in2_2_address0_local = zext_ln52_fu_609_p1;
    end else begin
        img_in2_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in2_2_ce0_local = 1'b1;
    end else begin
        img_in2_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in2_2_we0_local = 1'b1;
    end else begin
        img_in2_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0))) begin
        img_in2_3_address0_local = zext_ln11_fu_732_p1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        img_in2_3_address0_local = zext_ln52_fu_609_p1;
    end else begin
        img_in2_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in2_3_ce0_local = 1'b1;
    end else begin
        img_in2_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0))) begin
        img_in2_3_d0_local = num3_4_reg_958;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        img_in2_3_d0_local = num4_2_reg_818;
    end else begin
        img_in2_3_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        img_in2_3_we0_local = 1'b1;
    end else begin
        img_in2_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0))) begin
        img_in2bf_address0_local = img_in2bf_addr_reg_952;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp0))) begin
        img_in2bf_address0_local = zext_ln48_fu_594_p1;
    end else begin
        img_in2bf_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)))) begin
        img_in2bf_ce0_local = 1'b1;
    end else begin
        img_in2bf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter2 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001)))) begin
        img_in2bf_ce1_local = 1'b1;
    end else begin
        img_in2bf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)))) begin
        img_in2bf_we0_local = 1'b1;
    end else begin
        img_in2bf_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~(y_read_reg_814 == 8'd0) & ~(y_read_reg_814 == 8'd1) & ~(y_read_reg_814 == 8'd2) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if (((y_read_reg_814 == 8'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((y_read_reg_814 == 8'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((ap_enable_reg_pp1_iter2 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((ap_enable_reg_pp1_iter2 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((ap_enable_reg_pp2_iter3 == 1'b1) & (ap_enable_reg_pp2_iter2 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((ap_enable_reg_pp2_iter3 == 1'b1) & (ap_enable_reg_pp2_iter2 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_pp3_stage0 : begin
            if (~((ap_enable_reg_pp3_iter5 == 1'b1) & (ap_enable_reg_pp3_iter4 == 1'b0) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if (((ap_enable_reg_pp3_iter5 == 1'b1) & (ap_enable_reg_pp3_iter4 == 1'b0) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((1'b1 == ap_block_state3_pp0_stage0_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b1 == ap_block_state3_pp0_stage0_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((1'b1 == ap_block_state7_pp1_stage0_iter0) & (ap_enable_reg_pp1_iter0 == 1'b1));
end

assign ap_block_pp1_stage0_11001_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((1'b1 == ap_block_state7_pp1_stage0_iter0) & (ap_enable_reg_pp1_iter0 == 1'b1));
end

assign ap_block_pp1_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_11001 = ((im_axis_in_TVALID == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

assign ap_block_pp2_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_11001_grp3 = ((im_axis_in_TVALID == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

assign ap_block_pp2_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_subdone = ((im_axis_in_TVALID == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b1));
end

assign ap_block_pp2_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp3_stage0_11001 = ((1'b1 == ap_block_state16_pp3_stage0_iter0) & (ap_enable_reg_pp3_iter0 == 1'b1));
end

assign ap_block_pp3_stage0_11001_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp3_stage0_subdone = ((1'b1 == ap_block_state16_pp3_stage0_iter0) & (ap_enable_reg_pp3_iter0 == 1'b1));
end

assign ap_block_pp3_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state16_pp3_stage0_iter0 = (im_axis_in_TVALID == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter0 = (im_axis_in_TVALID == 1'b0);
end

always @ (*) begin
    ap_block_state7_pp1_stage0_iter0 = (im_axis_in_TVALID == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

assign ap_return = y_read_reg_814;

assign cnt_1_fu_582_p2 = (ap_phi_mux_cnt_2168_phi_fu_442_p4 + 5'd1);

assign cnt_2_fu_710_p2 = (ap_phi_mux_cnt170_phi_fu_499_p4 + 5'd1);

assign cnt_fu_627_p2 = (ap_phi_mux_cnt_1166_phi_fu_465_p4 + 5'd1);

assign icmp_ln14_fu_688_p2 = ((x_reg_911 < 7'd88) ? 1'b1 : 1'b0);

assign icmp_ln30_fu_633_p2 = ((ap_phi_mux_cnt_1166_phi_fu_465_p4 == 5'd21) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_588_p2 = ((ap_phi_mux_cnt_2168_phi_fu_442_p4 == 5'd21) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_716_p2 = ((ap_phi_mux_cnt170_phi_fu_499_p4 == 5'd21) ? 1'b1 : 1'b0);

assign img_in0_0_address0 = img_in0_0_address0_local;

assign img_in0_0_ce0 = img_in0_0_ce0_local;

assign img_in0_0_d0 = img_in0_0_d0_local;

assign img_in0_0_we0 = img_in0_0_we0_local;

assign img_in0_1_address0 = img_in0_1_address0_local;

assign img_in0_1_ce0 = img_in0_1_ce0_local;

assign img_in0_1_d0 = img_in0_1_d0_local;

assign img_in0_1_we0 = img_in0_1_we0_local;

assign img_in0_2_address0 = img_in0_2_address0_local;

assign img_in0_2_ce0 = img_in0_2_ce0_local;

assign img_in0_2_d0 = img_in0_2_d0_local;

assign img_in0_2_we0 = img_in0_2_we0_local;

assign img_in0_3_address0 = img_in0_3_address0_local;

assign img_in0_3_ce0 = img_in0_3_ce0_local;

assign img_in0_3_d0 = img_in0_3_d0_local;

assign img_in0_3_we0 = img_in0_3_we0_local;

assign img_in1_0_address0 = img_in1_0_address0_local;

assign img_in1_0_ce0 = img_in1_0_ce0_local;

assign img_in1_0_d0 = img_in1_0_d0_local;

assign img_in1_0_we0 = img_in1_0_we0_local;

assign img_in1_1_address0 = img_in1_1_address0_local;

assign img_in1_1_ce0 = img_in1_1_ce0_local;

assign img_in1_1_d0 = img_in1_1_d0_local;

assign img_in1_1_we0 = img_in1_1_we0_local;

assign img_in1_2_address0 = img_in1_2_address0_local;

assign img_in1_2_ce0 = img_in1_2_ce0_local;

assign img_in1_2_d0 = img_in1_2_d0_local;

assign img_in1_2_we0 = img_in1_2_we0_local;

assign img_in1_3_address0 = img_in1_3_address0_local;

assign img_in1_3_ce0 = img_in1_3_ce0_local;

assign img_in1_3_d0 = img_in1_3_d0_local;

assign img_in1_3_we0 = img_in1_3_we0_local;

assign img_in1bf_address1 = zext_ln66_fu_700_p1;

assign img_in2_0_address0 = img_in2_0_address0_local;

assign img_in2_0_ce0 = img_in2_0_ce0_local;

assign img_in2_0_d0 = reg_557;

assign img_in2_0_we0 = img_in2_0_we0_local;

assign img_in2_1_address0 = img_in2_1_address0_local;

assign img_in2_1_ce0 = img_in2_1_ce0_local;

assign img_in2_1_d0 = reg_564;

assign img_in2_1_we0 = img_in2_1_we0_local;

assign img_in2_2_address0 = img_in2_2_address0_local;

assign img_in2_2_ce0 = img_in2_2_ce0_local;

assign img_in2_2_d0 = reg_571;

assign img_in2_2_we0 = img_in2_2_we0_local;

assign img_in2_3_address0 = img_in2_3_address0_local;

assign img_in2_3_ce0 = img_in2_3_ce0_local;

assign img_in2_3_d0 = img_in2_3_d0_local;

assign img_in2_3_we0 = img_in2_3_we0_local;

assign img_in2bf_address1 = zext_ln66_fu_700_p1;

assign lshr_ln11_fu_722_p4 = {{ap_phi_mux_x171_phi_fu_510_p4[6:2]}};

assign lshr_ln17_fu_599_p4 = {{ap_phi_mux_x_10169_phi_fu_454_p4[6:2]}};

assign lshr_ln_fu_644_p4 = {{ap_phi_mux_x_9167_phi_fu_477_p4[6:2]}};

assign num1_4_fu_776_p1 = img_in1bf_q1[7:0];

assign num2_4_fu_810_p1 = img_in2bf_q1[7:0];

assign num3_4_fu_706_p1 = im_axis_in_TDATA[7:0];

assign num4_1_fu_623_p1 = im_axis_in_TDATA[7:0];

assign num4_2_fu_578_p1 = im_axis_in_TDATA[7:0];

assign num4_fu_684_p1 = im_axis_in_TDATA[7:0];

assign x_10_fu_740_p2 = (ap_phi_mux_x171_phi_fu_510_p4 + 7'd4);

assign x_8_fu_662_p2 = (ap_phi_mux_x_9167_phi_fu_477_p4 + 7'd4);

assign x_9_fu_617_p2 = (ap_phi_mux_x_10169_phi_fu_454_p4 + 7'd4);

assign x_fu_678_p2 = (ap_phi_mux_x_8165_phi_fu_488_p4 + 7'd4);

assign zext_ln11_fu_732_p1 = lshr_ln11_fu_722_p4;

assign zext_ln18_fu_693_p1 = lshr_ln16_reg_906_pp2_iter1_reg;

assign zext_ln30_fu_639_p1 = cnt_1166_reg_461;

assign zext_ln34_fu_654_p1 = lshr_ln_fu_644_p4;

assign zext_ln48_fu_594_p1 = cnt_2168_reg_438;

assign zext_ln52_fu_609_p1 = lshr_ln17_fu_599_p4;

assign zext_ln66_fu_700_p1 = ap_phi_mux_cnt170_phi_fu_499_p4;

always @ (posedge ap_clk) begin
    zext_ln11_reg_972[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln11_reg_972_pp3_iter2_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln11_reg_972_pp3_iter3_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //top_module_line_buff1
