// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module top_module_dataflow_in_loop_VITIS_LOOP_190_1_edg_img_0_RAM_AUTO_3R2W_memcore (
     
    address0, ce0,
    d0, we0, 
    q0, 
     
    address1, ce1,
    d1, we1, 
    q1, 
    
    reset, clk);

parameter DataWidth = 1;
parameter AddressWidth = 6;
parameter AddressRange = 42;

input[AddressWidth-1:0] address0;
input ce0;
input[DataWidth-1:0] d0;
input we0; 
output wire[DataWidth-1:0] q0; 

input[AddressWidth-1:0] address1;
input ce1;
input[DataWidth-1:0] d1;
input we1; 
output wire[DataWidth-1:0] q1; 

input reset;
input clk;

(* ram_style = "auto"  *)reg [DataWidth-1:0] ram[0:AddressRange-1];

wire [AddressWidth-1:0] address0_t0; 
reg  [AddressWidth-1:0] address0_t1;
wire [DataWidth-1:0] d0_t0; 
wire we0_t0; 
reg [DataWidth-1:0] d0_t1;
reg we0_t1; 
reg [DataWidth-1:0] q0_t0;
reg [DataWidth-1:0] q0_t1; // 

wire [AddressWidth-1:0] address1_t0; 
reg  [AddressWidth-1:0] address1_t1;
wire [DataWidth-1:0] d1_t0; 
wire we1_t0; 
reg [DataWidth-1:0] d1_t1;
reg we1_t1; 
reg [DataWidth-1:0] q1_t0;
reg [DataWidth-1:0] q1_t1; // 



initial begin
    $readmemh("./top_module_dataflow_in_loop_VITIS_LOOP_190_1_edg_img_0_RAM_AUTO_3R2W_memcore.dat", ram);
end 


assign address0_t0 = address0;

assign d0_t0 = d0;
assign we0_t0 = we0;


assign q0 = q0_t1;

assign address1_t0 = address1;

assign d1_t0 = d1;
assign we1_t0 = we1;


assign q1 = q1_t1;


always @(posedge clk)  
begin

    if (ce0) 
    begin
        address0_t1 <= address0_t0; 
 
        d0_t1 <= d0_t0;
        we0_t1 <= we0_t0;


 
        q0_t1 <= q0_t0;

    end

    if (ce1) 
    begin
        address1_t1 <= address1_t0; 
 
        d1_t1 <= d1_t0;
        we1_t1 <= we1_t0;


 
        q1_t1 <= q1_t0;

    end

end 







//read first
always @(posedge clk)  
begin 
    if (ce0) begin
        if (we0_t1) 
            ram[address0_t1] <= d0_t1; 
        q0_t0 <= ram[address0_t1];

    end
end 
 






//read first
always @(posedge clk)  
begin 
    if (ce1) begin
        if (we1_t1) 
            ram[address1_t1] <= d1_t1; 
        q1_t0 <= ram[address1_t1];

    end
end 
 


endmodule

