-- -------------------------------------------------------------------------------
-- This file has been automatically generated by the Caph compiler (version 2.8.4d)
-- from file main.cph, on 2018-05-11 at 12:39:30, by <unknown>
-- For more information, see : http://caph.univ-bpclermont.fr
-- -------------------------------------------------------------------------------

library ieee,caph,work;
use ieee.std_logic_1164.all;
use caph.core.all;
use caph.data_types.all;
use ieee.numeric_std.all;
use work.all;
use work.edgeDetectionOk_globals.all;

entity abs_sum is
   port (
    arg0_empty: in std_logic;
    arg0: in std_logic_vector(13 downto 0);
    arg0_rd: out std_logic;
    arg1_empty: in std_logic;
    arg1: in std_logic_vector(13 downto 0);
    arg1_rd: out std_logic;
    arg2_full: in std_logic;
    arg2: out std_logic_vector(13 downto 0);
    arg2_wr: out std_logic;
    clock: in std_logic;
    reset: in std_logic
    );
end abs_sum;

architecture FSM of abs_sum is
begin
  comb: process(arg0, arg0_empty, arg1, arg1_empty, arg2_full)
    variable p_gx : signed(13 downto 0);
    variable p_gy : signed(13 downto 0);
  begin
    -- arg1.rdy, arg0.rdy, arg2.rdy / p_gy=arg1, p_gx=arg0, wr(arg2,fabs(p_gx)+fabs(p_gy))
    if arg1_empty='0' and arg0_empty='0' and arg2_full='0' then
      p_gy := from_std_logic_vector(arg1,14);
      arg1_rd <= '1';
      p_gx := from_std_logic_vector(arg0,14);
      arg0_rd <= '1';
      arg2 <= std_logic_vector((fabs(p_gx)) + (fabs(p_gy)));
      arg2_wr <= '1';
    else
      arg0_rd <= '0';
      arg1_rd <= '0';
      arg2_wr <= '0';
      arg2 <= (others => 'X');
    end if;
  end process;
  seq: process(clock, reset)
  begin
    if (reset='0') then
    elsif rising_edge(clock) then
    end if;
  end process;
end FSM;
